### ISSUE TITLE
Go coding rules for verification

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1009]
As we plan to verify the go codebase in part or in full at some point, we're going to put a few basic restrictions in place about Go coding to greatly simplify the later verification work. It may not be possible to completely avoid these, but any exceptions should be well considered. The restrictions so far are:

- Don't use `interface{}`. 
  - Example exceptions: error-handling infrastructure:
  - https://github.com/netsec-ethz/scion/blob/master/go/lib/common/errors.go#L33
- ~Don't use closures.~
  - Example exceptions: handling panics:
  - https://github.com/netsec-ethz/scion/blob/master/go/lib/spkt/pld_ctrl.go#L48
- Don't use reflection.
  - Example exceptions: None.
- No racy implementations such as lock-free data structures.
  - Example exceptions: None.

These restrictions do not apply to test code (i.e. code in `_test.go` files).

**Comment by mueller55** [comment]
We should add:
* no racy implementations such as lock-free data structures

**Comment by kormat** [comment]
>1.5 years later, the codebase is done fine on everything except "Don't use closures". Closures are in _heavy_ use throughout the codebase, and changing that doesn't seem feasible in the short or medium term.

**Comment by scrye** [comment]
Closures, `interface{}` and `reflect` are used heavily both in the data-plane and control-plane. This makes verification quite a bit more challenging, but it's needed by a lot of the RPC/server code.
