### ISSUE TITLE
Drop zookeeper

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1025]
Zookeeper as we currently use it has a number of problems:
- the default server values mean it takes 10s for zookeeper to notice if a node has died, which is way too long. We can configure it to take much less time (currently it's set to 1s), but there is zero documentation or discussion i can find about whether this is safe/sane/supported.
- when leaving the infrastructure running for an extended period of time (e.g. over night), there are usually periods of time where our services lose their connection to it. Normally this rectifies itself, but sometimes it doesn't, meaning our services (at a minimum) need to be restarted
- there's a huge amount of complexity with handling connection issues with kazoo (our zk client library). It took months of work to get it mostly stable, but there are still bugs. E.g. https://github.com/netsec-ethz/scion/blob/master/lib/zk/cache.py#L194 is sometimes triggered.
- zookeeper is very resource intensive (e.g. ~400M, 8% cpu on my desktop right now), and to get it to keep up with the load we use a ramdisk as the log dir (`/run/shm/host-zk`) which means a machine crash will corrupt the database.
- there's no encryption or authentication in use. By default zookeeper clients just use plain text for communication. Fixing this is likely to be a sizeable amount of work.

In combination, i'm strongly leaning towards replacing zookeeper with something saner/more modern. It's currently not something we can support for production, at all. From some looking this morning, https://consul.io looks promising, but needs more investigation.

**Comment by kormat** [comment]
For context, here are two bugs i fixed in kazoo:
- https://github.com/python-zk/kazoo/pull/307
- https://github.com/python-zk/kazoo/pull/358

Note also that the kazoo author recommends restarting your process if you lose connection to zookeeper: https://github.com/python-zk/kazoo/issues/2

And here are some issues/PRs about trying to make kazoo/zookeeper reliable in our own code:
- https://github.com/netsec-ethz/scion/pull/64
- https://github.com/netsec-ethz/scion/pull/363
- https://github.com/netsec-ethz/scion/pull/811

**Comment by hausheer** [comment]
I opened a related issue on the scion-coord repo, https://github.com/netsec-ethz/scion-coord/issues/106 to remove zookeeper at least on those nodes that run only one instance of each service.

**Comment by hausheer** [comment]
I observed (on an Odroid device) that zookeeper is shutting down following an exception occurred from thread NIOServerCxn.Factory
