### ISSUE TITLE
Op: Deployment of software and keys in Prod

### ISSUE THREAD

**Issue by klausman** [scionproto/scion#1026]
While we have separated the Prod/Testbed machines, we still need to set up an Ansible tree to actually push to those machines.

- The Ansible key used must be a new one, we can not reuse the one from the testbed
- The `authorized_keys` files need to be decided on (they should also do the SSH_USER thing we do on `deadhippo` for git)
- The SCIONweb instance needs to be plugged into nginx as a uwsgi app (kormat has example files). SSL certs and a vhost are already in place.
- klausman has a truncated SQLite DB for the topology, but it likely needs some tweaking

**Comment by shitz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup alertmanager for prod machines](https://trello.com/c/K3BWPrjh/12-setup-alertmanager-for-prod-machines)

**Comment by shitz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Op: Deployment of software and keys in Prod](https://trello.com/c/BjC8bGUy/11-op-deployment-of-software-and-keys-in-prod)

**Comment by shitz** [comment]
The none SCIONweb part was done and SCIONweb is not part of this repository anymore.
