### ISSUE TITLE
Op: Monitoring of prod infrastructure

### ISSUE THREAD

**Issue by klausman** [scionproto/scion#1027]
Once we have the instrumentation from issue #984, we need to monitor the binaries as they run.

- We need premade dashboards for the various service types (CS, BS etc.)
- We need *some* alerts for those services
- Prometheus needs to be able to either auto-discover those services (this may be possible with Consul) or the Prometheus config needs to come out of SCIONweb.

We should also look at something like [mtail](https://github.com/google/mtail) to do log-side monitoring (this may necessitate a cleanup (issue #984 again) of our logging first)

**Comment by ercanucan** [comment]
+1
- We would need to export metrics to Prometheus from our infrastructure elements. In our dashboards it would be nice info about up paths, down paths, core paths registered, discarded PCBs, etc.
- Generating Prometheus config from scion-web would not be very difficult as scion-web knows about addresses of all the machines in an AS. We could prioritize this task and generate configs from Prometheus until we switch to Consul.

**Comment by kormat** [comment]
We can't use a service discovery to generate monitoring configs; that leads to circular logic. If a service instance never managed to register itself, the monitoring would never know about it, and couldn't send an alert. To put it another way, service discovery can never be authoritative, so we need to generate configs from something that is (i.e. scion-web).

**Comment by kormat** [comment]
(A lot of this is already covered by #984).

**Comment by shitz** [comment]
#1135 added exporting of metrics to BS, PS, and CS.

**Comment by kormat** [comment]
While at some point we might publish some example dashboards, i don't think there's anything else we really need to do here.
