### ISSUE TITLE
Op: Make preseeds for production installations

### ISSUE THREAD

**Issue by klausman** [scionproto/scion#1028]
We current have the [Preseed Config](https://github.com/netsec-ethz/scion-deploy/tree/master/preseed) that makes naked SCION-able machines for testbed-like deployments.

We should have something similar for production machines. Since it can be more specific, it would be closer to directly-deployable than the current preseed is.

**Comment by shitz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Op: Make preseeds for production installations](https://trello.com/c/D3OYngOl/13-op-make-preseeds-for-production-installations)

**Comment by kormat** [comment]
Obsolete.
