### ISSUE TITLE
Capnp groups count as single field

### ISSUE THREAD

**Issue by niederbm** [scionproto/scion#1153]
Fields within a group don't count towards len({...}.schema.fields), the whole group counts as one field. Hence, the sig_packX functions used to pack capnp structs for verification don't reflect changes to schemas that take place within a group.

**Comment by kormat** [comment]
We need to add a utility function that can calculate the number of fields in a capnp proto. This can probably be done by iterating over `x.schema.fields`, and checking the length of each field's schema (if any).

**Comment by kormat** [comment]
This is no longer relevant, as the signature system was fundamentally broken and has been redesigned since. See #1310 and #1336.
