### ISSUE TITLE
AS Certificate Reissuance

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#1183]
### AS Certificate expiration
Certificates are expected to expire in the order of days. Thus a mechanism for Certificate renewal shall be in place for seamless transition between validity periods.

### Certificate Reissuance Request
A Certificate Server proactively requests a renewed Certificate from the responsible Core AS (I.e. the issuer off the current Certificate). A CertReissueReq is signed with the private key of the current Certificate, to ensure the requester is still in possession of the private key. The request is handled by one of the Core AS' CS.

### Certificate Dissemination
Certificates are disseminated by the beacon server to the neighboring ASes as well as to the local Path Servers. An important observation is, that the new Certificate is only needed if ExpTime of new HopEntries is after the current Certificate's expiration time. 
The Beacon server (pre-)fetches the newest Certificate from the CS, such that it can sign new HopEntries. If for some reason the Certificate is not available, the BS has to adjust the HopEntry's expiration time to still fit into the current Certfificate's validity period.

**Comment by shitz** [comment]
@Oncilla is the work here done?

**Comment by Oncilla** [comment]
The issue can be closed. The go implementation now supports certificate reissuance.

Currently, the default topology uses the CS:PY and not CS:GO. Moving over will be done in a follow-up issue.
