### ISSUE TITLE
Need to adjust format strings in checksum_bench.c and dispatcher.c on 32bit ARM

### ISSUE THREAD

**Issue by hausheer** [scionproto/scion#1262]
As discussed with @perrig on 32bit ARM the following changes are necessary

Edit: c/lib/scion/checksum_bench.c
Need to adjust format strings in lines 43 and 60 so those lines then read:
printf("simple_test(%u = %uB): %ju in %ds (%.2lfM calls/s)\n",
printf("complex_test(8+8+2+12+1391 = 1421B): %ju in %ds (%.2lfM calls/s)\n",

In file: c/dispatcher/dispatcher.c
Edit line 872, replacing %lu with %ju:
zlog_warn(zc, "Dropped UDP packets: %ju", drop_count);

**Comment by kormat** [comment]
Ah. To do this in a platform-agnostic way, they should be changed to use the C99 format specifiers, like `PRIu64` (http://en.cppreference.com/w/c/types/integer).
