### ISSUE TITLE
Dispatcher can deadlock if applications do not read from their UNIX sockets

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1278]
The dispatcher can block during UNIX domain socket writes if the buffer gets full because an application is not reading from it. This causes all other SCION services that use the dispatcher to go down.

**Comment by scrye** [comment]
SCMP errors that are not drained from a Conn can also fill the buffer and eventually cause the dispatcher to block forever.

**Comment by shitz** [comment]
Fixed by #1356
