### ISSUE TITLE
Add TRC and Certificate Chain methods to sciond

### ISSUE THREAD

**Issue by mwfarb** [scionproto/scion#1297]
Currently, TRCs and certificate chains are not available from the sciond API.
- Add method to get the local AS Certificate chain.
- Add method to get the local ISD TRC.

**Comment by kormat** [comment]
This might as well be more general, and allow an application to request any version of any trc/cert chain, which avoids the app from having to handle the scion control protocol and querying CSes itself.

**Comment by mwfarb** [comment]
I was wondering if querying any version was reasonable. There are some methods to `get_trc_file_path` for example. However is there a preferable, more direct api to use for trc/crt chain requests?

**Comment by kormat** [comment]
The only current way for an application to handle this would be to query the certificate service directly, but that adds quite a bit of complexity to an app if it is not already handling scion control messages. `get_trc_file_path` only makes sense inside an app which is managing its own trc/cert cache.

**Comment by scrye** [comment]
The Control Service now also listens on TCP, so hosts in the local AS can ask it directly for TRCs and certificates. Does that suffice?

(Maybe SD could act as a cryptography cache, but that only makes sense in very large ASes, and it's not something that is needed right now).

**Comment by mwfarb** [comment]
Certainly, that would do. Thanks!
