### ISSUE TITLE
Add ISD-AS numbers to interfaces in sciond.if_info

### ISSUE THREAD

**Issue by mwfarb** [scionproto/scion#1298]
It's not possible currebtly for tools using sciond API to know the ISD-AS number of the interface the local AS connects to.
- Modify sciond.if_info to include the ISD-AS number with every interface id number returned since the daemon has access to the topology file.

**Comment by kormat** [comment]
I'm not clear what you're referring to. The SCIOND capnp proto responses contain the list of ISD-AS+ifid for all hops in a path.
```
struct FwdPathMeta {
    fwdPath @0 :Data;  # The info- and hopfields of the path
    mtu @1 :UInt16;
    interfaces @2 :List(PathInterface);
}

struct PathInterface {
    isdas @0 :UInt32;
    ifID @1 :UInt64;
}
```

**Comment by mwfarb** [comment]
True. That will give me the ISD-AS+ifid for the paths, but not all interfaces of the source AS may be used by those paths. The goal is to learn the ISD-AS+ifid for all interfaces of the source AS if possible.

**Comment by kormat** [comment]
Ahh, apologies, now i understand. Yes, we should expand `IFInfoReplyEntry` to also contain the remote ISD-AS.

**Comment by lukedirtwalker** [comment]
SCIOND should now be able to tell the local IA. Also the API changed a lot since this issue was created, so closing this.
If you feel there is still something missing please create a new issue, thanks.
