### ISSUE TITLE
Add AS descriptions to sciond.get_paths

### ISSUE THREAD

**Issue by mwfarb** [scionproto/scion#1300]
Currently each AS has only an ISD-AS pair to display to users when requesting paths. It would be helpful to see a short description similar to the the deployment configuration doc or https://www.scion-architecture.net/pages/map.
- Potentially this description could be stored in as.conf.
- Descption could be a hostname ("CMU-SCION-1") or simple, meaningful note ("CMU1").
- Nice to have: country code.
- Nicer to have: geocoordinates.

**Comment by kormat** [comment]
This is not information that belongs in the SCION control infrastructure. You are effectively looking for a SCION-equivalent to WHOIS, which i agree we should have eventually, but is not going to exist in the short-term (at a minimum).

**Comment by mwfarb** [comment]
Now that @perrig and I have discussed it more. It seems like an ISD descriptor is desired before we get to an AS descriptor. 

Tabling the AS descriptor, what about adding an optional ISD descriptor to the TRC? Which #1297 would supply?

**Comment by perrig** [comment]
Hi Mike,

The TRC should contain a "Description", see Figure 16.1 in the book on Page
371. Dominik is currently updating the TRC format to match the format in
the book. Dominik, please chime in ...

All the best,
  Adrian

**Comment by mwfarb** [comment]
@Oncilla

**Comment by kormat** [comment]
There is already a "Description" field in the TRC, which currently in the form of `ISD X`. You could put more meaningful information in there, so long as you are ok with the fact that it is unstructured.

**Comment by Oncilla** [comment]
@kormat is right. The description field is already in the TRC files. Also, Certificates have a field called comment which provides the same functionality.
