### ISSUE TITLE
Add environment variable to control logging verbosity

### ISSUE THREAD

**Issue by mlegner** [scionproto/scion#1330]
Currently, a lot of information is logged in DEBUG logs which would have to be turned off individually for each service.
It would be great to have some environmental variable which specifies logging verbosity for all services at once.
This would be particularly useful for Raspberry Pi and similar systems running on SD cards.
The environment variable could default to the current setting.

**Comment by kormat** [comment]
While it would be possible to add this, currently the python code is pretty indiscriminate about which information is logged at which levels, and not logging debug statements would greatly increase the difficulty of tracking down problems. An example that came up earlier today - sciond logs the paths it sends to a requester at DEBUG, and there were two cases where that information is vital to understand what's going on. 

The other thing is that the python processes are run from supervisord, which provides the environment (see http://supervisord.org/subprocess.html#subprocess-environment for details). This means that if you change the env var, you need to _shutdown_ supervisord and restart it, which is non-obvious (i.e. using `./supervisor/supervisor.sh shutdown`). Just doing `./scion.sh stop; ./scion.sh start` won't change anything (nor will `./supervisor/supervisor.sh restart \*`).

Is the concern that the SD card i/o is too slow? Or that it might wear out the card? What filesystem are you using?

**Comment by hausheer** [comment]
As far as I know, too many writes on the SD card reduces the lifetime of the cards, so it would be preferable to reduce the writes to a minimum. We are using ext4 filesystem.

**Comment by hausheer** [comment]
@stschwar can you see this?

**Comment by kormat** [comment]
> As far as I know, too many writes on the SD card reduces the lifetime of the cards, so it would be preferable to reduce the writes to a minimum. 

Ok, at least we're on the same page.

> We are using ext4 filesystem.

This is a bad idea, the journal gets touched for ~all I/O, which causes that part of the storage to wear out much much faster than the rest. I would recommend either using a filesystem specifically designed for flash devices, or using a non-journaled filesystem like ext2.

**Comment by hausheer** [comment]
@xabarass maybe you could take a look at this too. http://ideaheap.com/2013/07/stopping-sd-card-corruption-on-a-raspberry-pi/ proposes a number of good practices in order to reduce access to SD card

**Comment by stschwar** [comment]
@hausheer Yes, I do.
It seems like we are still figuring out, how we want to solve this issue fundamentally. Without being too familiar with the codebase yet, would it make sense to pass the logging level via `./scion.sh` like so `./scion.sh run --log=debug`?
Alternatively, if we want to disable extensive logging on Raspberry Pi only, we could try to identify the platform and dis-/enable logging accordingly.

**Comment by hausheer** [comment]
@stschwar The user should be able to turn on logging on a RaspberryPi if needed.

**Comment by xabarass** [comment]
We can create additional partition that will be used only for log files, there we can disable journaling, increase commit time and other optimizations we can think of. This way when power is lost, only log files might get corrupted, but we will be saving flash writes. Benefits of journaling FS will still be there for the rest of the data (that is mostly read only). 
To achieve this, no changes in scion code base are necessary as we can just symlink `logs` directory on devices with flash memory.

As this is a tricky process, we cannot expect user to do it manually, scion images for Raspberry PI should be generated with proposed structure. 

Does it make sense?

**Comment by hausheer** [comment]
@xabarass Yes, my idea was to include all that in the image, such that the user doesn't have to deal with it. In my point of view, the proposed solution makes sense. 
I noticed that we don't have any place to keep track of issues/scripts related to RaspberryPi (image creation etc.). Shall we add those in the scion-box repo or would it make sense to create a separate repo?

**Comment by xabarass** [comment]
I am hoping to finish initial version of image creation service soon. We can create repo for that and assign all the issues there.

**Comment by shitz** [comment]
It seems this has been resolved as far as this issue is concerned.
