### ISSUE TITLE
Missing instructions for contributors

### ISSUE THREAD

**Issue by andviane** [scionproto/scion#1357]
The project is missing a document that would help to understand rules required by this community. Or, if such document is present somewhere, then it is difficult to find.

* It is not clear who is the person or mailing list to contact before contributing to the project, are there any documents required to sign before the contribution, which kind of copyright headers do you require or accept or do you accept ad hoc pull requests.
* It is not defined which testability criteria the main code should meet, where are interfaces required. Due Go having no virtual methods it is easy to get a code that is completely non Unit-testable.
* It is unclear which types of Unit tests are required, which are optional and which would not be accepted at all that is a grave enough experience. 
* It must be clearly documented on which standard functions should **not** be used, and which replacements should be used instead (like So -> SoMsg in Unit tests, or maybe closures in the main code).
* Any coding style rules that are still an issue after both code formatter and linting tools are applied must be explicitly listed and the less of them the better.
* Ideally the document should also list some tasks the newcomer could take over. Even if no longer up to date, these may serve as examples.

See [GNU Classpath](https://www.gnu.org/software/classpath/docs/cp-hacking.html) or [OpenJDK](http://openjdk.java.net/contribute/) for the examples of such documents. The code review is not a replacement for them.

**Comment by scrye** [comment]
Fixed in #3744. Some bullet points (testability, interfaces) are best discussed depending on the issue the contributor is working on, but the documentation now contains details on how to reach out for feedback early in the contribution process.
