### ISSUE TITLE
API inconsistency in go/lib/ctrl

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1367]
`Pld.PackPld()` serializes a `SignedPld` structure (instead of `Pld`), while `NewPldFromRaw()` deserializes a `Pld`.

For clarity, `Pld.PackPld()` should be the inverse of `NewPldFromRaw()`. `SignedPld.PackPld()` should be the inverse of `NewSignedPldFromRaw()`.

**Comment by kormat** [comment]
`PackPld()` follows from `WritePld()`, for which the current behaviour is required. Existing code currently passes around `*ctrl.Pld` as a `common.Payload`, and expects `WritePld()` to do the full serialisation.

**Comment by kormat** [comment]
Closing as this is a consequence of the data-structure design and how we use it.
