### ISSUE TITLE
sciond should handle local BR being down

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1389]
If a local BR is unreachable, sciond will not receive any SCMP revocations, and keep handing out potentially stale paths from its cache. An app can only detect this by timeouts in traffic. The only option the app has on timeout, currently, is to tell sciond to flush its cache, which is very brute-force. We need Something Better™.

To do things in a more fine-grained fashion, the app needs to notify sciond that a BR (or ifid, potentially subtle issues here in that distinction) is potentially having problems. sciond could ask the BS for the IFInfo for an interface of that BR, but right now there is no reason for an endhost to contact a BS, and i'm not sure changing that is a good idea given how critical the BS is. Another option is to add functionality to the PS so that sciond can ask for revocations for a specific interface, and rate-limit sciond to ask no more frequently than, say, 5s. If either approach returns a revocation, sciond can use it to prune the cache, and then ask the PS for updated paths on the next app request.

**Comment by scrye** [comment]
#3743 will mean SCIOND never sees a revocation. If a link is down, applications will need to try different paths. If applications in an AS need more information, the AS can deploy custom health monitoring for its internals, but it's not something that needs to be part of every SCIOND.
