### ISSUE TITLE
Use infrastructure message dispatcher in SCIOND client library

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1424]
SCIOND requests include an ID, but the client does not take it into account when reading responses. This means it's not safe to issue multiple requests at once, since they might be reordered (e.g., sending out requests 5, 6, and getting back responses 6, 5).

Plugging the infrastructure dispatcher in `go/lib/infra/disp` between the SCIOND client and the reliable socket would solve this.

Using the infrastructure message dispatcher will also decouple the SCIOND client from the reliable socket protocol, allowing other local transports (such as pure UNIX DGRAM) to be used instead.

**Comment by kormat** [comment]
Fixed by #1449
