### ISSUE TITLE
Switch to 64b ISD-AS numbers

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1451]
The existing 32-bit ISD-AS numbers are divided into 12bits for ISD (~4k ISDs) and 20bits for AS (~1m ASes). The latter is likely to be too small in reality. It's possible that many existing BGP ASes will split into multiple scion ASes, and it's important we don't make the mistake of making the namespace too small.

My proposal is as follows:
- Switch to 64b ISD-AS numbers
- The top 16b will be for ISDs, of which the top 4 will be reserved. This retains the existing ~4k limit on ISDs for the moment, which is desirable because ISD proliferation is something we want to avoid for scaling reasons.
- The bottom 48b will be for ASes. These AS identifiers will be *global*, not scoped to the ISD as they are in the current design.

The reasons for going for global AS identifiers are:
-  It allows multi-homed ASes (e.g. a business that is in multiple ISDs) to have a clear connection between its multiple ISD-AS identitier, as the AS number will be the same.
- It means that existing BGP ASes can have their AS number ported directly to SCION, which makes things easier for everyone, and is easier to explain. The current BGP AS namespace is 32b, with first 16b of values fairly densely populated, but the remainder of the space is very sparsely used at the moment. Any _new_ SCION AS ids would be provisioned above the 32b boundary, to avoid any potential clashes.
- The major scaling issue in core routing for SCION is the number of core ASes. With the current system an AS that is a core in multiple ISDs must propagate separate beacons for each ISD. This leads to many more beacons than are needed, especially in the case of existing tier1 ISPs which will probably be core ASes in many ISDs. By switching to a global AS identifier, beacons could potentially have a single AS id, but a list of ISDs that the AS is a member of, and thereby have a single beacon instead of one per ISD. This needs to be investigated more closely to see if it would actually work, but the global AS choice at least makes it something we can explore.

**Comment by kormat** [comment]
To properly support ASes being in multiple ISDs AS Certs should list all the ISDs that an AS is a member of. This has some really nice benefits. There is now zero dependency on a naming service to tell you that `[1-11],addr` is also available at `[1-20],addr`, which means it also works for IP addresses, and not dns-style hostnames. Another benefit is that, if core CSes get the ability to maintain a list of ASes per ISD, a  CSes could support "Give me any cert for AS X". This allows you to bootstrap from the situation where you only know the AS number.

**Comment by shitz** [comment]
One point brought up by @sgmonroy is that this will necessitate global coordination on AS numbers. We already need this for ISD numbers, thus I don't see this as a blocker, but it's a trade-off to keep in mind.

**Comment by kormat** [comment]
@shitz : yes, this is part of the deal. My hope is that it would be done by IANA, like https://www.iana.org/assignments/as-numbers/as-numbers.xhtml.

**Comment by tklenze** [comment]
Thanks for clarifying how an AS can be part of multiple ISDs with only local AS numbers -- I've asked myself that question a while ago (the answer is: it can't, that's why we need global AS numbers).

While this change shouldn't incur any bandwidth overhead for standard SCION on the data plane, what about SCION extensions? Are there any that include the ISD-AS IDs of every hop? (Initially, I was thinking of OPT, but that does not seem to include the ISD-AS ID of each hop.)

**Comment by kormat** [comment]
I have created a wiki page to document the new ISD/AS allocation scheme: https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering

I think we should also support `_`'s as thousands-separators (like python3.6 does) in AS numbers, to make it easier to parse for humans. E.g. `4294967294` optionally becomes `4_294_967_294`. Both formats would be accepted.

**Comment by kormat** [comment]
> I think we should also support _'s as thousands-separators (like python3.6 does) in AS numbers

This is done as part of #1457.

**Comment by kormat** [comment]
Finished in #1478 and #1483
