### ISSUE TITLE
Unsupported payload type error msgs from BRs

### ISSUE THREAD

**Issue by jonghoonkwon** [scionproto/scion#1461]
I have investigated the huge size of log files generated by BRs running on Core ASes, and I observed that most of the error msgs are about `unsupported payload type pldType="*scmp.Payload"` and `Error validating packet`.
The error msgs are produced only from the BRs connected to AWS machines. 
The followings are the actual logs for the each case.

=============== log type: 1 ===================================================
> 2018-03-19 06:43:33.755293+0000 [EROR] Error processing packet rpkt=a2fe648a err=
>  Unable to process unsupported payload type pldType="*scmp.Payload" pld="Meta: Info=85 CmnHdr=1 AddrHdr=2 PathHdr=3 ExtHdrs=0 L4Hdr=1 L4Proto=UDP
>      >   Info: InfoF=3 HopF=5 IfID=3 Ingress=true RevToken=106a50040401030f358911090d05a002036054310d02011119e733690102013375010201ff78f9bb8de612e7f603417a12cf32707e2e2bcb74eb1b6fd0d533f85825705312bb51380101010131690201000031710201010131790201000031810201000031890201010131910201010131990201010131a10201010131a90201000031b10201000031b90201000031c10201010131c90201000031d10201ffcbd17620c91039ba3f20779922f912656a1bddd516ada01bb73e9d6375db900527d366bb3b397c4f97eac23995c303dfd06250e450dccf40596d094dcb44a9ad4124e3b0e31d4b7a4bbc34073392f372bd31a880ad18e8b5b58fa838835902374f950c08fee79668b4b47e6862a6a56adb0a55ed67717f0362bf1a7e3378884e2754da45a454eb1562f9675d63f657e2612363c28ab43f5babc6a483492d3e3ce8e18b76dbb8d62abf13aef9f7f9d4660fed59381da20af0fe9e32d3e8cc173b28853ec499f34ee1bc94c2a258aae899b21cbd6bb3f5a5aac7e658162175fe6f2ce6e78a9cd952f599f486fa4a540ad7ef0078ee22a0c2b049607dd51d5d262d6871fe4b9e86cdb44631d5a261a03f978623563c6ca3a1fbea63c329166b4f386638b0f115d887ffce70acb449b6924451fe83b240bd01ca795f996454903114ea395ac640e40991b3c6fdc20c59757757ad893e5a00e8d58b11c01ab90f584fbac662a5b5799aa0993654587a4193e2ab389c4961116c89281b617e2db7f15e10e851a2f3630ac1097b674b19cd3f59345973f03950ba83ce0d37d24efc1f7042a6b482f4ca647b01cb77b4be81dfc425ae22a5c4b0af90fd0772bc4562bf6a21960ee271544982d3994aaea7359296739099e487de3fbdde620133fdcf4565b5b863b7b2ecc2090fbfa12b1fa861afe791a4bc6ae035fa63d9920c22e05967ff
>      >   CmnHdr: 00c1034d06030500
>      >   AddrHdr: 02a0000502a0000700000de56b8d0000
>      >   PathHdr: 005aaf5c15002a020040000003f0f831003f00300015bebc
>      >   ExtHdrs: 
>      >   L4Hdr: 794100000315e38f
>      >   "

=============== log type: 2===================================================

> 2018-03-20 15:26:46.206004+0000 [EROR] Error validating packet rpkt=94d0e2d5 err=
>  Interface revoked ifid="0xc4212cced8"
>      CT: PATH(3):REVOKED_IF(4) Info: InfoF=3 HopF=4 IfID=3 Ingress=false RevToken=106a50040401030f38b711090d03a002036054310d02011119e733690102013375010201ff60b59d6cd4c945e7035fb7e45fb437ebd317a57ca110d8debef05d2be4a12745b351380101000031690201000031710201000031790201010131810201010131890201010131910201000031990201010131a10201010131a90201000031b10201010131b90201000031c10201010131c90201000031d10201ff4e0fb427a97ba1aa3fdffb26e834b00bf638a950270e48f933f89124f6f8eac056f7124b5c3353beb780274e0ad071b96706d0facf8b865af3ca7c71820e942836bb91e0b38e9b81b5e3bd221c4fc07eded7e6bc3f816eeab68c4a494d22d5991c4d35ada49ef5000fa35540b5ff720d014943aa395d0bd15206b51f21bc86efbd2260c38a902cd7fccab16a268c167ee70bd552466ae41c3bb97876bc99470ac50c970db5846fc1a97c53da745deb7c8be2cf3a20ae04c3949dfff1c4e6ffbde47fd782195c07bd009f032ddfbf12de94b0171845d189fbc3aa692945750fceb802f6e1026a8c6ccc2e38d9f658a16846799c168d0b957bb8332b47b3f7adb4ed0f0e796e1a1793b266c09f9058b1c92d41b9f5a90872e7e088079cca1d3dc8daf4656abcc4718d94825e5f974ede3f5310148224405ce7d456b0e7ef4b040928ce107f04eeeed27815d9d21048c1f0bcdd641631a560ecc4e4118367304973745015670a6655bff3303dfff9c44c02f09396671dd6d7be3951da0d5e819ffac0eecc353e7bcd94b0b66e3a6059e2848850b655e06c284487a46a756603c1bef1ce6b8cd8027444b123ea54f94a77b21f4c74e8d1cd22acb42c2e2d58bcf8fccfa6aff712b0f46f84246278fe0acbbd41e69b955e67aa97cb16b477b77bc82548e8dc3068f93c44ca42e0366eaf4d9444c2c4061a8c634c0dbd922519265203ed

**Comment by kormat** [comment]
Updating based on the slack discussion:

The second log entry is known - we should just stop logging when we receive a packet for a revoked interface, and just export a prometheus metric instead.

The first type happens when a BR is running on the same IP as other services, and thus intercepts scmp errors received over an interface that are destined for that IP. If this happens when the other side of the link has revoked their interface, then the revocation will never be handled properly, and the local AS will never be informed about it, so traffic will keep trying to use that interface.

The basic issue here is that the BR would need to have support for parsing all possible SCMP error types in order to determine who they should be delivered to. Until we have that, running a BR's interface on the same IP as any other service is not supported.

**Comment by sgmonroy** [comment]
This is from the legacy router, does not apply anymore.
