### ISSUE TITLE
Go applications should support dispatcher restarts

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1474]
Currently if the dispatcher restarts while a Go process is running, the process will lose connection and never recover, while the python code ~gracefully reconnects. We need to add this capability to the go libraries too.

**Comment by kormat** [comment]
#1621 is related.

**Comment by scrye** [comment]
Reopening because this does not cover the Border Router, Certificate Server and SIG yet.

**Comment by scrye** [comment]
Closing this as the issues are now tracked by https://github.com/scionproto/scion/issues/1896, https://github.com/scionproto/scion/issues/1897, https://github.com/scionproto/scion/issues/1898.
