### ISSUE TITLE
Add support for multiple internal addresses and interfaces to the BR

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1481]
Currently, the border router can only listen and use one internal address/interface. This creates a problem when a BR router should be reachable through multiple physical network interfaces for redundancy reasons.
The current design of handling multiple internal interfaces needs to change, since it would require the BR to support full IP routing to know on which interface it needs to forward a packet towards the internal network.
One proposal is to have the BR read from and write to a single virtual network interface and let the kernel do the overlay routing.

**Comment by kormat** [comment]
The simplest solution is to have the BR listen on a wildcard address. That way the kernel will pick the appropriate OS interface and source address when sending packets to the local AS.

**Comment by shitz** [comment]
There could be performance implications down the line when there is only a single socket to read from/write to. We will have to deal with that when it becomes an issue.

**Comment by sgmonroy** [comment]
Given that we want to delegate routing and internal interfaces management, I don't think we can then support mixed io (ie. Posix and HSR) per internal address.
Instead, Posix would be used by default unless other io is built. We could add some config parameter to select which io to use if multiple are available/built-in.

**Comment by sgmonroy** [comment]
Although it is still unclear if the BR will support dual stack and its design for it, the current approach for multiple internal interfaces could be any of the following proposals:
- Virtual IP
- Interface Bonding
- Bind to a loopback address using a routing protocol to advertise the route.
