### ISSUE TITLE
SIG: Implement allocation discovery protocol

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1485]
Requirements:
- CS needs support for publishing the IAC (Ip-Address config) for an AS, which lists its IP allocations, signed using [RPKI](https://en.wikipedia.org/wiki/Resource_Public_Key_Infrastructure) and the AS cert.
- Each AS must register their IAC with all core issuing ASes in their ISD.
- The core CS must support IAC registration/caching.
- A crawler service needs to be written to periodically query every ISD for new/updated/removed IACs,  verify them vs RPKI and the relevant AS cert, and generate a config file for the SIG.
- The SIG needs to support two separate allocation(/routing) tables: a static one for allocations configured manually by the local admin, and a dynamic one for allocations discovered via IACs. When deciding where to send a packet, the SIG should first consult the static allocation table, and if it doesn't match then try the dynamic allocation table. This way admins can override dynamically discovered allocations (albiet at their own risk).

**Comment by kormat** [comment]
I've just come across a major blocking issue to this: not all sites that deploy a scion AS will be their own BGP AS. E.g. ETHZ is part of SWITCH's AS: https://bgpview.io/asn/559#prefixes-v4. SWITCH announces separate prefixes for the various educational institutions, but it is the owner of the prefixes.

**Comment by scrye** [comment]
New gateway (#3932) has this implemented, albeit with a different algorithm (gateways query the ASes they care about directly for the prefix allocations). RPKI is not supported yet.
