### ISSUE TITLE
Add tests for scion-pki

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1488]
scion-pki needs tests

**Comment by shitz** [comment]
Have a look at `go/lib/xtest/binary/loader.go`. This will allow you to build `scion-pki` from your test and then call it with various arguments. 
As a first step, it would be useful to have end2end test such as:
* Given a `isd.ini`, does `scion-pki` generate the correct TRC
* Given a `as.ini`, does `scion-pki` generate the correct certificate(s)
* Generally making sure that existing files do not get overwritten without `-f`

There are also several places where unit tests would make sense, e.g.,
*`conf.As.validate`
*`conf.Trc.validate`
*`pkicmn.ProcessSelector`

**Comment by scrye** [comment]
Closing due to age. `scion-pki` will change significantly for X.509, and the change will also include tests.
