### ISSUE TITLE
Make the signing algorithms for online/offline keys configurable.

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1492]
Currently, the signing algorithms that are used with the online/offline keys are hardcoded to `ed25519`. The AS configuration (`as.ini`) should have a fields to make this configurable.

**Comment by jinankjain** [comment]
@shitz Any specific set of signing of algorithms you have in mind that `scion-pki` should support?

**Comment by jinankjain** [comment]
@shitz currently while generating TRC as.ini is not checked. So how about introducing this parameter inside isd.ini like for all the coreAS?
