### ISSUE TITLE
SCIOND Rewrite in Go

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1494]
As part of our core infrastructure rewrite efforts, SCIOND needs to be redesigned and rewritten in Go. The current design discussion can be found here: https://docs.google.com/document/d/1j3GawuIETb20aP7Pztm-ukoPfpSA_fAeeJWkl5ovxCY/edit?usp=sharing

**Comment by kormat** [comment]
This is blocked by https://github.com/scionproto/scion/issues/1474
