### ISSUE TITLE
Read signing algorithm from TRC when signing a new issuer certificate

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1496]

**Comment by jinankjain** [comment]
@shitz Currently in the TRC there is no field associated with respect to which signing algorithm to be used when signing a new issuer cert?

**Comment by jinankjain** [comment]
There are two different types of `trc` one is defined here [1](https://github.com/scionproto/scion/blob/master/go/lib/crypto/trc/trc.go) and [2](https://github.com/scionproto/scion/blob/master/go/tools/scion-pki/internal/conf/isd.go). And `scion-pki` uses the second one. I think we should unify the structs (i.e. thats why I got confused)

**Comment by shitz** [comment]
`isd.ini` is not a TRC. It contains some of the configuration needed to generate a TRC. `scion-pki` takes `isd.ini` as an input to generate the actual TRC. When signing an new issuer certificate `scion-pki` should check in the current TRC which `OnlineKeyAlg` should be used.
