### ISSUE TITLE
Dispatcher in Go

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1498]
The current dispatcher hasn't aged well and is also too simple by not doing any encapsulation/decapsulation work. The goal of the new dispatcher would be to offer a similar interface that an eventual kernel implementation would offer, such that it could also act as a replacement for kernel support where that is not easily possible to add.

**Comment by jinankjain** [comment]
@shitz I am thinking of doing this task. At this point in my thesis I am stuck with extending c dispatcher to make it understand APNA Ephemeral ID which would involve implementing some crypto stuff which is already there on Go side or just rewrite this in Go.

Could you elaborate a bit more on this task what exactly that needs to be done? Is it just a rewrite using CGO or there are some design changes?

**Comment by shitz** [comment]
@jinankjain The idea here is to not just rewrite the current C dispatcher, but to basically replace it with a component that would implement the same interface as an eventual SCION kernel implementation.
In particular, this would also mean that the dispatcher does encapsulation and decapsulation of SCION packets, i.e., an application just hands over the payload and the destination (potentially including path etc) and the dispatcher does the rest. A lot of this is currently done in `snet`, but there of course it's not language agnostic. Obviously, the new dispatcher would also need to implement all the functionality that the current dispatcher offers.
This is a really big task and would require very close collaboration, thus I'm not sure if it would be feasible for you to do during your thesis...

**Comment by jinankjain** [comment]
@shitz Thanks for the update :smile: I will hack something in the current dispatcher to do the translation which I need for the thesis.

**Comment by scrye** [comment]
Implemented as of https://github.com/scionproto/scion/pull/2388.

In the end we decided to go with a dispatcher that is functionally equivalent to the C dispatcher. This allows for a simpler API between applications and dispatcher. Most of the advanced dispatcher logic mentioned in @shitz's comment above will be implemented via libraries in SCION applications.
