### ISSUE TITLE
SIG: Integration Test Setup

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1499]
The SIG is a highly complex piece of software and needs a proper integration testing setup that allows us to make sure changes do not break functionality. The integration test setup will involve spinning up a SCION network and run SIGs in several ASes that can then be used by test applications to test various functionalities.

**Comment by worxli** [comment]
- CI? e.g. only for `sig-*` and master branches
- LXC needed? Docker network enough?

**Comment by worxli** [comment]
Idea: 
- Spin up  ~ `Default.topo` with per subnet user defined docker networks
- Add Sigs to different ASes, add traffic policies and run `ping`
- Then modify traffic policies

**Comment by worxli** [comment]
- Ping
- Iperf

**Comment by worxli** [comment]
- ideally there would be a basic SIG integration test that would just test basic encap/decap as a sanity check
- and then have an acceptance test that test various policies, different scenarios, reloading, and performance
