### ISSUE TITLE
Write comprehensive control-plane PKI design doc

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1500]
The past weeks have shown that the control-plane PKI is far from a finalized design. Many aspects has been discussed and lots of decisions have been made. To have them all in one place we need a comprehensive design doc that merges the basic (but outdated) description in the book with the various documents that have been produced in the past few weeks, and adds any missing points left.

Here is a collection of what has been written so far (some of the things might already be outdated):
* TRC Design by @Oncilla: https://docs.google.com/document/d/1T5UMI6IZldaFXMpPYCmCgVqGWGc4O3jYewWHYejE6eA/edit?usp=sharing
* Trust Verification Specification by @scrye: https://docs.google.com/document/d/1Nfw8RuF73x18fMefKwoPRHzenqbZDH0BlhV-p2xZNhY/edit?usp=sharing
* Notes on validation by @scrye: https://docs.google.com/document/d/1X_mIfuXqF3fx8_2BT0-Lyu-eS33JOFa6irWtj_BDGTw/edit?usp=sharing

**Comment by scrye** [comment]
Comprehensive docs will be written as part of https://github.com/scionproto/scion/issues/1645 as the CPPKI gets finalized. Closing this as duplicate.
