### ISSUE TITLE
BS should be more proactive when getting first segments

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1509]
Currently the BS does propagation and registration every 5s. On startup (or after its been disconnected for a while) that means it can take 4.9999s before an incoming PCB gets registered/propagated. The BS should be smarter about this - if it has no (or only stale) segments, it should immediately register/propagate PCBs by default. That will allow quicker startup and recovery times.

**Comment by Oncilla** [comment]
fixed by #2672
