### ISSUE TITLE
Proposal: Change human-readable formatting of SCION AS numbers

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1512]
The move to 48bit, globally unique AS identifiers and a numbering scheme that reserves the range`0x000000000000` - `0x0000FFFFFFFF`for BGP AS numbers, has lead to hard to read AS identifiers. E.g., for internal testing we use AS numbers such as `4295002011` which we format as `4_295_002_011`. AS identifiers are ubiquitous in configuration files, file system paths, and log files. Thus, it's of utmost importance that they are easy to read and parse for humans.

I propose a new human-readable formatting scheme for AS identifiers:
* The 48bit AS number is formatted as follows `<upper 16bits as decimal number>.<lower 32bits as decimal number>`, e.g., `4295002011` would be formatted as `1.34715`.
* All grandfathered-in BGP AS numbers would be in the `0.X` range for which we could even drop the `0.` prefix (i.e., no prefix means implicitly `0.`), such that those numbers would be formatted just as current BGP AS identifiers.

Advantages:
I claim that this format is much easier to read for humans. Even though the lower 32 bits could become a large and unwieldy number it's easy to just increase the 16bit 'prefix' to keep numbers small. With current formatting, there is no way around large numbers in the first place. Besides, current AS identifiers could theoretically also span the full 32bit range. Furthermore, it has many practical advantages for testing, development, and local setups, since we could reserve a small range in the `1.` prefix for testing purposes.

**Comment by kormat** [comment]
> it's easy to just increase the 16bit 'prefix' to keep numbers small.

No, because as soon as you that BGP AS numbers become unreadable.

Advantages:
- The representation can be a lot more compact for low 32-bit AS numbers.

Disadvantages:
- It's easy to read it as implying the the left-hand side refers to BGP AS numbers. E.g. i would not be surprised if there was a lot of confusion where something like 4.xxxx was assumed to mean BGP AS xxx in ISD 4.
- It still leaves us with 32bit AS numbers that are very hard to read. E.g. here's the max AS in this scheme: `65535.4294967294`. Comparing that against another AS number is very error prone for humans.
- It's not feasible for a human to visually compare a formatted AS number and the raw AS number, which makes it harder for debugging. E.g. a user enters the following url: `https://4-4295002011,[127.0.0.1]` into their browser, it would currently (probably) reformat that to `https://4-4_295_002_011,[127.0.0.1]`, which a user can trivially confirm is the same AS. In the new format, that would require a calculator or tool to check.

Re: your example of `4_295_002_011` - `4_295` is the documented standard prefix for private use ASes (https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering), the rest is chosen for semantic meaning in our test topo. So the gain here would be changing `4_295` to `1.`, which while it easier to read, i don't think it's a big issue. If people can learn that `192.168` is an private network prefix in v4, i don't think that `4_295` is real stumbling block. Production SCION-only ASes will start at `4_300_000_000` in the current scheme, which won't become unreadable for a Long time.

**Comment by shitz** [comment]
> No, because as soon as you that BGP AS numbers become unreadable.

Maybe it was not clear what I meant. Whenever the numbers in one of the prefixes get too large you'd increase the first decimal (i.e., upper 16bit), so instead of something like `1.123456789` could just increase the prefix and keep the numbers small, e.g., `2.1234`. 



> It's easy to read it as implying the the left-hand side refers to BGP AS numbers. E.g. i would not be surprised if there was a lot of confusion where something like 4.xxxx was assumed to mean BGP AS xxx in ISD 4.

Don't agree with this. The full identifier would still be `4-4.xxxx` (and for legacy BGP AS numbers it could even be `4-XXXX`). Also, I don't know what you mean by left-hand side. 



> It still leaves us with 32bit AS numbers that are very hard to read. E.g. here's the max AS in this scheme: 65535.4294967294. Comparing that against another AS number is very error prone for humans.

I acknowledged this in my description, however, with the current scheme we have no way of avoiding that at all. We always have numbers > 2**32. Whether we format the lower 32bits using `_` for large numbers could be considered separately.



> It's not feasible for a human to visually compare a formatted AS number and the raw AS number, which makes it harder for debugging. E.g. a user enters the following url: https://4-4295002011,[127.0.0.1] into their browser, it would currently (probably) reformat that to https://4-4_295_002_011,[127.0.0.1], which a user can trivially confirm is the same AS. In the new format, that would require a calculator or tool to check.

I'd argue that the user would use the `X.Y` format in the first place so there would be no conversion needed at all. What you are describing can be compared to a user entering a raw UNIX timestamp and that one getting reformatted to some ISO datetime string. Almost nobody does it and if you do, yes you need a calculator.

> Re: your example of 4_295_002_011 - 4_295 is the documented standard prefix for private use ASes (https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering), the rest is chosen for semantic meaning in our test topo. So the gain here would be changing 4_295 to 1., which while it easier to read, i don't think it's a big issue. If people can learn that 192.168 is an private network prefix in v4, i don't think that 4_295 is real stumbling block. Production SCION-only ASes will start at 4_300_000_000 in the current scheme, which won't become unreadable for a Long time.

It's a lot just about the length of the identifier. `4_295_002_011` is so much longer than `1.211` and since those identifiers are ubiquitous it really makes a big difference. For me logging output and identifiers appearing in tests and code are the worst offenders. So far, almost everybody reacted quite repulsive to the current formatting and while it is a small sample size I'm reasonably sure that other people will have a similar reaction.

**Comment by kormat** [comment]
> Maybe it was not clear what I meant. Whenever the numbers in one of the prefixes get too large you'd increase the first decimal (i.e., upper 16bit), so instead of something like 1.123456789 could just increase the prefix and keep the numbers small, e.g., 2.1234.

Ah. That's something that IANA (or similar) would be in charge of, and that doesn't seem to fit without how they tend to allocate numbers. In any case, it's not something we can rely on happening, and there are already private use BGP ASes in the 4.2 billion range (https://www.iana.org/assignments/as-numbers/as-numbers.xhtml)

> Don't agree with this. The full identifier would still be 4-4.xxxx (and for legacy BGP AS numbers it could even be 4-XXXX). Also, I don't know what you mean by left-hand side.

The _AS_ number is now global. It's independent of ISD, can be in many ISDs etc, so we should expect it to be used relatively frequently. (And i meant right-hand side, sorry :) This confusion re: prefix vs ISD is a major concern for me. I think it's very important to keep the namespaces clear, and clearly separated.

> I acknowledged this in my description, however, with the current scheme we have no way of avoiding that at all. We always have numbers > 2**32. 

I don't follow. The current scheme makes it fairly easy for humans to compare _any_ values. That's exactly what it's designed for.

> Whether we format the lower 32bits using _ for large numbers could be considered separately.

The syntax is getting torturous at that point. `-` separator between ISD and AS, `.` separator in the ~middle of the AS number except if it's a BGP AS in which case not, `_` separators on the right of the `.` for large values, etc. That's a mess.

> I'd argue that the user would use the X.Y format in the first place so there would be no conversion needed at all. What you are describing can be compared to a user entering a raw UNIX timestamp and that one getting reformatted to some ISO datetime string. Almost nobody does it and if you do, yes you need a calculator.

That's a reasonable point.

> It's a lot just about the length of the identifier. 4_295_002_011 is so much longer than 1.211 and since those identifiers are ubiquitous it really makes a big difference.

Ok, i have another proposal then: let's use ~ipv6's `::` [approach](https://en.wikipedia.org/wiki/IPv6_address#Recommended_representation_as_text), and do something similar to ipv4-mapped v6 addresses for BGP ASes. This gets us a more compact representation, and avoids confusion re: BGP ASes. 
- It would be 48-bit wide (as opposed to 128b for ipv6), and use `:` 16-bit separators and `::` to indicate `all missing sections are zeros`.
- The equivalent of the v4-mapped v6 prefix is just `::/16`. Anything within that prefix is interpted as a BGP AS and formatted as decimal. `::XXXX` or just `XXX`. E.g. Swisscom would be `::3303` or `3303`.
- All SCION ASes would be in a different prefix. The current `4_295_002_011` would be `1:0:879b`. The current min production AS would be `1:4c:cb00`

(We would obviously change the prefix allocations to make more sense with the new representation)

**Comment by kormat** [comment]
Updated https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering#as-numbers with the v6-inspired propsal. Awaiting feedback before committing to implementation.
