### ISSUE TITLE
Proposal: Increase max segment ttl to 3 days

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1531]
Currently the max segment length of 1 day is an assumption of the protocol. The HopField expiry time unit is derived from it. This makes it impossible for an AS to issue segments with a validity longer than 1 day. My proposal is to increase this to 3 days. An example scenario:

A large company with a number of internal sites is using SCION to route between them, and the outside world. Assuming it does not have a core AS, if its link(s) to the outside world go down, internal routing will break when the segments expire. A 3-day expiry limit gives sufficient time to contact providers etc, even if the outage happens on a weekend.

AS Communities can address this, but that's a lot of extra complexity that may not be necessary depending on the use-case.

Relatedly, currently the HopField expiry unit is defined as `MAX_SEGMENT_TTL / (1<<8)`. I propose we change this to `MAX_SEGMENT_TTL / ((1<<8) - 1)` so that it is actually possible for a HopField to have MAX_SEGMENT_TTL as an expiry duration.

**Comment by shitz** [comment]
Generally, I think it's definitely worth considering this. For completeness I just want to add some trade-offs and considerations:

* Increasing the max TTL to 3 days will also increase the shortest possible TTL to ~17mins (up from ~5.6mins). This also means the granularity decrease from 5.6mins to 17mins steps.
* The main reason that was brought up will also require quite some implementation support: The TTL of a `PathSegment` is defined as the minimum TTL over all `HopFields`. This means that the either the upstream provider of the large company would also need to use 3 day expiration on its hopfields (at least for the hopfields that it propagates towards the large company), or the implementation changes to keep `PathSegments` around for as long as at least one `HopField` is valid (basically redefining the expiration of a `PathSegment`) with the caveat that this `PathSegment` can only be used for certain paths that only include still valid `HopFields`.

**Comment by scrye** [comment]
This was not changed in the recent data-plane path rework and the plan is to no longer change the packet format. We might revisit this in the future with a different path type, but for now the one-day limit stays.
