### ISSUE TITLE
CI: Move to circleci machine executor

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1539]
We currently use circleci's [docker executor](https://circleci.com/docs/2.0/executor-types/#using-docker) for our CI environment. While this gives some nice benefits, it runs in an unprivileged docker container, which prevents us from doing things like adding V6 addresses for testing, or creating network namespaces. The only way around this is to use the [machine executor](https://circleci.com/docs/2.0/executor-types/#using-machine), which means we are given a dedicated VM to run our tests on.

The simplest approach would be to run our existing docker container on that VM, with `--privileged`. This will likely require quite a bit of work to get up and running, and to make it efficient.

**Comment by worxli** [comment]
This would also allow us to do SIG testing on the CI and publish docker images.
