### ISSUE TITLE
Python: fetch trcs & cert chains for verifying SignedCtrlPlds/SignedRevInfos/etc

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1545]
Currently `scion_elem` has support for deferring the processing of a path segment until the required TRCs and cert chains have been acquired. The same approach is needed for signed ctrl payloads and signed rev infos. For signed ctrl payloads this needs to be conditional on the contents of the payload (e.g. don't try to verify payload signatures for trc/cert chain updates), and for rev info this needs to be tied to the ttl of the rev info (there's no point in trying to indefinitely verify a rev info that has expired).

**Comment by worxli** [comment]
Make the cert, TRC fetching more generic. Add callback for when stuff is done, maybe add a custom timer to the item in the queue.

**Comment by worxli** [comment]
there is a question, however, of what it does for path requests in the meantime
i guess the ideal case is that it excludes paths that _would_ be revoked until it knows either way
but that requires some special logic
