### ISSUE TITLE
BS: send RevInfos to PS, not IFStateInfos.

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1549]
Currently the BS sends IFStateInfos to the PS for simplicity, but the PS doesn't care about anything except the embedded RevInfo. Having the BS send a RevInfo directly would mean there's one less (non-obvious) message type the PS needs to implement.

**Comment by Oncilla** [comment]
partially fixed in #2625
When we do no longer support BS:PY we can drop the message handler in the PS

**Comment by worxli** [comment]
Python services are remove from the repo, thus this can be closed.
