### ISSUE TITLE
Prepend control payloads with capnp proto ID

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1562]
Currently all services expect that all UDP/SCION packets received on their control ports have a payload of the format:
- 4B payload length
- Packed `SignedCtrlPld` proto object.
This means that it's not possible to send any other type of message on these ports.

My proposal is to change it to:
- 4B payload length
- Proto id (e.g. `0xdf42b02816bdc1bf` for `SignedCtrlPld`)
- Packed proto object of the specified type.

**Comment by scrye** [comment]
Now that we plan to deprecate control port UDP/SCION messages, this is no longer needed. The control plane transport protocols (currently only QUIC) will natively support RPC mechanisms directly on top of their connections, without any message prefixes.
