### ISSUE TITLE
scion.sh run fails when run within Docker container

### ISSUE THREAD

**Issue by ognjenvukovic** [scionproto/scion#1563]
Hi,

I have followed the instructions for the [Docker build](https://github.com/scionproto/scion/tree/master/docker), and the last step `$ ./scion.sh run` fails.

Setup & Steps:
- Ubuntu 16.04 fresh install in a Virtual Box VM.
- Followed the step-by-step instructions from [Docker build](https://github.com/scionproto/scion/tree/master/docker).
- The last 2 steps:
` $ ./docker.sh run
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.`
`scion@scion:~/go/src/github.com/scionproto/scion$ ./scion.sh run
Compiling...
make[1]: *** No rule to make target 'install'.  Stop.
Makefile:30: recipe for target 'liblwip' failed
make: *** [liblwip] Error 2 `

**Comment by kormat** [comment]
@ognjenvukovic : i believe the problem is that you have not checked out the git submodules. Try running these commands on your host machine, and then rebuilding the docker image:
```
git submodule init
git submodule update
```

**Comment by ognjenvukovic** [comment]
@kormat : thank you Stephen, that solved the issue.
