### ISSUE TITLE
scion takes up to 30s to recover after a failed link recovers

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1576]
There is an series of timers that works badly together in the case of a link recovery:
- The upstream BS has issued a revocation, which can last for up to 10s after the link comes back, during which time no beacons can be propagated.
- The upstream BS has a propagation timer of 5s, so it can take up to 5s after the revocation is expired before it propagates a beacon.
That's 15s. The same applies to the downstream AS (except there it's the registration timer instead of the propagation timer).

**Comment by kormat** [comment]
Things we can do to reduce this window:
- Have both BSes preemptively clear revocations from BRs when a link comes back up, instead of waiting for them to expire.
- Have an BS propagate immediately when a downstream link comes back up, regardless of it's propagation timer.
- Have a BS register new beacons ~immediately when an upstream link comes back up and beacons are received.

**Comment by Oncilla** [comment]
fixed by #2672
