### ISSUE TITLE
Router receiving packet for local delivery should check rp.ifNext

### ISSUE THREAD

**Issue by tklenze** [scionproto/scion#1578]
I think the current implementation is susceptible to a segment truncation attack for down-segments. Let's say that you have the following topology:

```
  A
 / \ 
B   C
 \ /
  D
  |
  E
```

Assume that it's D's policy that end hosts in D can only use the down-segment A-B-D, while end hosts in E are permitted to also use A-C-D-E. An attacker can craft a packet violating D's routing policy. He simply uses the segment A-C-D-E, but puts the ISD-AS of D in the packet. The packet will be delivered to an end host in D, even though it used the illegal path via A-C-D.

(Note that the check for rp.hopF.ForwardOnly is not a sufficient substitute)

If the current hop field is on the down-path and one enters the block in https://github.com/scionproto/scion/blob/af97eb1acd3092a7a94ebc71d7a4fd41121941c7/go/border/rpkt/route.go#L165
then rp.ifNext must be set to a constant indicating the end of a segment.

(On the up-path, truncation is legal. E.g., E can truncate the path E-D-C-A to send a packet to D.)

**Comment by kormat** [comment]
There's a big question about whether FORWARD_ONLY is actually worth the complexity, but putting that aside, can you explain why the forward-only check 2 lines below is not sufficient?

**Comment by tklenze** [comment]
Certainly.

FORWARD_ONLY prevents a packet from being delivered in an AS in *all* cases.
This is in general not desirable behavior. For instance, in the above topology D wouldn't want to set a FORWARD_ONLY flag on its hop field in the segment A-C-D-E, since it prevents E from sending packets to D by (legitimately) truncating the (reversed) path E-D-C-A. ASes will not commonly set the FORWARD_ONLY flag, and are thus susceptible to the attack.

**Comment by kormat** [comment]
The current design assumes that if that's the policy that D wants to enforce, that it would in fact set FORWARD_ONLY on the hop field in segment A-C-D-E, with the implication that traffic between D and E would have to go up to C (or A) and then back down. This is one of the major flaws with FORWARD_ONLY, and why it's likely to just get dropped. At that point there's no attack because there's no policy ;)

**Comment by tklenze** [comment]
I see your point about FORWARD_ONLY being of questionable utility, but its removal will not solve the issue outlined above.

AS D should be able to allow its customer AS E to use a paths that end hosts in D are not allowed to use.

**Comment by shitz** [comment]
@tklenze Thanks for bringing this up. I was actually discussing exactly this case with @sgmonroy yesterday. 
We can definitely introduce this check (and I think it makes sense to do so), however, as you pointed out it only works in one direction. Hosts in D could still use A-C-D as an up-segment and receive return traffic over A-B-D, e.g., in case the remote doesn't use the reverse path or during native multipath communication where it's very likely that both down-paths would be used (one by reversing the received path and one by doing a path lookup to D).

**Comment by tklenze** [comment]
@shitz yes, this is true. The problem can be solved by putting all end hosts into a leaf ASes (ASes with no customer ASes). I presented that at the last SCION retreat.

But until a permanent solution is found, at least we should solve the problem for the down path.

**Comment by kormat** [comment]
Hey. While i'm not sure that this is a policy that SCION has to be able to enforce, i have opened a related issue which will address this as a side-effect: #1585. I've also just opened a proposal to drop FORWARD_ONLY too: #1586

**Comment by kormat** [comment]
As `FORWARD_ONLY` has been removed from SCION in #1586, i'm going to close this as obsolete.
