### ISSUE TITLE
Add support for peer revocations to the Go path combinator

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1597]
Currently, the Go path combinator does not take peer revocations into account when creating forwarding paths. There are multiple ways how to implement this. The most efficient would probably be to pre-process the path segments and remove revoked peering entries before they get added to the graph.

**Comment by shitz** [comment]
@scrye Is this now supported or not? Possibly, this can be closed and new issue should be opened for filtering the "long paths".

**Comment by scrye** [comment]
Closing this as the Go path fetching algorithm already checks for revocations.

Opened https://github.com/scionproto/scion/issues/1695 to track the longer paths problem.
