### ISSUE TITLE
Add option to rebuild binaries involved in tests on each run

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1611]
A few Go tests involve executing binaries. The only available option right now is to refer to an existing binary. This is awkward when the code of the binary has changed, as the developer needs to keep calling `make` before rerunning the test. It also integrates poorly with `goconvey`s web interface test reruns, as make needs to be executed separately from a shell.

An alternative would be to add a flag to tests that want to use existing binaries, and have default test behavior rebuild everything each time. This integrates well with CI environments, as they can use the flag and thus only build the binaries once and have the tests use them, while also simplifying the workflow of testing during development.

The flag can be easily implemented in package `go/lib/xtest`.

**Comment by kormat** [comment]
Tests should not build binaries, or at the very least they should not replace binaries built by the developer. Otherwise using build tags becomes a nightmare.

**Comment by scrye** [comment]
This is just for development and local integration testing, where I would find it to be immensely helpful.

A common scenario is that after some code is changed, an integration test is rerun (e.g., I do it from the goconvey web UI). If the test runs an external binary (say, a server), that binary is never rebuilt automatically, and thus the test runs against stale code. This makes development much more awkward (need to _remember_ to run `make` manually each time, and then run the test itself), especially when using the web ui. It also is prone to errors, where code looks like it works, but it's because the file was accidentally not rebuilt.

Indeed, tests would not replace the binaries. All compiled stuff is put in the test direct in `/tmp`, and cleaned at the end of the test.

This should not impact anything anywhere, really. It's just a QoL change for dev.

**Comment by scrye** [comment]
Deploying bazel fixed this for us. Acceptance/integration tests can list the targets they depend on, and they will be rebuilt when they change.
