### ISSUE TITLE
SIG: Reconnect to SCIOND

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#1621]
If SCIOND and the SIG are started simultaneously, the SIG fails with:
```
[CRIT] Error during initialization err=
>  Error creating local SCION Network context
>      Unable to initialize path resolver
>      Unable to connect to SCIOND
>      dial unix /run/shm/sciond/sd1-ff00_0_110.sock: connect: no such file or directory
```
Because SCIOND is too slow to create the socket. The SIG should at least retry to connect and timeout if it cannot reach SCIOND.

**Comment by kormat** [comment]
Re-opening, #1802 only covers the case of the sig starting before sciond. It does not cover the case of sciond restarting while the sig is running.
