### ISSUE TITLE
Support wildcard 0 AS during path segment fetching

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1623]
The path segment fetcher introduced by pull request https://github.com/scionproto/scion/pull/1619 does not support the wildcard 0 destination AS (e.g., 11-0 or 12-0) for path segment queries. A destination AS of 0 means _any core AS in the destination ISD_.

After https://github.com/scionproto/scion/pull/1619 is merged, support needs to be added for this.

**Comment by scrye** [comment]
Fixed by #1731.

**Comment by kormat** [comment]
Fixed-ish. See https://github.com/scionproto/scion/issues/1778 for the follow-up issue.
