### ISSUE TITLE
Go: interface for untrusted data

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1624]
Proposal:
Any data object that can be received from an untrusted source must implement this interface:
```
type Validate interface {
  Validate() error
  IsValidated() bool
  MustBeValidated()
}
```
`Validate()` parses all (where possible) contained binary data (e.g. `Data` capnp fields), and checks that all values are within legal limits.
`IsValidated()` returns true if `Validate()` has successfully run.
`MustBeValidated()` panic's if `Validate()` has not been successfully run.

This allows code that receives data that should have already been validated (e.g. the path combinator receiving path segments) can ensure that validation has actually happened. This greatly reduces the complexity of error handling, and also allows us to quickly catch paths that fail to validate.

**Comment by lukedirtwalker** [comment]
I have a different proposal. For We introduce 2 types one for the raw format, i.e. the current type, and one for the parsed type. For example for SignedRevInfo:
```go
// Current:
type SignedRevInfo struct {
	Blob    common.RawBytes
	Sign    *proto.SignS
	revInfo *RevInfo `capnp:"-"`
}

// Proposal:
type SignedRevInfo struct {
	Blob    common.RawBytes
	Sign    *proto.SignS
}

func (sr *SignedRevInfo) Parse() (*SignedRevInfoParsed, error) {
....
}

type SignedRevInfoParsed struct {
	*SignedRevInfo
	RevInfo *RevInfo
}
```
This way all code that wants to have the parsed version can indicate so in the signature.
While it is slightly more programmer overhead it brings the following advantages:
* It is enforced by the compiler
* The programmer is forced to call Parse and handle the error
* From the type we can immediately see what data is available, i.e. `SignedRevInfo` doesn't have a parsed `RevInfo` while `SignedRevInfoParsed` does.

**Comment by kormat** [comment]
From the offline discussion:
- While the separate-type approach the compiler helps us, which is nice
- and it would work pretty well for simple types like SignedRevInfo
- but when it gets to larger (and more deeply-nested) types like PathSegment, this becomes unwieldy. You'd need an entire set of parallel types, and everything needs to be parsed/validated at once even if you only care about a subset.

So, let's go with the interface approach for now.

**Comment by scrye** [comment]
We've revisited this pattern a bit over the last few years and it seems like the two-types approach leads to simpler code. The main advantage of it is that once the wire type is parsed, application code can freely work with the parsed type without being concerned about parse state, so less branching/less complexity/less bugs.

If parsing becomes a performance bottleneck, we will need to look at each bottleneck individually to decide what to do anyway, so we can defer partial/lazy decoding solutions until then.
