### ISSUE TITLE
sciond: update capnp union handling in sciond.Pld

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1637]
Currently `go/lib/sciond/types.go:Pld` doesn't handle its union contents very cleanly, leading to a lot of boilerplate being required to construct sciond.Pld's. It should be migrated to the approach used in `go/lib/ctrl` and below, where it has a dedicated embedded `union` type that handles getting/setting the union contents.

**Comment by scrye** [comment]
Superseded by https://github.com/scionproto/scion/issues/3347. The new approach will no longer need the union.
