### ISSUE TITLE
Remove sciond.SvcBR from SCIOND API

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1638]
A service address for the BR does not make sense, so `sciond.SvcBR` should be dropped.

We should also consider dropping the SIBRA SCIOND service, as we're looking at removing the associated flags anyway in https://github.com/scionproto/scion/issues/1622. We can revisit adding the service type when SIBRA gets closer to implementation.

**Comment by kormat** [comment]
#1622 is dropping the sibra flags from the _path request_ call. That's because sibra will use a different api call/messaging in the future. I wouldn't drop the SIBRA SVC address.
