### ISSUE TITLE
snet: fuller error reporting to app, with filtering

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1640]
Currently an app that uses `snet` will, when an SCMP error reply is received, be passed back the L4 scmp header as an `OpError`. While most scmp errors should kill the connection, there are a few exceptions:
- revocation
- oversize packet
- expired HOF
It's application-specific whether the above errors should be passed back to the app or not, depending on its level of sophistication and control. To make this generally useful, an app should be able to mask non-fatal SCMP errors, to allow it to choose which ones to handle. E.g. an app that's letting snet handle path selection probably doesn't need to receive revocation scmp errors.

There is another case, such as with QUIC/SCION, where a library is using the interfaces that snet provides without being SCION-aware. If an application using such a library wants to manage its own paths, a wrapper around snet should be used, which allows the application to specify a callback to be used when certain events happen (e..g a revocation is received). This allows a clean interface combined with flexibility.

**Comment by kormat** [comment]
Also, the scmp payload should be exposed to the app, not just the l4 header.

**Comment by scrye** [comment]
Applications can now customize how they want work with SCMP via the snet SCMP handler:

https://github.com/scionproto/scion/blob/2f106c5b1e33b6c9e7d3342d81ac049ce6b16858/go/lib/snet/dispatcher.go#L66-L67
