### ISSUE TITLE
CPPKI: Complete Control-Plane PKI

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1645]
The control plane PKI needs to be completed. Currently, TRCs are trusted as there are no cross-signatures yet. Also, certificate revocation needs to be closely looked at (currently we rely on auto-expiration).

This is a larger issue and needs to be broken down in smaller chunks as we get to it.

**Comment by scrye** [comment]
Some previous notes regarding the CPPKI, linked from https://github.com/scionproto/scion/issues/1500. They are quite outdated by now, but might still be somewhat useful:
  - TRC Design by @Oncilla: https://docs.google.com/document/d/1T5UMI6IZldaFXMpPYCmCgVqGWGc4O3jYewWHYejE6eA/edit?usp=sharing
  - Trust Verification Specification by @scrye: https://docs.google.com/document/d/1Nfw8RuF73x18fMefKwoPRHzenqbZDH0BlhV-p2xZNhY/edit?usp=sharing
  - Notes on validation by @scrye: https://docs.google.com/document/d/1X_mIfuXqF3fx8_2BT0-Lyu-eS33JOFa6irWtj_BDGTw/edit?usp=sharing

**Comment by Oncilla** [comment]
As the PR route of collaborating on the design doc is a bit cumbersome we move the discussion and collaboration
from #2464 
to stackedit.io.
Open https://drive.google.com/file/d/1LNB20SxY3hHt_sTSLmj8mHcd-T_al8kW/view?usp=sharing using stackedit.io to collaborate

**Comment by Oncilla** [comment]
We have come a long way since the creation of this issue.

The new CPPKI design was announced in #3784
