### ISSUE TITLE
Variable header sizes are a hard problem

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1651]
In an IPv4 world, header sizes are fixed: 20B IPv4 header, fixed-size L4 header, and the rest can be L4 payload up to the MTU. The MTU is (usually) fixed for a given connection, so once that is determined then an application/l4 protocol knows exactly how much space it has to work with, and a starting assumption of 1500B is likely to just work a lot of the time. An application has the choice of either using [PMTUD](https://en.wikipedia.org/wiki/Path_MTU_Discovery) or allowing its packet to be fragmented and have the IP layer handle reassembly.

In a SCION world, things are a lot more complex. The common header is fixed length, but the address/path/extension headers are all fundamentally variable-length. Examples:
- A packet is sent to an SVC address, and the service instance replies from an IPv6 address.
- A different path is selected.
- An extension is added/removed.
  - I recently proposed a nonce header to help give additional proof-of-on-path confirmation, that would only be sent if SCMP error forgeries were noticed.
  - The One-Hop-Path extension is only present for the first exchange of packets between two hosts.
- An extension header changes size.
  - The SIBRA header for reservation renewals is a lot bigger than the normal reservation-use header.

While SCION does have the advantage that a path's MTU is known[0] from the path segments it was constructed from, that doesn't cover the MTU at the endhosts in the src/dest ASes (e.g. a DSL subscriber behind PPoE might have a 1492 MTU). Also note that the MTU may increase as well as decrease (e.g. switching from a longer path to a shorter path).

All of these factors make things Much more complex for an application that cares about how much data it can send in a packet. Note that this value is _not_ the MTU. It's the MTU minus all of the SCION header overhead. So it changes if the MTU changes, but it also changes if any of the headers change size. A better term might be "Maximum L4 Size" (ML4S). In theory, the ML4S can change for _every_ packet. If the application is using a streaming protocol like TCP/SCION, then it is insulated from this issue, provided that the L4 protocol is aware of ML4S, and supports changes in both directions for the ML4S. Any datagram L4 protocol (like UDP, or QUIC) doesn't have this luxury. In the worst case the app would have to query the network stack for the ML4S for each packet before sending it.

There are 2 approaches i see to try and work around this:
- Mandate that all extensions that could be used on a connection must always be present, and all headers are padded to their maximum size. This leads to a lot of overhead, and in the case of path header it's not really possible to say what the max length of a path could be.
- Have the network stack expose the ML4S (and changes to it) to applications, and implement fragmentation for any packets which are too large. The former means that apps that care can reduce (but not eliminate) the chances of fragmentation for their traffic.

Right now it looks like supporting fragmentation in SCION is the only workable solution. It would follow some of the ideas from IPv6 and, e.g. only support fragmentation at the endpoints.

[0] Actually this only holds for the side that constructed the path. The other side doesn't know the MTU currently.

**Comment by scrye** [comment]
This is no longer up to date, things have changed slightly making variable header sizes less of a problem:
- All extensions have been removed. While extensions could be added in the future, we don't know if they will change in size during forwarding.
- Service addresses are only used for RPC endpoint discovery. The discovery mechanism uses small protobuf messages that must stay small in size, and these are used to upgrade communication to QUIC. Applications that want UDP transports need to deal with MTU issues on their own.
- Path switches are done in application libraries, so they can adjust accordingly. The Gateway, for example, always knows what packet size to use.
- OHP is present only on the first exchange (service discovery), but it is special-cased by applications. The built path is then used by different application logic in the gRPC call.

Note that MTU is _still_ a hard problem. Protocols like QUIC make assumptions about packet size and do not do MTU discovery. It's only that variable header sizes (as mentioned in the title) are less common nowadays. Closing.
