### ISSUE TITLE
Path server revocation logic sometimes breaks valid paths

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1660]
If a path server sees that a segment contains a revoked IFID, it will not reply with it. However, there are scenarios where the segment could be used in a valid path. For example, if A-B is revoked, D could still communicate with C if the segments were made available to SCIOND, as A-B is never used to forward information:
```
A
|
B
| \ 
C  D
```

**Comment by shitz** [comment]
@lukedirtwalker can you verify what's the current behavior of the Go PS regarding this issue?

**Comment by scrye** [comment]
Path servers currently reply with segments that have revocations on them, so this is no longer valid.
