### ISSUE TITLE
Extend integration tests

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#1674]
Following parts need integration tests:
- ~~Reissued certificate:
  Make a client which sends a certificate reissuance request and validates that a correct certificate response is received~~ (done as acceptance test)
- Signed payloads:
  Sending and receiving signed payloads. Also, the test should ensure that some of the required certificates are missing locally and need to be fetched from the certificate server.

**Comment by scrye** [comment]
Closing this due to age. The entire control-plane PKI is moving to X.509 (see [here](https://anapaya-scion.readthedocs-hosted.com/en/latest/cryptography/index.html)), so this is no longer up-to-date.
