### ISSUE TITLE
Proposal: Support peering links between core and non-core ASes

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1678]
Many existing ASes that would become SCION core ASes presumably have a lot of existing peering connections. Any of those peers that become SCION core ASes would have their peering upgraded to a core link. So far so good. But it's likely that many of those peers would _not_ be SCION core ASes, and may in fact be in separate ISDs. In order to support this, the proposal is to allow peering links between core and non-core ASes. This would work in the following way:

When a core AS registers a core segment to its local PS, it would add peering HopEntries to the path segment. (Note: it would not _propagate_ a beacon containing peering HopEntries). During path combination, as well as checking for peering links between non-core ASes, the path combinator would also check for peering interfaces between the up-segment and the start of the core segment, and the down-segment and the end of the core segment.

**Comment by scrye** [comment]
We'll probably revisit this in the future because it's something we're keeping an eye on. However, I'm going to close this because the data-plane path format and control-plane service structure have changed recently, so this is no longer up to date.
