### ISSUE TITLE
Infra: Add transport negotiation protocol

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1681]
With https://github.com/scionproto/scion/pull/1680 we have different means of transport we can use. 
To select the protocol to use we should also implement a negotiation or have different ports that serve different protocols.

In more detail:
A SCION server should always support UDP as an unreliable protocol and have at least RPT support for everything that needs to be reliable. On top of RPT the reliable protocol should be negotiated that is preferably QUIC or TCP (once we have it) and only in the worst case RPT. 

Since a server will seldomly remove a supported protocol the selection can be cached on the client side. However in case of error the negotiation of the protocol should be re-initiated.

**Comment by scrye** [comment]
Closing this as transport negotiation is no longer on the roadmap. Control plane speakers will know they either need to talk UDP or QUIC, depending on what message they're sending and whom they're sending it to.

If we need to support multiple transports in the future, their negotiation can be done by extending the address resolution mechanism proposed in https://github.com/scionproto/scion/issues/2554.
