### ISSUE TITLE
Go: don't use the sync/atomic package unless absolutely necessary

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1688]
It turns out there's an alignment "bug" that triggers when you use sync/atomic on structures that aren't aligned according to the platform rules.

https://golang.org/pkg/sync/atomic/#pkg-note-BUG
https://github.com/golang/go/issues/599

This causes subtle cross-platform bugs, and is not worth the complexity for non-critical paths.

**Comment by lukedirtwalker** [comment]
There is now a vet pass called `atomicalign` that should detect those issues. We should use that.
(see https://github.com/golang/go/issues/11891#issuecomment-455085965)
(see https://godoc.org/golang.org/x/tools/go/analysis/passes/atomicalign)

**Comment by kormat** [comment]
@lukedirtwalker : In that case we'd want to have automated testing on at least `arm`, otherwise we won't know when it breaks.

**Comment by kormat** [comment]
Oh, even worse - bazel doesn't support arm as a host platform, so we _can't_ actually build on an arm vm => can't do automated testintg.

**Comment by tmm1** [comment]
Unfortunately `atomicalign` only finds errors for 64-bit unaligned access and thus cannot be used for the 32-bit ARM case.

**Comment by scrye** [comment]
Closing as unactionable. However, note that we have 0 uses of `sync/atomic` in the code base at the moment, so it looks like this is already avoided by us never needing such low-level concurrency optimization primitives.
