### ISSUE TITLE
snet: Ipv6 support

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1710]
snet needs to support IPv6.

**Comment by scrye** [comment]
After @matzf's contributions, this is probably in.

We'll need enhance our end to end test to include IPv6 ASes to confirm that it works, and to protect against regressions.

**Comment by scrye** [comment]
As a first test for this, we should be checking that pure IPv4 ASes can interact with pure IPv6 ASes in the standard end to end test. The end to end test currently has 16 ASes; we should make 8 of them IPv6. They should be as spread out as possible throughout the network.

**Comment by lukedirtwalker** [comment]
Now with #3593 we have a test that tests IPv6 ASes in CI. So we can be fairly confident that this works as it should.
