### ISSUE TITLE
PS: non-reachable non-core AS causes DDoS on cPSes

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1725]
If a popular non-core AS is unreachable, its core ASes will be hammered by frequent requests for down-segments to the unreachable AS. This is because the path lookup mechanism is entirely polling-based, so there's no way for remote ISDs to know when new down-segments are available. They could use exponential backoff, but it doesn't help a lot, as the maximum backoff has to still be fairly small, otherwise the reachability outage will last a lot longer than the connectivity outage.

As the problem is the polling model, my proposal is that we add a pubsub model, at least for this case. Remote core ASes would subscribe to the unreachable AS's core to be notified when down-segments are available. That way they only need to send a small amount of traffic, and still get notified quickly when service returns.

**Comment by scrye** [comment]
Pub/Sub models are no longer on the table for the path construction process. The Go core PS in the remote ISD removes the need for multiple segment requests by replying with both segments and revocations. I assume this can be closed now?

**Comment by lukedirtwalker** [comment]
This is mitigated by the new path lookup strategy with caching. We only get new segments every 5 minutes (configurable). It isn't optimal if an AS isn't reachable via a segment and then registers another, but this should be a rare case (and shouldn't be the case for a popular AS in the first place).
