### ISSUE TITLE
PS: Python PathDB prunes too much

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1735]
There can be situations, especially with core segments, where path resolution in the PS fails, due to the PathDB limiting the answer to at most `k` segments (currently `k == 5`). Due to limiting the number of returned path segments based purely on length of the segments it can happen that no valid combination from `src` to `dst` can be made even though there would be segments in the PathDB that together would form valid paths from `src` to `dst`. To fix that, three things need to be done:

1) The PathDB itself shouldn't limit the number of segments it returns. In Python this means adding a `full=True` parameter to the query.
2) When querying the PathDB not only the destination IA should be taken into account, but also only the possible starting IAs should be included in the query.
3) The final set of path segments must be pruned to an acceptable limit. This has to be done in a way that all segments included in the final path reply can be used to form valid end2end paths from `src` to `dst`.

**Comment by kormat** [comment]
1) should be optional. I.e. the requester should be able to specific a limit.
