### ISSUE TITLE
Pathstore: policy must be checked on both insertion _and_ retrieval.

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1740]
The current python pathstore, used by the BS, only checks PCBs against the policy when they are inserted into the pathstore. When the BS calls `get_best_segments()`, the policy is ignored. An example is `DelayTime` - a PCB which was inserted within the DelayTime parameter can easily persist until it no longer matches the policy, causing the BS to sometimes propagate PCBs that it itself would reject, and indeed its neighbours _do_ reject.

**Comment by scrye** [comment]
This no longer applies to the Go Beacon Server.
