### ISSUE TITLE
Add tests for scmp tool

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#1747]
Currently there are no tests for SCMP tool and it is very easy to brake the application with different changes.

At a minimum, 3 tests should be added for echo, traceroute and recordpath.

**Comment by scrye** [comment]
The tests should use the Go integration suite (more information here: https://github.com/scionproto/scion/blob/master/go/lib/integration/README.md).

For an example integration test that uses the above suite, please see https://github.com/scionproto/scion/blob/master/go/examples/pingpong/pp_integration/main.go.
