### ISSUE TITLE
Makefile for docker images

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#1761]
Replace `./docker.sh` with a Makefile. Maybe this should be in the toplevel Makefile.
- `make docker_base`
- `make docker_scion`
- `make docker_apps` - > docker/perapp/Makefile

Then update `scion.sh` to build the docker images if needed.

**Comment by scrye** [comment]
Instead of makefiles, we went with Bazel (see https://github.com/scionproto/scion/pull/2533).
