### ISSUE TITLE
Go SCIOND should be flexible when routing to wildcard core ASes

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1778]
SCION applications sometimes want to reach a core AS in a remote ISD, without them caring _which_ AS.

To handle such requests, Go SCIOND currently commits to a remote core AS, and then tries to build paths there. However, such paths might not exist. The logic should instead first try to see which paths to the remote core are available first, and then reply with a selection of them.

**Comment by lukedirtwalker** [comment]
We could also just ask the path server with an `ISD-0` query.
