### ISSUE TITLE
Migrate away from "unit" tests that act as integration tests

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1779]
Running integration tests using a unit test framework does not work well:
- there's no logging to allow debugging, no timestamps to correlate failures with the logs of services they interact with.
- it provides a very limited environment (see below).
- using a build flag (`infrarunning`) to prevent the tests being run normally comes with a large cpu and memory overhead as go has to recompile a lot of the codebase. (In CI we have to run each infrarunning test individually, as otherwise the memory usage spikes by 1.6GB and causes OOMs in 4G of ram).

We currently have 3 tests that do this:
- `go/lib/pathmgr/infra_test.go` - this doesn't use _any_ features of the unit test framework.
- `go/lib/snet/integration_test.go` - this will fail if any path request times out, and it assumes that it can run client and server in different ASes on the same host, which we're trying to explicitly move away from.
- `go/sciond/server_test.go` - runs its own sciond with a config that may be incompatible with the running environment.

All of these should work well as normal integration tests, and would increase the reliability/flexibility/simplicity of our testing setup.

**Comment by lukedirtwalker** [comment]
We no longer have infrarunning tests.
