### ISSUE TITLE
go-sciond: Handle zero up/down segments in DB lookup logic

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1780]
https://github.com/scionproto/scion/blob/1a068d8ec9cf34b5748ce66fafe33f1501488a28/go/sciond/internal/fetcher/fetcher.go#L336 if `getStartIAs(downs)` or `getStartIAs(ups)` is a zero length list, the query we should no longer query the database and instead return 0 segments.

**Comment by kormat** [comment]
Maybe it's simplest/possible to handle this inside `getSegmentsFromDB`?
