### ISSUE TITLE
Go path combinator should panic when it detects a cycle

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1782]
If the Go path combinator is fed a set of segments that contain a cycle (this can happen with core segments due to programming errors), it silently enters an infinite loop.

This makes debugging tricky, because the first instinct when debugging a hanging SCION server is to suspect one of the blocking calls (specifically, a bug in `context` handling).

Having the Go path combinator panic in this situation would immediately hint to the problem.

**Comment by lukedirtwalker** [comment]
I think the combinator shouldn't panic but handle it correctly.
In the new default topo if we query from `1-ff00:111` to `1-ff00:112` we will get up segments to `1-ff00:0:130` and to `1-ff00:0:120` and the core segments will be segments between those two cores, thus creating a loop. This should not result in a panic but correct paths that lead from src to dst.

**Comment by scrye** [comment]
Yes, it looks like cycles in the core should be supported.

As @kormat and you proposed, enforcing the exploration restriction of "one up -> one core -> one down" edge in `GetPaths` should efficiently solve the issue. I like it.
