### ISSUE TITLE
The antonym of "core" is "non-core"

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1800]
Until now we've been using "local" to mean 3 things:
- Local to this ISD-AS
- Local to this ISD
- Non-core AS

This leads to confusion. Proposal:
- "local" is the opposite of "remote".
- "non-core" is the opposite of "core".
- "local" on its own means "this ISD-AS"
- "isd-local" or "local ISD" means "this ISD"
- "sciond queries the local PS" (meaning the PS in this IA, regardless of whether it's a core or non-core AS).

**Comment by scrye** [comment]
I think local/remote/core/non-core term use has been pretty consistent lately, so this can be closed.
