### ISSUE TITLE
trust: Add constant for latest version (0)

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1813]
We currently use the literal value 0 for the latest version of trust "material" (TRC, Chains). Instead of having a literal 0 we should introduce a constant, so that it is clear what is meant. The constant should be part of the protocol, since it is also used in requests sent over the network.

**Comment by Oncilla** [comment]
The constant is also present in `go/lib/ctrl/cert_mgmt`. However, the go code does not use it as of now.
https://github.com/scionproto/scion/blob/38bda1325880d765a47d8a872937fff89d23564e/go/lib/ctrl/cert_mgmt/cert_mgmt.go#L25
