### ISSUE TITLE
BR: Acceptance tests

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1814]
We want a test setup for a single BR, send it various packets and inspect the outgoing packet from the BR under test. This way we can make sure that changes to the BR do not break its semantics in an automated way.

**Comment by sgmonroy** [comment]
Non-core AS<sup>1</sup>:

| InLink | OutLink | Result |
| --- | --- | --- |
| child | parent | pass |
| child | peer | pass | 
| child | child | pass | 
| parent | parent | fail | 
| parent | peer | fail | 
| parent | child | pass | 
| peer | parent | fail | 
| peer | peer | fail | 
| peer | child | pass | 

Core AS<sup>1</sup>:

| InLink | OutLink | Result |
| --- | --- | --- |
| child | core | pass | 
| child | child | pass | 
| core | core | pass | 
| core | child | pass | 

1. It is assumed that a packet cannot be sent on the same interface it was received on.

Regarding border router interface configurations:
- Single child interface.
- Single parent interface.
- Single peer interface.
- Single core interface.
- Multiple (2 of each link type) child, parent and peer interfaces.
- Multiple (2 of each link type) child, core interfaces.

**Comment by sgmonroy** [comment]
Closing the issue as the framework has been implemented supporting all current needs.

More tests should be added to cover all corner cases, but we would do this outside this epic.
