### ISSUE TITLE
PS: Implement pull-based PathSegmentSync

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#1817]
Core PSes regularly query Core PSes in other Core ASes about all new down-segments since T.

~**Currently Blocked:**
Until we have support for packet fragmentation in the underlying network stack this will not be very helpful. With this protocol it could easily happen that we have to send many segments and thus more bytes than the MTU. Therefore this issue is currently blocked.~

Wiht QUIC this is feasibly now.

**Comment by lukedirtwalker** [comment]
Specification: https://github.com/scionproto/scion/blob/master/doc/PathService.md#replication-of-down-segments

**Comment by lukedirtwalker** [comment]
Until we have support for packet fragmentation in the underlying network stack this will not be very helpful. With this protocol it could easily happen that we have to send many segments and thus more bytes than the MTU. Therefore this issue is currently blocked.

**Comment by scrye** [comment]
The segment sync mechanism is going away, replaced by #3731.
