### ISSUE TITLE
Rework SCIOND HostInfo

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#1842]
Currently SCIOND fails to transmit all the required network information to reach a service.
The issue lies upon the HostInfo struct that contains only partial information from a TopoAddr:
```
struct HostInfo {
    port @0 :UInt16;  # Reachable port of the host.
    addrs :group {  # Addresses of the host.
        ipv4 @1 :Data;
        ipv6 @2 :Data;
    }
}
```
There are a few issues with this struct:
- Forces the same L4 port for both IPv4 and IPv6.
- It is limited to IPv4 and IPv6 addresses.
- Overlay port is not transmitted, thus it does not support having an overlay port different than the default.

Following are some proposals to address these issues:
```
# Returned for ServiceInfoRequest
struct InfraAddrs {
    addrs @0 :List(InfraInfo);
}
struct InfraInfo {
    l3 @0 :L3Info;
    l4 @1 :L4Info;
    overlayPort @2 :UInt16; # Overlay type is known
}
# If we ever need to represent a non-scion service, like a database.
struct AddrInfo {
    l3 @0 :L3Info;
    l4 @1 :L4Info;
}
# Returned for IFInfoRequest, and as part of PathReplyEntry
struct OverlayInfo {
    l3 @0 :L3Info;
    overlayPort @1 :UInt16; # Overlay type is known
}
struct L3Info {
    type @0 :UInt8;  # HostAddrType
    addr @1 :Data;
}
struct L4Info {
    type @0 :UInt8;  # L4InfoType
    info @1 :Data; # Typically 16-bit port.
}
```

**Comment by kormat** [comment]
While we're at it, we might as well get rid of the anonymous struct in the go definition of `HostInfo`.

**Comment by scrye** [comment]
Most of the interface address types for L3 and L4 have been deprecated in favor of using `net.UDPAddr` everywhere, therefore having a lot of support for various address types is no longer needed in the SCIOND API.

Also, it is unclear what the requirements of a non-UDP underlay/SCION address are, so it's hard to design _now_ how to carry that information across the SCIOND API boundary. For example, URLs cover the scenarios (IPv4/IPv6/DBs) discussed in the top comment, but might be simpler to use.

Also, the anonymous structure was moved to a named type in https://github.com/scionproto/scion/pull/3233.
