### ISSUE TITLE
daemon: Refetch Segments if we have less than *k* results locally

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1857]
Current behavior:
If sciond receives a path request and finds a single path that satisfy the request it will return this path immediately.
Expected behavior:
If sciond has less than *k* paths that satisfy the request it will try to fetch more segments from the PS.

**Comment by scrye** [comment]
It is unclear if this heuristic fixes the issue of segment/path diversity, or just papers over the cracks. For small networks, the current algorithm works, so closing this for now.
