### ISSUE TITLE
Wildcard AS destination should result in at least *k* cores

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1864]
If sciond or a PS receives a ISD-0 request they should make sure that the response contains paths to at least *k* cores in the requested ISD. So that the client can select the "best" core for its needs (e.g. lowest response time).

**Comment by lukedirtwalker** [comment]
Currently the PS and SD will return all paths they have towards the core. But if there is a limit on how many segments/paths they can return, diversity isn't checked. So this is still relevant.

**Comment by matzf** [comment]
This no longer applies -- the control service and daemon return all paths and the number of returned path segments / paths is not limited at this point.

Note: For wildcard queries to the local ISD, only up segments are returned and so this only includes the "provider" core ASes. For remote ISDs, paths to all reachable core ASes are returned.
