### ISSUE TITLE
BR: filter revocations in data-plane

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#1867]
After the BR Control/Data plane split, received revocations should be forward to the control plane for processing (verification and forwarding to other infra services).

Given that if a revoked interface could potentially generate a high number of revocations, it is desirable that the data-plane avoids sending the same revocation multiple times to the control-plane.

**Comment by scrye** [comment]
#3743 plans to remove revocations from the control-plane, so forking would no longer be a thing.

@sgmonroy: I'm guessing this can be closed?

**Comment by sgmonroy** [comment]
Indeed
