### ISSUE TITLE
Topology bind/overlay cleanup

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#1875]
The main goal is to cleanup the topology file as much as possible.
The two main changes to achieve this are:
1) Move bind address from topology to env (the bind address is only important for its own instance).
2) Define AS global overlay ports for infra/dispatcher and BR.
   Currently we have a default overlayPort and also we can specify different overlay port per service.
   The proposal is to have a default overlayPort for all infra/dispatcher and another overlayPort for BRs.
   It also introduces a requirement of a different address per IFID.

To support multiple IFIDs on the same address #1001 (ie. IXP networks), we need to determine the IFID of a packet by its source address which should match an IFID remote address (this is obviously subject to address spoofing).

**Comment by scrye** [comment]
Topology was simplified in https://github.com/scionproto/scion/pull/3440.

Regarding the points in the top comment:
- bind addresses for services are no longer supported in Go code; bind addresses for underlay (overlay, in the old terminology) ports are still supported s.t. BRs can sit behind NATs
- custom bind underlay (overlay, in the old terminology) ports are ignored
- ASes still have underlay UDP port 30041 hard-coded

Note that this only changed how topology files are interpreted in Go applications, the file format itself was not changed, so the _Breaking change_ label is removed.
