### ISSUE TITLE
sciond: Go sciond is not informed about first hop revocations

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1876]
In the python sciond we had a flush flag which meant that the local path segment cache would be cleared and new segments are fetched from the PS.
In the Go sciond we no longer do flushing, we instead just have a refresh flag which means fetch new segments from the PS and then reply.

This leads to Go sciond possibly never be informed about a revocation, which is on the first hop. 
The client will time out when waiting on the response but does not know that the interface has been revoked. 
The PS will not return segments with revoked on-segment interfaces. 
That means sciond will assume that the segment is still valid and return it again to the client.

Possible solutions:
1. The client informs sciond that it assumes a certain interface is broken. Sciond will then query the PS for this explicit interface. This could be done using an IFStateRequest.
2. PS returns "interesting"/"recent" revocations in the reply if the refresh flag is set. (Note that for this the segverifier probably has to be adapted to consider all revocations)
3. The refresh flag could again be used to flush the DB.

**Comment by kormat** [comment]
Related: https://github.com/scionproto/scion/issues/2871

**Comment by scrye** [comment]
To deal with link issues, the current plan is to go with #3743. This means SCIOND will never see a revocation, so we don't need to implement this any more.
