### ISSUE TITLE
PS,BS,SD: topology reload must deal with adding/removing interfaces

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1881]
If a fresh topology has added or removed an interface, the applications need to handle it appropriately.
BS:
- Update the list of interfaces to beacon/ifid through.
- Update the state of interfaces.
PS,SD:
- Evict all segments that used a removed interface.

**Comment by scrye** [comment]
Other than the eviction, everything is supported right now by the Control Service/SCION Daemon. Closing this.
