### ISSUE TITLE
segverifier: Possible optimizations

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1884]
Current segverifier groups revocations and segment into verification units and verifies units in parallel. This could result in revocations being verified multiple time.

There are also other optimizations that are possible:
* Only do work that is needed, i.e. do not verify segments or revocations that we already have in the local storage (verified).
* Only verify each segment/revocation once.
* Optimize replies in the PS, i.e. only include relevant peer revocation that could actually be on a path to the destination.

**Comment by scrye** [comment]
@lukedirtwalker: With control-plane revocations being removed by #3743, is this something we can close?

**Comment by lukedirtwalker** [comment]
yeah let's close. If we want to optimize we should have clear numbers on what is a bottleneck.
