### ISSUE TITLE
PS: DownSegmentSync using timestamps can be racy

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#1891]
If we use a timestamp to check what we synced already this can always lead to problems.

With the current `segsyncer`:
1. Segment is inserted at T
2. Segsyncer reads segments at T
3. Segsyncer sets last synced segments to T
4. Another segment is inserted at T
5. At the next sync segsyncer will not see the segment inserted in step 4.

This problem is very likely to happen if the resolution of T is one second, less likely if resolution of T is 1 nanosecond. However the problem is still there.

Slightly better would be to use timestamps in the pathdb, then we can use `now` to set the timestamp in the DB. But this might still be problematic if we use transactions (we need a serialized time).

Alternative solutions:
1. Using T >= lastUpdated in step 5, but this will lead us to resend the segment until a new one is inserted.
2. Use a version counter that is incremented on every insert/update (of down segs), only do down-seg sync if the version was incremented. (improves 1.)
3. Have a global counter on each segment that auto increments on update/insert, only remember the last number that was sent. This might lead to overflow problems.

**Comment by scrye** [comment]
The segment sync mechanism is going away, replaced by #3731.
