### ISSUE TITLE
SIG: sig.json needs to contain the sig's local allocation

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1893]
In a mis-configured setup, if a SIG receives packets that for an allocation it doesn't own, it will re-forward them through itself to the correct destination. This is open to abuse, and should be prevented. Specifying to the sig what its local allocation(s) are would allow it to drop these packets.

**Comment by scrye** [comment]
With #3932, gateways now can specify their local allocations via the routing policy file. See the [PR contents](https://github.com/scionproto/scion/blob/1cfb0742b00ef0968590110addc02af42e483b1b/go/pkg/gateway/routing/doc.go) for more info on how to configure.
