### ISSUE TITLE
SIG should reconnect to the dispatcher

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#1896]
If the dispatcher restarts, the SIG is currently not capable of reconnecting. Also, losing connectivity with the dispatcher generates a huge amount of logs that can quickly fill up storage.

The SIG should be able to reconnect to the dispatcher.

**Comment by kormat** [comment]
In the interim, the sig should exit if the dispatcher socket closes, because the disk filling symptom is a major problem.

**Comment by scrye** [comment]
Reconnecting to the dispatcher is awkward for high-throughput data-plane sockets like the SIG.

SIG protocol implementations that care about high availability in the event of dispatcher crashes should look into opening a socket on the underlay directly.
