### ISSUE TITLE
Proposal: rework segment ASEntries

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1904]
The current path segment format contains:
```
struct HopEntry {
    inIA @0 :UInt64;  # Ingress (incl peer) ISD-AS
    remoteInIF @1 :UInt64; # Interface ID on far end of ingress link
    inMTU @2 :UInt16;  # Ingress Link MTU
    outIA @3 :UInt64;  # Downstream ISD-AS
    remoteOutIF @4 :UInt64;  # Interface ID on far end of egress link
    hopF @5 :Data;  # Raw HopField
}
```
This causes a lot of duplication, as everything except the HopField is actually link-specific, and not hop-specific, which means any HopEntries which share the same links include the info.

Another issue is that if an AS has hundreds or thousands of peering links, the PCBs become huge and unwieldy.

Proposal:
Add an ASEntry-level "link information" list. It would contain every relevant interface ID, and its associated remote AS/remote interface id/mtu/latency/etc. HopEntry would then only contain the raw HopField.

The link information for a given AS can be versioned, and if it grows beyond a certain size, the AS can just reference the version instead of including the whole list every time. A down-stream AS can then query up-stream if the link info version changes (or if it didn't have a copy to begin with). This removes a huge amount of data that rarely changes from PCB propagation.

Using the link info block also allows an AS to not include hop fields for all peering interfaces in its PCB. The down-stream AS has full knowledge of the peering interfaces that it is allowed to use, and we can add a mechanism where it can request hop fields for specific peering interfaces it wishes to use.

**Comment by scrye** [comment]
We're currently looking into moving this to protobufs, and estimate that the number of peer links should not be an issue for quite some time. Closing this as a _Won't fix_, but we might look into this again in the future if it becomes a problem.
