### ISSUE TITLE
SIG: Reloading needs redesign.

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#1907]
`Unable to add network ia=IA net=IP/24 err="Networks.Add(): Networks overlap new="&{0xc4262c6f58 {28 281105609525249} 0xc4260f3860}" existing="&{0xc42000ede0 {28 281105609525265} 0xc420cfcc60}""` is not quite a helpful error message.

This happens when reloading the SIG config while moving allocations, thus the reloading logic needs to be rethought..

**Comment by scrye** [comment]
With the overhaul of #3932 this should no longer be an issue.
