### ISSUE TITLE
PS: logs are far too verbose

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1908]
In a testlab environment, the PS logged 660M of logs in 4 days, including 3.8 million debug lines.

Just looking at the last 8 hours:
- 59M of logs
- 547k lines
- 354k log entries
- 74 non-debug entries

**Comment by kormat** [comment]
A breakdown of the entries:
- `[Messenger] Received message`: 98886
  - `type=SegReg`: 74576
  -  `type=SegRequest`: 2416 
  - `type="SegSync"` 21894

**Comment by scrye** [comment]
Fixed by https://github.com/scionproto/scion/pull/1947.
