### ISSUE TITLE
Infra: infra dispatcher logs error on Close

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1911]
When `pathmgr.Revoke()` is called, it creates a new reliable conn to sciond, and starts a new infra dispatcher. The infra dispatcher spawns a goroutine to read incoming messages. When the revocation processing is done, the pathmgr calls `Close()` on the connection. This causes the reliable socket to be closed _first_, and then the reading goroutine to be stopped. This means that it will usually log an error like:
```
2018-09-19 12:54:09.454131+0000 [WARN] error id=ccf642e3 goroutine=dispatcher_bck err=
>  transport error op="RecvFrom"
>      read unix @->/run/shm/sciond/default.sock: use of closed network connection
```
which is really hard to track down.

**Comment by scrye** [comment]
The current plan is to move the SCIOND API to gRPC, which means the infra dispatcher will no longer be used (see https://github.com/scionproto/scion/issues/3347).
