### ISSUE TITLE
BR: Packet to local AS through remote AS

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#1928]
When running traceroute on the default topo from 1-121 to 1-122 we get the following path `1-ff00:0:121 48>72 1-ff00:0:120 72>48 1-ff00:0:121 94>24 1-ff00:0:122`. Where `1-ff00:0:121` to `1-ff00:0:120` is an up segment and `1-ff00:0:120` to `1-ff00:0:121` to `1-ff00:0:122` is a down segment. In this case traceroute does not get an answer from the border router in `1-ff00:0:121` (connected to `1-ff00:0:120`) because the BR creates a reply to its own AS with a path through `1-ff00:0:120`. 

In theory such a path is valid, the Go path combinator filters these paths but the python version does not. But the border router should still know how to handle such a packet.

**Comment by sgmonroy** [comment]
This is from the legacy router, does not apply anymore.
