### ISSUE TITLE
SD.go: remove expired segments from pathdb

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1933]
Go sciond does not currently expire path segments from pathdb. In combination with #1931, this means it hands out very old segments in some circumstances.

**Comment by lukedirtwalker** [comment]
Note that the Go PS already implements this behavior. See `go/path_srv/internal/cleaner/cleaner.go`. To run the cleaner periodically, in main:
```go
cleaner := periodic.StartPeriodicTask(cleaner.New(pathDB),
	time.NewTicker(300*time.Second), 295*time.Second)
defer cleaner.Stop()
```
