### ISSUE TITLE
Proposal: Use a non-linear scale for hop expiry.

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1948]
The current unit for hop expiry is multiples of ~5m38s. While this is probably fine on the low end, it doesn't make a huge amount of sense on the upper end. 23h57m vs 23h52m isn't a meaningful choice. The current unit is tied to the max path ttl, which is bounded by the AS cert renewal period. #1531 proposes increasing the max path ttl to 3 days, and it remains to be seen what the AS cert renewal period actually turns out to be, thus decoupling the hop expiry from the actual max allowed path ttl and the AS cert renewal allows us to be much more flexible in the future.

So, the proposal is to have a non-linear scale for hop expiry that fits into 8b, starts with a ~5min ttl, and scales up to ~1 week.

**Comment by scrye** [comment]
This was not changed in the recent data-plane path rework and the plan is to no longer change the packet format/semantics behind the fields. We might revisit this in the future with a different path type, but for now the linear scale stays.
