### ISSUE TITLE
Ctrl payloads need to distinguish between request and reply.

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1949]
Currently the capnp struct looks like:
```
struct CtrlPld {
    union {
        ...
    }
    reqId @9 :UInt64;
    ...
}
```
The convention we have is that a requester sets the reqId in the request, and the responder sets the same id in the response. This breaks when system A sends out a request with reqID X, and meanwhile receives a request with reqID X from elsewhere. This causes the infra dispatcher to map the incoming request to the out-going request, leading to failures like:
```
2018-10-06 12:02:12.820677+0000 [EROR] Failed to find core segs debug_id=f64aaebf src=24-ffaa:0:1 dst=24-ffaa:0:3 err=
>  [Messenger] Type assertion failed debug_id="01457571"
>      Unable to type assert disp.Message to *path_mgmt.SegReply msg="24-ffaa:0:13 -> 24-ffaa:0:3, Flags: {false false}"
```
To avoid such collisions, we should add an extra field to CtrlPld to indicate if this is a request or a response packet.

**Comment by scrye** [comment]
Because we now support transport protocols in the control-plane stack and plan to move to a complete RPC mechanism, we get request/response matching for free, and thus no longer need the extra field.
