### ISSUE TITLE
BR: allow user to specify how many buffers to allocate

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#1981]
Currently the BR allocated 1024 buffers in the free pool, and each socket tries to grab 32. This means that at 32 sockets, all buffers are taken by default. When there are more than 32 sockets, depending on the traffic pattern it's possible for a socket to end up with zero buffers. In this case it will block waiting for free buffers to be available, but it's non-deterministic when it will succeed.

The BR allocates the free buffer pool at start. While in theory this could be relative to the number of sockets it will use, that number isn't fixed as config reloading may add (or remote) interfaces. Also from an operational perspective a simple multiplier factor isn't a good solution, a given BR may need a higher or lower number depending on traffic patterns/historical usage/etc.

The proposal is to add a cmdline flag to the BR to specify how large the free buffer pool should be. If not specified we can default to 1024. We should also calculate a minimum value of buffers that is reasonable, something like `(64 * num_sockets) + 512)`, and fail to load a topology file if the new value would be larger than the flag-specified value.

**Comment by sgmonroy** [comment]
This is from the legacy router, does not apply anymore.
