### ISSUE TITLE
Dispatcher: reversing packets with SVC destination address

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#1997]
Currently packet reversing is only used when creating replies for SCMP echo/traceroute/recordpath packets.

This works as long as the destination is not an SVC. In the case of SVC destination address, the dispatcher would need to:
1. Resolve SVC addresses
2. Possibly allocate more space for the address header, ie. SVC to IPv6 address.

NOTE: It is not clear if this is a desired feature and if SVC Multicast should be supported as it is a trivial amplification attack.

**Comment by scrye** [comment]
Service multicasts are no longer supported and the dispatcher will be deprecated soon (see scionproto/scion#3961). Closing this.
