### ISSUE TITLE
BS: send ifids if zk is down

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2021]
The current design is that only the master BS in an AS will send ifid packets, propagate beacons, register path segments, and revoke interfaces. However, if master election is broken (e.g. zookeeper is down), then there will be no BS sending ifid packets, and all neighbours will revoke its links. This is a consequence of moving ifid sending from the BR to the BS (which was done to cover the case where a BR is up but has no connectivity to the local AS).

Proposal:
A BS should send ifid packets if:
- master election is working and it is the master
or
- master election is not working.

**Comment by kormat** [comment]
A downside is that a BS that loses connectivity to master election will keep all reachable interfaces up, even if the actual master BS is revoking some of them.

**Comment by kormat** [comment]
One way to mitigate this might be to expand the IFID payload
```
struct IFID {
   origIF @0 :UInt64;
   ifidQuorum @1 :Uint8;   
}
```
If a BS is master, then it sends IFID packets with ifidQuorum set to `1`, meaning that one IFID sender is sufficient for the neighbour to consider the link to be up. 

If master election is down, all BSes would send IFIDs with the quorum set to some pre-determined value (e.g. (n/2)+1 of the number of BSes running; actual value depends on operational approach and policy of AS); if the neighbour receives ifids from ifidQuorum BSes across that link, it considers the link to be up.

If a subset of BSes lose connectivity to master election, they will send IFIDs with the higher quorum set, but the neighbour will disregard them when it receives the IFID from the master, as it self-fulfills the contained quorum.

**Comment by Oncilla** [comment]
> ... keep all reachable interfaces up, even if the actual master BS is revoking some of them.

To me it is unclear what `revoking` means in this context. Does it mean stop sending ifid keep-alives?
If so, what would be the purpose of this in the first place?

**Comment by kormat** [comment]
@Oncilla: for example, there is a network partition, and the master BS loses connectivity with a given BR. A BS that still has connectivity to that BR and sends IFIDs over it will cause the neighbour to believe that the interface is usable.

**Comment by scrye** [comment]
The current plan is to improve control-plane / data-plane separation; this will include moving the keepalives back to BRs. We'll release start releasing some contributions in this direction soon-ish.

ASes interested in detecting internal partitions and reacting to them must deploy custom internal health checks.
