### ISSUE TITLE
Sig: set source IP in sig routing table

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2023]
Currently the sig routing table entry is a plain `default via sig metric 100`. This does not specify a default source address, so packets from the local machine going through this routing table will end up with an arbitrary source IP. This causes all sorts of mayhem, so we should stop doing that. :)

**Comment by sustrik** [comment]
Given that the source IP may be different for each peer AS, I assume this should be done by specifying the address to use in the config file, then doing setting the source address explicitly via sendto().
