### ISSUE TITLE
Add path test functionality for showpaths tool

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2039]
It would be useful if `showpaths` were able to check the health of printed paths, for users to be able to differentiate between healthy, revoked, unknown, etc. This mode of operation could be enabled by specifying a flag, e.g., `-p`.

**Comment by sustrik** [comment]
The original idea was to use SVC_BR (see #1801) to check the health of the path. However, I think it muddles the layering of the stack.

SVC_BR implies that the packet reaches BR application but it in fact does not. It only reaches the dispatcher which in turn generates the reply.

The alternative would be to use SVC_NONE instead, with the semantics "don't even try to dispatch to a specific service and reply straight away".

That of course, would require dispatcher to live on all nodes in the network, including the BRs. But that may be a reasonable requirement in the first place: If the dispatcher is, in fact, an ersatz kernel, then running without a dispatcher is like running without a kernel.
