### ISSUE TITLE
Parsing from raw functions should check that the buffer is big enough

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#2050]
As an example, MetaFromRaw should check buffer length before trying to parse anything from the buffer:
```
func MetaFromRaw(b []byte) (*Meta, error) {
        if len(b) < MetaLen {
                return nil, common.NewBasicError("Can't parse SCMP meta subheader, buffer is too short",
                        nil, "expected", MetaLen, "actual", len(b))
        }
        m := &Meta{}
        if err := restruct.Unpack(b, binary.BigEndian, m); err != nil {
                return nil, common.NewBasicError("Failed to unpack SCMP Metadata", err)
        }
        return m, nil
}
```

**Comment by karampok** [comment]
I have been going through functiosn that are named `*FromRaw` or they include a `common.RawBytes` or a `[]byte` as argument.
```
ag "^func .*\(.*common.RawBytes.*\)" |grep FromRaw
ag "^func .*\(.*\[\]byte.*\)" |grep FromRaw
```

A large number of *FromRaw functions are using the ` proto.ParseFromRaw(a, b)` which is
guarded by a `SafeDecode` function that transform the panic into an error.

Found some minor issues (pushed the changes)

@sgmonroy do you have more concrete experience where I should look into?
