### ISSUE TITLE
PathSegment encapsulation and caching do not play well together

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2090]
`PathSegment` exposes the `ASEntries` slice but only offers `ID` and `FullId` as methods. The ID methods cache the id internally. If the `ASEntries` are changed the ID cache has to be invalidated. However programmers will have a hard time to remember this. So I see 3 solutions:
1. Hide `ASEntries` and only expose it via controlled methods.
2. Always calculate the ID values.
3. Introduce a second immutable type for the parsed segment.

**Comment by Oncilla** [comment]
PathSegment has been reworked in the meantime.
The ID is simply recalculated every time. It is done in very few places anyway, and if it turns out to be too expensive calling code should take care of caching.
