### ISSUE TITLE
SIG: Add SIG SVC address and SIG SVC address resolution to the BR

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#2120]
A new SVC address for the SIG should be introduced and the BR needs to understand and resolve that address to one of the existing SIG instances. Also, SIGs need to be added to the topology.json.

**Comment by sustrik** [comment]
We still need to add SIGs to topology generator. Given that it's hard to run SIGs unders supervisor, this is blocked on #1776.

**Comment by sustrik** [comment]
Blocked on #2115

**Comment by sustrik** [comment]
Actually, adding SIGs to the topology stretches this issue too far. This will be solved as part of #2186.
