### ISSUE TITLE
SIG: Add support to use the SIG SVC address to discover a SIG in a remote AS

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#2121]
The SIG should be able to use the SIG SVC address to discover a SIG in a remote AS. To that end, it sends discovery packet to the SIG SVC address and uses the response when establishing a new session with a remote SIG.
Exact contents of the discovery and the reply packet need to be worked out, as does interaction with existing static configuration of SIG remotes (e.g., should those serve as fallback or are static configurations always preferred).

**Comment by sustrik** [comment]
First steps are going to be as follows:

1. Do SvcSIG thing first. If not available, fall back to static configuration.
2. Remove static configuration altogether.

In this phase we are not going to change the format of keepalive packets among SIGs.

To decide: Should we keep some old SIG addresses at hand in case the remote AS will send us consistently to a dead SIG? How would that work when the local SIG is restarted? Save those addresses in a file? When will they expire? Do we even care about this corner case enough to add this much complexity? Etc.
