### ISSUE TITLE
Proper encapsulation for error handling

### ISSUE THREAD

**Issue by sustrik** [scionproto/scion#2140]
Currently the Go codebase uses BasicError which can in turn contain nested error and so on.

This breaks basic encapsulation semantics for functions: The caller of a function has to be aware of the entire underlying call tree to guess what kind of errors they could get. In other words, a change in a function 5 layers deep in the call stack can change API of the function you are calling. Other way round, if you add a new error to a function, it changes API of every function that calls this function, even indirectly so.

Also, complex multi-dimensional errors incentivize developers not to handle them with care, but pass them up the stack instead, to the caller, who has even less context to properly handle the error. Once the error bubbles up to the top level there's rarely more to do than to log it and hope everything still works.

An alternative would be to report only a small set of errors for each function (e.g. OK, TIMEOUT, DISCONNECTED) which can be handled by the caller without too much work. Also, having only few possible error types means that the implementer of the function has to actually think for at least few seconds about how they want to present each individual error condition to the user.

**Comment by scrye** [comment]
Regarding how we handle errors, we decided to go in the same direction as the Go core library (see Go 1.13 release notes https://golang.org/doc/go1.13#error_wrapping) in https://github.com/scionproto/scion/pull/3159.
