### ISSUE TITLE
SD: add prometheus metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2156]
Sciond should export prometheus metrics. This is especially useful when it's running on an infrastructure node.

Potential metrics:
- client requests by type (path, iainfo, revnotify, etc)
- path requests by ISD (and possibly by IA)
- total request latency (from request to response)
- sent requests by type (pathreq, certreq)
- PS/CS response latency
- timeouts/errors

**Comment by lukedirtwalker** [comment]
I wonder if we actually should report latencies in metrics or whether that should be done through tracing.

**Comment by lukedirtwalker** [comment]
Most important metrics are covered by #3247 if we need more, we should create a new issue.
