### ISSUE TITLE
SIG: Defaults for config values should be public and not internal to the sig.

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2158]
`sig/internal/sigconfig/conf.go` contains various default values in the const block. Those are not visible outside the sig. But they should be certain code outside of it might want to make use of them.

**Comment by Oncilla** [comment]
This has moved in the meantime: https://github.com/scionproto/scion/blob/72b2b49a072babeff6b076c3816beeb6e4e55a51/go/pkg/sig/config/config.go#L28-L33
