### ISSUE TITLE
Add a `Go` suffix to all functions than can be called as a go routine

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#2165]
* Anything that could be called as a go routine must have a `Go` suffix in the name
* All functions/methods that end in `Go` must have `defer log.LogPanicAndExit()` at the top
* All `go` calls in the code must be either calling something directly that ends in `Go`, or wrapping it in a `func()` with the log defer

**Comment by sustrik** [comment]
Should we also discourage calling Go* functions in synchronous manner? If we do we would have one more special case to worry about - especially with respect to (not) propagating the panic upstack.

**Comment by shitz** [comment]
Yes, that makes sense.

**Comment by kormat** [comment]
Slight modification, i'd suggest `_Go` as the suffix, because we're going to have functions that look like `StopGo` otherwise, and the underscore should hint that the suffix is a suffix, and not part of the name.

**Comment by kormat** [comment]
This will find _most_ occurrances (including all closures...):
```
git grep -P '^\s+\bgo\b \b\S+(?!_Go)\(' -- '*.go' 
```
