### ISSUE TITLE
AS Master key derivations should use salt value with a random part

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#2168]
As suggested in rfc2898 section 4.1, the salt value should contain at least 8B of random data.

**Comment by matzf** [comment]
I can't really see how this would work. Would we store the randomly generated salt along the master key (the "password")? It's not clear to me how this would help at all. After all, in our setup, the "hashed password" is not any more likely to be compromised than the "password" itself, nor does it make any difference which one is compromised.

A simpler option seems to be to assume that the master key has been generated as a sensible random key and not treat it as a password. If users want/need to set this based on a password, they can still run a PBKDF manually when setting up the master secret.

**Comment by matzf** [comment]
@sgmonroy, what do you think about this now, 4 years later?

**Comment by matzf** [comment]
Closing, will be reconsidered as part of a design for forwarding key roll over.
