### ISSUE TITLE
Make startup of all elements more useful and consistent

### ISSUE THREAD

**Issue by klausman** [scionproto/scion#2169]
All elements (BS/PS/CS/DS/SIG/dispatcher/SCIONd, possibly more) should log one distinct line on startup, for example:

`====================> Starting PathServer ps1-2-3`

After this (or on the same line), these things should also be logged:

- Commit ID the binary was built from
- Build date
- Version number, if available
- Build chain version(s) (Compiler versions for gcc and Go)
- Whether the process is dockerized (examine `/proc/self/cgroups` for that)
- uid/gid the process is running as
- unparsed command line as seen by the process

The clean exit lines should be similarly distinctive (same leader as the start line).

**Comment by lukedirtwalker** [comment]
Helpful links:
https://socketloop.com/tutorials/golang-add-build-version-and-other-information-in-executables
https://blog.alexellis.io/inject-build-time-vars-golang/

**Comment by lukedirtwalker** [comment]
We have common startup messages for all go services since #2177. Most services are now go and the rest will be replaced soon, therefore this issue can be closed.
