### ISSUE TITLE
Better segment verification error

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#2175]
```
 Segment verification failed debug_id=de2e701f segment="86f4d9984c01 2018-11-27 15:11:02.000000+0000 2-ff00:0:210 450>503 2-ff00:0:220 502>3 1-ff00:0:120 6>1 1-ff00:0:110 2>1004 1-ff00:0:130" err="Invalid signature"
```
Isn't a very useful error. There should be more info about why the signature verification failed.

**Comment by kormat** [comment]
More specifically:
- _Which_ signature failed?
- What was the `proto.Sign` of the failed signature?
- And what does "Invalid" _mean_?
