### ISSUE TITLE
pktdisp: detect dispatcher disconnect, and export error metrics instead of logging

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2204]
Currently `go/lib/pktdisp` will produce an infinte amount of logging if the connection to the dispatcher dies. It will also happily log so many errors that it is unable to read from the dispatcher quickly enough, causing the dispatcher to kill the socket. These 2 factors combined is worse than the sum of their parts.

**Comment by worxli** [comment]
Related to #2181

**Comment by kormat** [comment]
Partially addressed by #2207

**Comment by scrye** [comment]
Error part moved to https://github.com/Anapaya/scion/issues/1127.

Reconnecting logic in the rest of the SIG is covered by https://github.com/scionproto/scion/issues/1896.

Closing this since we can use the finer grained issues instead.
