### ISSUE TITLE
SIG: support egress session restarting

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2205]
Currently if there's a socket error for a session (e.g. #2204), the only possible action is to kill the SIG, and let it be restarted. This could be greatly improved by only killing the _session_, and having the SIG itself restart that.

**Comment by sustrik** [comment]
Ingress dispatcher will also need restarting.

**Comment by scrye** [comment]
With #3932, all gateway connections now support dispatcher restarts. If this degrades performance too much, we should investigate having the data-plane socket stop attempting reconnects (or perhaps stop supporting dispatcher restarts).
