### ISSUE TITLE
Add tagged metadata to hop entries in beacons

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2219]
With the current internet, reverse dns entries are used a lot to provide some location information about hops. With scion right now all we get are interface IDs, so e.g. we can't tell what geographical area of an AS you might be traversing. The proposal is to add (_optional_) tagged metadata to hop entries in beacons, to allow an AS to expose some amount of information to receivers of the beacon.

**Comment by scrye** [comment]
Fixed by https://anapaya-scion.readthedocs-hosted.com/en/latest/BeaconExtensions.html.
