### ISSUE TITLE
PS: Offload chain verification to CS

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2228]
Once we have application level acks we could offload the chain verification to the CS. When the PS receives a segments and it doesn't have the chain to verify it, it should:
1. Fetch the chain from the senders AS CS
2. Send the chain to the local CS, which verifies it and ACKs only if it could be verified and stored.
3. With the ACK from the CS the PS can use the Chain without verification.

**Comment by scrye** [comment]
No longer going to fix this because we're going with the monolithic Control Service approach.
