### ISSUE TITLE
Add authentication mechanism for messages between Infra elements

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2230]
Certain infra messages between infra elements (br, bs, cs, ps) should be authenticated.
E.g. This is a hard requirement for #2228 to be secure.

The messages can be authenticated using symmetric crypto.
The shared key could be derived from the master secret that is already available on infra elements.

- [ ] Compile list of messages to authenticate
- [ ] Define Key derivation
- [ ] Define authenticator
- [ ] Define where the message is authenticated and where authenticity is verified

**Comment by scrye** [comment]
All intra-AS traffic is not an aspect of the SCION protocol; we should be using TLS instead.

**Comment by scrye** [comment]
Additionally, the monolithic Control Service no longer does network RPCs between bs/cs/ps, so we don't need authentication there any more.

**Comment by scrye** [comment]
Created https://github.com/scionproto/scion/issues/3636 as a more recent proposal for authentication mechanisms (TCP would allow us to easily run TLS on top).

Closing this, since it is outdated by now.
