### ISSUE TITLE
env.LogCleanup is broken

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2242]
calling `log.LogPanicAndExit` indirectly doesn't work. `recover` only works if the direct caller is called from defer.

Solution: Remove the function.

**Comment by Oncilla** [comment]
All apps should call 
1. `defer env.LogAppStopped(...)`
2. `defer log.LogPanicAndExit()`
in that order.

Bonus:
log `"=====================> Panic"` in `log.LogPanicAndExit()`
