### ISSUE TITLE
Revisit the applicability of OverlayAddr

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2259]
Under the hood, overlay addresses are currently a composition of interfaces:

```
func NewOverlayAddr(l3 addr.HostAddr, l4 addr.L4Info) (*OverlayAddr, error)
```

If the layer 3 and layer 4 headers are a valid combination, the object is constructed. Otherwise, an error is returned.

The two important methods to get back the interfaces are:
```
func (a *OverlayAddr) L3() addr.HostAddr
func (a *OverlayAddr) L4() addr.L4Info
```

The intention is for applications to be agnostic about the overlay they are running on. However, in practice `OverlayAddr` does not make this possible, and sometimes makes for awkward code.

Some disadvantages
===============

1. Applications still need to construct a specific type of overlay socket. Once the type of the socket is chosen, applications construct the `OverlayAddr` from a `HostAddr` and `L4Info` that they themselves initialize. Since they know the concrete implementations of the `HostAddr` and `L4Info`, they could just use them directly.

2. APIs/libraries taking `OverlayAddr` that need to do overlay related operations need to check for all valid combinations. This is done by extracting layers 3 and 4 with methods `L3()` and `L4()` and checking whether their combination is a supported combination (e.g., a library that can only construct UDP/IP packets cannot accept an IP-only overlay). Because `L3()` and `L4()` return interfaces, the check needs to go into the concrete objects behind those interfaces. This amounts to a lot of checks (see 3. below).

3. Related to the point before, checking that an overlay address is supported must always be done by checking the concrete layer 3 and layer 4 types against all supported implementations:
```
if overlayAddr.L3().Type() == Foo || overlayAddr.L3().Type() == Bar {
  // overlay code
}
```
This is done to protect libraries against future overlay implementations, which might add new unsupported layer 3's or 4's. But since all the types are explicitly checked, this makes the code aware of the implementation again.

4. Method `L3()` returns interface `addr.HostAddr`. However, not all implementations of `addr.HostAddr` are valid. For example, `addr.HostSVC` is not a valid L3 for a combination. While the constructor of `OverlayAddr` protects against it, programmers need to always remember that the returned object can never be an invalid implementation of `addr.HostAddr`. While in the immediate call to `L3()` this is somewhat feasible, imagine if the result is stored in some other object, that gets passed in a different library. The library only sees `addr.HostAddr`, and needs to check against all invalid implementations again. This leads to more lines of code, more branching, and more testing.

5. Some overlays don't have an L4. Because method `L4()` can always return nil, every access needs to perform additional checking do defend against panics. The checks work against the flexibility the type aims to promote, because it exposes an implementation aspect of the interface (the fact that it is constructed without an L4), to a caller that shouldn't care about this aspect.

6. UDP/IP is the only overlay we need at the moment. While IP only could be used in the somewhat near future, nothing is stopping us from having an IP overlay address and an UDP/IP overlay address. Callers will need to understand what addresses they're constructing anyway (e.g., from an address string in the config file).

7. The need for precise conversion from `OverlayAddr` to concrete implementations can also be seen from `OverlayAddr`'s API. Methods like `ToUDPAddr()` that return `nil` for every invalid internal combination of layer 3 and layer 4, and return a `*net.UDPAddr` for IP/UDP overlays, are basically a way for callers to say extract the concrete overlay they support, without going through all the checking. This works fine right now because we only support one combination, but as the number of overlays grows many more methods like this would appear.

Possible solution
============

A possible way to simplify this is to manager overlay addresses similarly to how the standard library `net` package manages addresses. The address interface is very lightweight, and gives very limited information about the internal type:
```
type Addr interface {
        Network() string // name of the network (for example, "tcp", "udp")
        String() string  // string form of address (for example, "192.0.2.1:25", "[2001:db8::1]:80")
}
```

This means that every data type that wants to use the address, must type assert to the implementation immediately. This works great for stuff like `net.UDPConn` and `net.TCPConn`, because they support a single address concrete type, and it can possibly work just as great for overlays.

For us, this would amount to having (maybe) an UDP/IP overlay connection type (`net.UDPConn`, basically) with UDP/IP overlay addresses (`net.UDPAddr`), and in the future we can add an IP overlay connection type (`net.IPConn`) with IP overlay addresses (`net.IPAddr`). Using the concrete types as soon as possible means libraries need to do less checking, and will be more robust. Whenever we want to pass an address around in higher-level logic, we can use `net.Addr`.

Thoughts?

**Comment by sustrik** [comment]
Are we expecting to ever support mixed-overlay-type deployments? If not so, we can hardwire the overlay type at compile time.

**Comment by scrye** [comment]
`OverlayAddr` was removed by https://github.com/scionproto/scion/pull/3381 and https://github.com/scionproto/scion/pull/3552.
