### ISSUE TITLE
BR: behavior of deactivated interface without revocation

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#2295]
From the border router point of view, it is currently valid to receive an IFStateInfo message to deactivate an interface without a revocation.

The result is the interfaces shows as deactivated in the log, it also deactivated in the border router internal state, yet it forwards packets because there is no revocation associated with it.

Shouldn't a revocation be required to deactivate an interface with an IFStateInfo message?

**Comment by scrye** [comment]
The `IFStateInfo` RPC will be reworked for #3743. We don't know if it will even still exist, but at a minimum it will no longer contain a revocation.

@sgmonroy: We can probably close this?

**Comment by sgmonroy** [comment]
Agreed,
