### ISSUE TITLE
Unintuitive -maxpaths argument behavior in showpaths tool

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2313]
Argument `-maxpaths` seems to not be enforced when using `showpaths`.

For example, when running:
```
bin/showpaths -srcIA "1-ff00:0:110" -dstIA "1-ff00:0:120" -sciondFromIA -maxpaths 1 -local "1-ff00:0:110,[127.0.0.1]:40001"
```

I expect to see at most one path, but I get:
```
Available paths to 1-ff00:0:120
[ 0] Hops: [1-ff00:0:110 1>6 1-ff00:0:120] Mtu: 1472
[ 1] Hops: [1-ff00:0:110 2>1004 1-ff00:0:130 1005>1 1-ff00:0:120] Mtu: 1472
[ 2] Hops: [1-ff00:0:110 3>453 2-ff00:0:210 450>503 2-ff00:0:220 502>3 1-ff00:0:120] Mtu: 1280
[ 3] Hops: [1-ff00:0:110 3>453 2-ff00:0:210 450>503 2-ff00:0:220 501>2 1-ff00:0:120] Mtu: 1280
```

The above happens even when probing is enabled via `-p`. The behavior is ambiguous in this case, because it is not clear if `-maxpaths` means _at most maxpaths working paths_ will be displayed or at most _maxpaths_ will be displayed (even if they all timeout, for example).

Also, there is no way to specify _all paths_ right now. The default is `10`, and there is no way to specify _all_.

**Comment by matzf** [comment]
This has been fixed in the meantime. The `--maxpaths` / `-m` option is applied correctly. Specifiying a value `0` shows all paths.

The relation to the probing seems clear enough now that probing is enabled by default -- it will probe all paths that are displayed.
