### ISSUE TITLE
Consider renaming IFID Packets

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2328]
The name `IFID` is used to refer to both the numerical identifiers of interfaces, and also the interface health monitoring packets exchanged between beacon servers. Giving the two concepts separate names would reduce confusion.

A possible alternative could be IF Keepalives, or something along those lines.

**Comment by shitz** [comment]
Yes, that is something that has been bothering me for a while. I like IF Keepalives.

**Comment by kormat** [comment]
Bear in mind that IFID packets _do_ contain an IFID, which is a critical part of beaconing.

**Comment by scrye** [comment]
This is not actionable, so closing as invalid.

Additionally, new documentation usually refers to these packets as keepalives already, and with them being localized to between BRs for #3743, there should be much less confusion.
