### ISSUE TITLE
Add metrics to common library code

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#2329]
- [ ] Config reload (infraenv) 
- [ ] Topology version
- [x] Messenger latency, total calls (#2380)
- [ ] Packet bytes recv/send(Messenger -> infra dispatcher)
- [ ] snet bytes sent/received
- [x] Truststore (#2362)
- [x] PathDB (#2358)

**Comment by kormat** [comment]
Messenger doesn't have access to packet bytes, but it could at least keep track of messages sent/received by type.

**Comment by lukedirtwalker** [comment]
This is issue has been superseded by multiple issues labeled `monitoring`.
