### ISSUE TITLE
Consider removal of the ISD field in an Info Field in the forwarding Path.

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#2344]
It is unclear the value and usefulness of the ISD field in an Info Field given that currently there is no code using it actively.

What is the meaning and possible value of this field in core segments that go through multiple ISDs?
Are there any scenarios where this information could be leveraged?

Getting rid of this field would free 2 bytes in the already populated Info Field struct.

**Comment by scrye** [comment]
Replaced by #3714.
