### ISSUE TITLE
Function scmp.PldFromRaw does not detect truncated quotes

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2353]
If the buffer holds less data than what the lengths in the Meta field suggest, the buffers silently get truncated because `bytes.(*Buffer).Next()` just returns less data than requested.

This also means that if the length of the last quote extends past the end of the packet, the event is not detected.

Simple program to illustrate the issue:
```
package main

import (
    "fmt"

    "github.com/scionproto/scion/go/lib/common"
    "github.com/scionproto/scion/go/lib/scmp"
)

func main() {

    b := []byte{
        0, 0, 0, 0, 0, 0xff, byte(common.L4UDP), 0, // suggest L4 is 255 * 8 bytes long
        1, 2, 3, 4, 5, 6, 7, 8, // dummy L4 start
    }
    pld, err := scmp.PldFromRaw(b, scmp.ClassType{Class: scmp.C_Routing, Type: scmp.T_R_UnreachHost})
    fmt.Printf("pld = %#v, err = %v\n", pld, err) // no error
}
```

**Comment by Oncilla** [comment]
scmp package no longer exists
