### ISSUE TITLE
pathpol: Implement ! and & operators for path policy sequences

### ISSUE THREAD

**Issue by sustrik** [scionproto/scion#2356]
These operators are missing. In theory these could be implemented using regexp lookaheads, however, lookaheads are not implemented in golang regexp package. The reason is that there are not trivially, if at all, implementable using simple FSMs. For more context look here: https://github.com/golang/go/issues/18868#issuecomment-426361008

That being said, it's not entirely clear whether the operators are needed. Some use cases can be implemented using ACLs. There's also stuff that's not doable, but it's rather obscure, e.g. "go through ISD 64 on the second hop but not through AS 64-42; at the same time we don't want to blacklist AS 64-42 in this policy".

**Comment by jiceatscion** [comment]
This has not seen any activity other than labeling since being filed. The description implies that the feature might not even be helpful. So, I think it's a case of YAGNI. Please reopen if you have a clear use case.
