### ISSUE TITLE
Remove SCIOND API mock

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2377]
Now that most of the code base uses `gomock`, we no longer need hard-coded mocks. The existing mocking code in sciond should be refactored.

**Comment by scrye** [comment]
To be more specific, the mock in question is in `go/lib/sciond/mock.go`.

**Comment by Oncilla** [comment]
For mocking, we use the `github.com/golang/mock/gomock` framework.

Mock files are generated using `make mocks`. To add mocked interfaces, `tools/gomocks` must be updated.

**Comment by scrye** [comment]
Fixed by https://github.com/scionproto/scion/pull/3014.
