### ISSUE TITLE
Investigate addressing for Docker BR Dispatcher

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2382]
In the docker test topology, the control planes of Border Routers run on top of a BR-only dispatcher (that is a different instance from the main AS dispatcher). The address of this BR-only dispatcher is arbitrarily selected in `python/topology/docker.py` from the set of all Control Socket addresses from that AS. This means that certain BRs might be unreachable via their control plane socket.

This should be fixed, although I don't know what the best solution is.

**Comment by worxli** [comment]
It seems we cannot assign multiple IPs from the same subnet to a container. Therefore the solution would be to add a dispatcher per BR.

**Comment by scrye** [comment]
In the end, the current solution hasn't led to any reachability problems in the last year, so closing this.
