### ISSUE TITLE
Respect Border Router's multicast/anycast choice in Dispatcher delivery of SVC packets

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2393]
In SCION multicasts and anycasts are resolved at the edge of the AS. The border router detects that the packet is towards an SVC destination, checks the topology state, and then chooses a destination host address for the packet. The destination is specified in the destination address field of the overlay header.

The C SCION Dispatcher uses the overlay destination address in the packet to determine which address to forward the packet to. E.g., if the overlay destination address is `10.0.0.1`, then it will look for SCION applications listening on `10.0.0.1` on the SVC address contained in the SCION header. Then, the dispatcher multicasts/anycasts to the ports on that IP, depending on the type of SVC address.

The Go Dispatcher currently does not extract the Overlay Destination IP Address, and therefore does not implement the same multicast/anycast logic as the C dispatcher. This is sufficient for most scenarios, but to make the Go implementation fully replace the C implementation, the feature should also be implemented.

**Comment by kormat** [comment]
Reasons to do this:
- If an operator happens to run two instances of the same service on the different IPs on the same machine, they will receive duplicate MSvc messages as the BR can't tell they are on one machine, so it will send one copy per IP. While this is a corner case, this could be a very unexpected gotcha, and could break application logic.
- If a service instance is running on a machine which has a publicly routable IP address, then messages can be sent to that service even if the operator deliberately binds it to a non-routeable IP. (An example would be scionlab ASes in the cloud).

**Comment by scrye** [comment]
With the current design choice of fully decoupling underlay addresses from SCION addresses (see https://github.com/scionproto/scion/issues/2779), dispatchers should no longer use the underlay address to compute SCION addresses. Therefore, the new BR semantics for multicast/anycast choice extend to the underlay IP, and it is the responsibility of the internal SCION control-plane infra to decide where to forward the multicast/anycast.

Operators that want to restrict the addresses to which services bind should look into running multiple dispatchers on the same host (e.g., a dispatcher for non-routable IPs and a dispatcher for routable IPs), and have applications connect to the proper dispatcher.
