### ISSUE TITLE
pathdb: sqlite backend does not always reset the transaction on errors 

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2408]
For example in `insertFull` we `return err` without rolling back the transaction.
We should check for all returns after a transaction was started and make sure that they either commit or rollback the transaction. 
Optimally we should make sure that this will not happen in the future. For example by creating a deferable function that cleans up the transaction.

**Comment by matzf** [comment]
Appears to be fixed by #2521.
