### ISSUE TITLE
toml: fix casing in config files

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2412]
According to the [spec](https://github.com/toml-lang/toml#spec) toml is case sensitive.
While the go lib currently also matches case insensitive (https://godoc.org/github.com/BurntSushi/toml#hdr-Key_mapping) we should not rely on this.

**Comment by Oncilla** [comment]
What style should we go for?
```
[logging]
  [logging.file]
    Level = "debug"
```
vs
```
[Logging]
  [Logging.File]
    Level = "debug"
```

**Comment by scrye** [comment]
We should go for snake_case, so it's similar to our JSON files.
