### ISSUE TITLE
Sciond: Use services with fewer errors

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2434]
As an example, take path lookup. Sciond should keep track of successes/failures when querying PS instances, so if one instance is unhealthy sciond prefers to add a health instance instead.

**Comment by Oncilla** [comment]
I think the scope of this issue can be extended. The pool concept does not
only apply for path servers, but all servers in general. For example, the
trust store selects the certificate service based on the topology and should
also do something similar. 

The pool could also be used to keep track of remote core ASes that are better
at responding for certain queries.

To this end, we introduce package `lib/healthpool` that keeps track of the health 
of given entries. At the top level, there is a general implementation of a pool
that only keeps track of keys and their health status. The sub-packages create 
a shim layer between that base implementation and information that client
packages actually care about. (e.g. `lib/healthpool/svcinstace` will keep track
of the health for scion service instances)

The health status of service instances should be global to the process on 
infrastructure nodes. We create package `lib/infra/module/isvcinstances` that 
provides a singleton for choosing healthy instances based on the service type.
`isvcinstaces` is notified about topology changes through the callbacks in itopo.

## Choosing service instances

In a first phase, the `healthpool` uses a simple choosing algorithm based on
the minimal fail count.

However, choosing the service with the minimal count can lead to heavy load on
singular services. To distribute the load, we will move to a probabilistic approach
that chooses the server with a probability that considers the fail count.


## Healthpool

### Code structure

````
  go/lib/
  ├── healthpool
  │   ├── common.go   # pool interface definition
  │   ├── pool.go     # internal implementation
  │   ├── info.go     # internal implementation
  │   └── svcinstace
  |       ├── pool.go
  │       └── info.go # info for service instances
````

### `go/lib/healthpool/common.go`

Here the interfaces of the health pool are defined.

````
type InfoKey string

type Info interface {
    fmt.Stringer
    Key() InfoKey
    FailCount() int
    Fail()
    ExpireFails()
}

type Pool interface {
    // Update updates the pool based on the new info.
    // The pool adds all infos that are not in the pool.
    // The pool deletes all entries that are not in infos.
    // However, if Options.AllowEmpty is not set, and the 
    // Update causes an empty pool, the entries are not 
    // removed and an error is returned.
    Update(infos map[InfoKey]Info) error
    // Choose chooses info based on fail count.
    Choose() (Info, error)
    // Keys returns a list of all keys in the pool.
    Keys() []InfoKey
    // Close closes the pool and stops the periodic fail expiration.
    // After the pool is closed, it can no longer be updated.
    Close()
}

type Options struct {
    // AllowEmpty indicates that the pool is allowed to be empty.
    AllowEmpty bool
}
````

### `go/lib/healthpool/pool.go`

Here the pool is implemented. We expose only the function `NewPool`.
The implementation is private.

````
var _ Pool = (*pool)(nil)

func NewPool(infos map[InfoKey]Info, opt Options) (*pool, error)
````


### `go/lib/healthpool/info.go`

Here the info is implemented. We expose only the function `NewInfo`. The implementation is private.

````
var _ Info = (*info)(nil)

func NewInfo(key InfoKey) (*info)
````

#### `go/lib/healthpool/svcinstace/pool.go`

This file contains a shim that uses the healthpool as the underlying 
pool for info selection. It keeps track of actual service info.

````
type Info struct {
    mu sync.RWMutex
    info healthpool.Info
    addr *addr.AppAddr
}

func (i *Info) Fail()
func (i *Info) Update(a *addr.Appaddr)
func (i *Info) Addr() *addr.Appaddr

type Pool struct {
    mu sync.RWMutex
    pool healthpool.Pool
    infos map[healthpool.InfoKey]Info
}

func NewPool(infos topology.IDAddrMap, opt healthpool.Options) (*Pool, error)
func (p *Pool) Update(info topology.IDAddrMap) error
func (p *Pool) Choose() (Info, error)
func (p *Pool) Close()

````

**Comment by Oncilla** [comment]
Interesting article we could use to select the info efficiently: https://web.archive.org/web/20190130110026/http://www.keithschwarz.com/darts-dice-coins/

**Comment by scrye** [comment]
Closing this, gRPC's default server selection strategy works for now.
