### ISSUE TITLE
acceptance: Add common function to setup env if it isn't setup

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2440]
Currently `lib.sh` does the setup of `ACCEPTANCE_ARTIFACTS` but this is only accessible if the test is run using `acceptance/run` not if the functions are called individually.

To solve this we should have:
* For each test an env file that is created when the test starts.
* A common command that creates the env file if it doesn't exist and creates the `ACCEPTANCE_ARTIFACTS` dir and adds it to the env file.
* A command to delete the existing env file (for setup).

**Comment by scrye** [comment]
We're deprecating `lib.sh` in favor of the Python acceptance libraries. Is this something we still want to fix?

**Comment by lukedirtwalker** [comment]
No we don't need a fix for this. Calling `acceptance/ctrl grun ...` is also a workaround for this.
