### ISSUE TITLE
BK: Ubuntu Base Image

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#2443]
At the moment we're using buildkite/elastic-ci-stack-for-aws to spin up machines for BK jobs. Unfortunately this is restricted to RHEL based images. When we have `bazel` we have hermetic builds out of the box and won't need `docker` for this anymore. Thus we could also run tests on the machines instead of in a CI docker image. For this to work we need a Ubuntu 16.04 based base image where the BK agent runs on. 

To begin with we could run x Ubuntu based VMs on AWS. They should be provisioned with packer and have bazel, docker-ce, docker-compose and the buildkite-agent installed. 

In a second step we would re-enable autoscaling, potentially using buildkite/buildkite-agent-scaler. This would run as a Lambda on AWS and scale machines up or down based on the BK API.

**Comment by worxli** [comment]
https://buildkite.com/docs/agent/v3/gcloud

**Comment by Hermain** [comment]
Done in repo https://github.com/Anapaya/elastic-ci-stack-for-aws
Second step done too
