### ISSUE TITLE
Proposal: Add 'cost' to hopentries

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2447]
For an AS which is distributed over a large geographical area, it's not obvious to outsiders which sets of interfaces are close together and which are far apart. For example, say a swiss ISP peers in NYC and LON - traffic being sent from NYC to LON (distance 5570km) might go via switzerland because it just looks like a single hop, even though the traffic goes through Basel, adding up to 6956km.

If each hop entry has a metric to indicate, say, the minimum latency between the two interfaces, that would allow routing to optimise for lowest latency path, and avoid obvious inefficiencies like above.

**Comment by scrye** [comment]
Paths now have access to additional tuning via the static information extension (see [here](https://scion.docs.anapaya.net/en/latest/BeaconExtensions.html)), so this is now supported. Closing.
