### ISSUE TITLE
Proposal: re-thinking hop fields

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2466]
Issues with the data-plane path currently:
1. IFIDs are allowed to be up to 64bit in size, which is likely huge overkill.
1. The design for variable length is very unwieldy - having to have a flag field on every line is ugly, and makes it hard to work with; lots of bit shifting is needed to merge fields which have been split. Also allowing for hop fields that are >16B is probably overkill, too.
1. Hop fields aren't self-contained - you can't parse one without metadata that's only present in the ctrl-plane PathSegment, as that specifies how many bits the ifid fields are.

Here's the current format of hop fields:
https://github.com/scionproto/scion/blob/12cff7efd24bca8be8ae6437f5f1c7f0f224741b/go/lib/spath/hop.go#L44-L57
Not visible (and not implemented yet) is a Continue bit to allow for variable-length hop fields.

Proposal:
- Change max ifid size to 32-bit, which is _way_ more than should ever be needed.
- Make hop fields either 8 or 16B long, with a bit in the hop flag field to indicate which.
- Reserve the last _bit_ of the MAC to mirror the hop length flag bit, to allow browsing backwards through a data-plane segment. This bit is masked out of MAC calculations.
- Allow 4 different sizes of ifids: 1/2/3/4B, and use 2 bits in the hop field flags to indicate the size. This makes parsing a hop field self-contained.
- Shrink the "default" ifid size in an 8B hop field to 8b, with a 31-bit MAC. This is plenty for smaller and leaf ASes.

An AS with max-sized IFIDs would have a 16B hop field, with 47b of MAC.

Here's what the format would look like:

```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|L IFL V X r r r|    ExpTime    | ConsIngress...  ConsEgress... |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                               |
.                                                               .
.                                                               .
|                      MAC...                                 |L|
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

L(1b): hop-field length. 0 == 8B, 1 == 16B
IFL(2b): ifid length. 0 = 1B, 1 = 2B, 2 = 3B, 3 = 4B
V(1b): Verify-only flag
X(1b): cross-over flag
r: reserved
```

Based on discussion with @sgmonroy and @sustrik.

**Comment by sustrik** [comment]
Some random comments:

1. In info there's "Hops" field which doesn't sounds suboptimal. Specifically. Specifically, if the router wants to check whether it's end of the current segment, it has to return to the beginning of the segment and count hops until it gets to the current hop. We probably want an offset of the next segment instead of hop count.

2. Assuming 1,2,3,4-byte long IFIDs, 4-byte MAC and alignment to 8-byte boundaries, we would waste this much space per-hop:
  a.) For ASes with 1-byte IFIDs: 0 bytes
  b.) For ASes with 2-byte IFIDs: 6 bytes
  c.) For ASes with 3-byte IFIDs: 4 bytes
  d.) For ASes with 4-byte IFIDs: 2 bytes
What's troubling is that the IFID size most commonly found on a path would be, presumably either 2 or 3 bytes which result the most wasted space.

**Comment by sustrik** [comment]
On the pros side, one advantage that wasn't mentioned is that with dynamically sized IFID field there's no need for wide-scale and potentially disruptive changes once the 257th interface is added to the AS.

Also, traffic going through the first 256 interfaces can still use 1 byte IFIDs.

**Comment by kormat** [comment]
Yes, the `Hops` field is a misnomer. It's actually "segment length".

The wasted space calculation depends heavily on the assumption that 4B MAC is the correct size for all ASes, but i don't know enough to evaluate the claim either way.

**Comment by scrye** [comment]
This is now covered by #3714. Closing this as a duplicate.
