### ISSUE TITLE
Proposal: Common and Address headers field changes

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#2468]
Issues:
- 8 Byte alignment. This results in more wasted space (padding) than desired for no obvious reason. Most of the current CPUs have small performance for unaligned accesses. Even so, considering that SCION is currently deployed as an overlay on top of IP/UDP,  it already means that SCION is unaligned at an 8B boundary when the underlay is IPv4/UDP (28 Bytes).
- No Address length, which requires all BRs to support all Address Types (more details below).
- Total length includes the header length, should check that header_len < total_len
- CurrINF is absolute offset, should check that CurrINF > common_hdr_len + address_hdr_len.
- CurrHF is absolute offset, should check that CurrINF < CurrHF.

The main issue with the current approach of parsing the address header is that for any given Address Type, all Border Routers in the path must support it or it will fail to parse.

Even if it were to ignore the address type when forwarding packets (ie. not destined to the local AS), it will fail to create SCMP packet errors given that it cannot properly parse the address header.

This also affects how to add support for a new address type in an existing SCION network, requiring that all BRs in a given path need to support the new address type.

This was mentioned by \<REF-PLACEHOLDER\>.

Following is the current SCION common and address format:
```
                     1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|Version|  DstType  |  SrcType  |           TotalLen            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|     HdrLen    |    CurrINF    |     CurrHF    |    NextHdr    |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
+                           DstISDAS                            +
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
+                           SrcISDAS                            +
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                          SrcHostAddr                          |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
+                                                               +
|                                                               |
+                          DstHostAddr                          +
|                                                               |
+                                                               +
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           Padding                             |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
Proposed changes:
- 4 Bytes alignment.
- Split the address type field (6 bits) into type and length, such as 4 bits type and 2 bits length, or 3 bits type and 3 bits length.
- TotalLen would be change to TotalPayload, like in IPv6.
- CurrINF starts after common_hdr_len + address_hdr_len.
- CurrHF is relative to CurrINF.

Following would be the format assuming 3 bits for address len:
```
                     1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|Version|Dtype|Dlen |Stype|Slen |           TotalLen            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
Possible encoding based on bits used for address type and length:
- 4 bits type and 2 bits length: 4/8/16/20 Bytes (TBD).
- 3 bits type, 3 bits length: 4/8/12/16/20/24/28/32 Bytes (4 Byte increment starting at 4B length).

With the 4 Byte alignment and address type lengths multiple of 4, there would be no need for padding in the address header. The exception would address types that do not match exactly with the supported sizes. Taking the SVC address (2 Bytes) as an example, its length would be 4B, where the 2 LSBs are set two 0:
```
                     1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|          SvcHostAddr          |            Zero               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
Based on discussions with @shitz, @kormat, @sustrik, @scrye .

**Comment by scrye** [comment]
This is now covered by #3714.
