### ISSUE TITLE
Proposal: redesign core beaconing

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2469]
The current system of beaconing in the core scales very badly. The fundamental problem is the BSes who decide what to propagate don't have any information about what their neighbours need. To put it another way, only a given AS knows what beacons it has/wants, and there's no way for it to influence what beacons it gets.

This causes a lot of duplicate effort (propagating beacons that aren't wanted by neighbours), and availability problems (you're completely at the mercy of the rest of the network when it comes to having multiple paths to reach remote cores).

The way to fix this is (conceptually) simple: move from a push model to a pull model. It would work something like pub/sub:
- A core AS can query its neighbours to see what segments it has available
- It can also register a policy (or policies) of segments its interested in with its neighbours.
- If the neighbours cannot satisfy the policies from the segments they already have, they can also reach out to _their_ neighbours, and so on.

This way an AS can, for example:
- opt not to receive many segments that all traverse a single-point-of-failure AS
- request greater path diversity to reach important remote ASes
etc.

**Comment by sustrik** [comment]
I would try to fix the problem without requiring AS operators doing manual work first. If that doesn't work, then sure, let's add manual policies.

One improvement that comes to mind:

1. Timestamp the beacons.
2. When a beacon arrives in AS, forward it to neighbouring ASes, but only iff we haven't got that particular (or newer) beacon via that link already. (Whether we did can be inferred from the DB of available paths.)

That would prevent multiple traversal of the same vertex and thus effectively trasform the graph of core ASes into a a spanning tree.

**Comment by sustrik** [comment]
I would prefer if the problem could be solved without manual intervention of the AS operators.

Let's have a look at the existing spanning tree protocol practice & research.

**Comment by matzf** [comment]
This is a vast topic and various approaches have been proposed. Since this issue has last been discussed, the re-implementation of the beacon service (now integrated in the monolithic control service) in golang has alleviated the most pressing scalability issues by "just" being a much more efficient implementation of the same push-based beaconing model.

Closing this for now, but feel free to open a new discussion.
