### ISSUE TITLE
Go code should log the source of error packets

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2470]
As an example:

https://github.com/scionproto/scion/blob/12cff7efd24bca8be8ae6437f5f1c7f0f224741b/go/lib/snet/reader.go#L148

This logs the contents of the revocation, but not the sender, so it's not possible to determine what AS it applies to.

Further up in the same file:
https://github.com/scionproto/scion/blob/12cff7efd24bca8be8ae6437f5f1c7f0f224741b/go/lib/snet/reader.go#L119-L120

**Comment by scrye** [comment]
To make this actionable, for this issue only the errors in `snet.reader.go` should be touched (if logging the source address makes sense for them). At a minimum, the address should be logged in the two places mentioned in the original comment.

(Of course, logging the source address is valid advice that also concerns errors created in other files).

**Comment by scrye** [comment]
Closing due to age. We'll fix bad error messages one by one as we find issues.
