### ISSUE TITLE
Dispatcher should ensure overlay and scion addresses match for incoming packets

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2476]
This is a more general form of #2393.

The dispatcher must honour (and enforce) that the destination address in the scion header matches the destination overlay address. This is how a normal network stack works (and also how multi-ip webserver configurations work, where the server binds to :80, but dispatches based on destination IP), and it prevents packets from being accidentally or _maliciously_ sent to an application that has not registered to receive them.

For non-svc addresses, this means the overlay destination address must match the scion destination address. For SVC, it means that the overlay destination address must match the IP that the service registered on.

**Comment by kormat** [comment]
Clarifying a bit:
- If an app has only a public address, then the overlay destination address must match the scion destination address.
- If an app has a public+bind address, then the overlay destination address must match either (though potentially we could think about reducing that to it must match the bind address).
- If the destination scion address is SVC, then the overlay address must match either the public or bind addresses.

An example:
- An AS is running on a cloud machine (e.g. AWS). It has a public IP that is NATed to the private IP that is configured on the machine.
- There is a BR running on the machine, with public address == public IP, and bind address == private IP.
- There is a BS running on the machine, using only the private IP.
- Without the proposed restrictions, a packet sent with the public IP as the overlay address, and the private IP as the scion destination address, can be delivered to the BS, despite the fact that it deliberately did not register for the public IP.

**Comment by scrye** [comment]
Currently, the Dispatcher works as a proxy so the SCION IP address and underlay IP address do not need to match. This means SCION applications can make no assumptions about what physical interfaces they are listening on, and they should expect data from all physical interfaces.

This might change in the future, especially if we go in the direction of removing dispatchers altogether.
