### ISSUE TITLE
Dispatcher should support wildcard addresses

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2477]
This would greatly improve the usability of tools like `scmp` and `showpaths --probe`, because they can get the local IA from sciond, and don't need to care about the local IP, because the dispatcher would pick it for them for outgoing traffic.

**Comment by kormat** [comment]
To make this work, the dispatcher needs to know what IPs are configured on the local machine (which can change). For machines being NAT, this is a bit tricky - the dispatcher should also know what public IPs map to the bind addresses.

**Comment by scrye** [comment]
This is no longer needed now that tooling can infer the local address.
