### ISSUE TITLE
Don't use fixed ports for unit tests

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2523]
As an example:
https://github.com/scionproto/scion/blob/b3ffb868bfb5cdee339b0a5ccd59a7387520ea3d/go/lib/infra/rpc/rpc_test.go#L77
This fails on my machine, because there is something running on 60002 (`mosh-server`) currently.

It's fairly easy to just use dynamic ports instead, which removes this potential race-condition.

**Comment by scrye** [comment]
I don't think we have that many ports left in unit tests.

For this issue, the occurrence mentioned in the original comment should be fixed (and others, if they are in the same package).

If other packages have similar unit tests, we can fix them on a case-by-case basis.

**Comment by scrye** [comment]
All new tests (and most existing ones) now use virtualized environments, so this is no longer needed.
