### ISSUE TITLE
Revocation might break beaconing process

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2534]
## Scenario
Given the following topology as an example:
```
   ( A )     A:   Core AS
     |       B-F: Non-Core AS
   ( B )     x:   revoked link
     x       |:   Parent link
   ( C )
     |
   ( D )
   /   \
( E ) ( F )
````
When the link between `B` and `C` gets revoked, beacons are no longer propagated.
Even tough there is connectivity on a network level between `C-F` this might result in the ASes not being able to reach each other.

## Beaconing Issue
In the current implementation, beacon servers evict all beacons that contain revoked interfaces.
Since beacons are only originated at core AS `A`, no beacons are propagated from `C` towards `D` for as long as the revocation is valid.

This implies, for as long as the revocation is active, `C-F` only have stale paths available. Depending on the duration of the revocation and the expiration time of these stale segments, `C-F` might loose connectivity due to no paths being available.

## Path Construction Issue
In the protocol specification, a path server drops all paths that contain a revocation.
Also, path construction by the non-core ASes is done by fetching Up- and Down-segments at the core. In our example, when `E` wants to communicate with `F` it will have all paths evicted from the DB and have to request new ones from core. However, the core is not reachable due to the revocation.
(see: #1660)

 
### Path Construction Issue
1. Do not always evict revoked paths. It might even be okay to keep all revoked paths in the DB.
2. Under some circumstances, allow responding paths with revocation.
3. Instead of always going to the core it might be useful to fetch down-paths from intermediate ASes. (e.g. `E` will have discovered the ISD topology after some time, so it might as well request paths  from `D` if the connection to `A` is broken)

### Beaconing Issue
When an AS loses all connectivity on all links to the upstream ASes, it starts to originate its own beacons. Downstream ASes only propagate this beacon if they do not have any core beacon available.

In our example, the PS in `E` would the request the Down-segment for `C`. However, this requires approximate knowledge of the graph and state of the links.

**Comment by scrye** [comment]
> In the protocol specification, a path server drops all paths that contain a revocation.

#3743 will change revocations, and they will no longer be present in the control-plane. This means the path server (now, part of the Control Service) will no longer know about them, and will no longer do filtering. The effect is that all path segments will be kept in the DB, and paths that might be down will be disseminated by the Control Service.

To tolerate links being down negatively impacting beaconing, non-leaf ASes should deploy more links. This will usually be the case anyway, because critical ASes will want host-level redundancy anyway.

@Oncilla: Due to #3743, I'm thinking we can now close this. What do you think?

**Comment by Oncilla** [comment]
Yes, restricting the revocations to data-plane only will make this issue obsolete.
