### ISSUE TITLE
squic: connections never closed

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#2539]
Since v0.8.0, quic-go will not call `Close` on the underlying connection when a client/session is closed. At least for connection objects passed into `quic.Dial`, this appears to be intentional*.

For squic this means that any call to `squic.DialSCION` etc will leak the scion connection.

There does not appear to be any way to retrieve the connection object from the `quic.Session`, so callers of `squic.DialSCION` currently have no way to manually cleanup either.

---

<sup>[*]</sup> Currently, the vendored version is quic-go v0.8.0.
In v0.8.0, quic-go never seems to close any client connections.
In v0.9.0 the [PR 1467](https://github.com/lucas-clemente/quic-go/pull/1467) was merged, so that connections are again closed, but only when `DialAddr` is used. This appears to be the behavior in the latest versions also.

**Comment by chaehni** [comment]
Not closing the underlying `net.PacketConn` is intended by quic-go. The QUIC session never owns the connection and therefore doesn't close it. Execpt for `DialAddr` where the connection is established specifically for that sesscion. 
See: https://github.com/lucas-clemente/quic-go/issues/1622
Package `squic` should expose the `PacketConn` or provide a function to close the connection.
