### ISSUE TITLE
cs: Heuristic to avoid unnecessary verification of beacons

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#2575]
As requested [here](https://github.com/scionproto/scion/issues/2560#issuecomment-479401261) we should think about having a heuristic to avoid unnecessary verification.

This feature should be toggleable, and turned off by default

**Comment by matzf** [comment]
As this was issue was opened based on my own request, I'm taking the liberty to close this as no longer necessary -- at least as far as SCIONLab is concerned, the beacon service re-implementation in golang has proven to be so much more efficient than its older python incarnation that such optimisations do not seem necessary at the moment.
