### ISSUE TITLE
Bazel: modified licenses.tar file after running acceptance test

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#2576]
When running acceptance tests on Master, the following files are modified:
docker/perapp/licenses.tar

Current Master commit hash:
commit 9a8e66faff8f05a45a26dcec47391875b55d009b

**Comment by worxli** [comment]
More precisely the file is modified when running `make -C docker/perapp`.

**Comment by kormat** [comment]
This problem still exists, reopening.

**Comment by kormat** [comment]
From an off-line discussion with @sustrik:
- Python packages from `pip` come with their own licenses.
- Apt packages put their licesnses into /usr/share/doc/<pkgname>, and `docker/perapp/files/copy_package` already handles this

So the remaining thing we need to care about is licenses from go libraries we depend on.

Proposed fix:
- Add a go_deps target to the top-level `Makefile`. It should run `tools/fetch.sh` if `WORKSPACE` has changed, and generate a BUILD.bzl file containing a target that depends on all go dependencies.
- Convert  `docker/perapp/licenses.tar` into a bazel target, that depends on the target generated by `tools/fetch.sh`
- Have all docker image targets depend on `licenses.tar`

**Comment by scrye** [comment]
Licensing changed in #3692, closing this as it should now be fixed.
