### ISSUE TITLE
Refactor trust store tests to use mocks instead of full objects

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2611]
Some trust store tests in `go/lib/infra/modules/trust/trust_test.go` use entire `Messenger` objects on top of fake point to point connections built on pipes. These connection do not propagate address information correctly, which makes stricter address checking in the messenger break the tests. The goroutines needed to run multiple messengers also make the tests difficult to debug.

Now that we have mocking support, the tests should be refactored to run in a single goroutine, with the trust store running on top of only mocked objects.

**Comment by Oncilla** [comment]
Supported in new trust store
