### ISSUE TITLE
lint: Add dead (go) code detector

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2630]
Sometime we have unused private variables or private methods/functions that are not called. We should have a tool that finds such code and fails the build if it exists.

Note that for public code it might make sense to be unused during the development phase (e.g. create new module, add main later).

staticcheck would support this (https://staticcheck.io/docs/checks#U1000)

**Comment by matzf** [comment]
`golangci-lint` includes various dead code detectors that are enabled in our configuration `deadcode`, `structcheck`, `unused`, `varcheck`.
What we're still missing is a check for exported but unused functions in "private" packages.

**Comment by jiceatscion** [comment]
It seems the latest incarnation of the "unused" linter has an option to not give a pass for unused exported symbols:
"exported-is-used: false"
If we can turn that on for private packages we should be good. No?
