### ISSUE TITLE
Deprecate support for RPC calls over pure UDP

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2677]
Pure UDP has a number of issues (unreliable, packet size limits, request-response matching) which make it unwieldy to use directly for SCION control plane RPC.

Currently the control-plane supports QUIC and is backwards compatible with UDP, but once every RPC call gets ported to QUIC we should look at deprecating backwards compatibility for UDP.

**Comment by Oncilla** [comment]
With switch to gRPC this is solved.
Only RPC calls that are pure UDP will not be ported and removed when switching completely to header v2.
