### ISSUE TITLE
Infra: Interface removal might create a temporary black hole

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2688]
When removing an interface from the topology, the beacon server will stop creating revocations for the interface. Already cached paths might be used afterwards, leading to SCMP BadIF error.

We should investigate how the infrastructure copes with this error.
Sciond should avoid handing out paths that contain a bad interface.

The beacon and path server should stop serving paths that contain a removed local interface.

**Comment by Oncilla** [comment]
related #1881

**Comment by kormat** [comment]
This is mostly an ops issue. An operator should not remove an interface until all paths that use it have expired. The expected procedure would be:

1. set interface down on the BR (note: we don't actually have a way to do this, yet)
1. wait until all paths that use that interface have expired
1. remove interface from topology file

**Comment by scrye** [comment]
#3743 implies SCION applications should recover from traffic black-holes. Closing this, because #3743 already covers this.
