### ISSUE TITLE
Topology generator generates invalid address: 10.10.10.0 is not a host address in a /24

### ISSUE THREAD

**Issue by AnotherKamila** [scionproto/scion#2708]
When running
```
./scion.sh topology -c topology/Tiny.topo -n 10.10.10.0/24
```
the generated `topology.json` file contains 10.10.10.0 for the `PublicOverlay` field for `br1-ff00_0_110-1`. This is incorrect, as that address is the network address and host addresses should start with .1 .

It also happens with other .topo files.

Tested with commit 9f416c7 (latest on `master` as of today).

**Comment by Oncilla** [comment]
Hi Kamila

When running `./scion.sh topology -n 10.10.10.0/24`, the `10.10.10.0` appears in a point-to-point connection between two border routers i.e. in a `10.10.10.0/31`.
As far as I know, `10.10.10.0` is a valid host IP in the `/31` subnet:

````
$ ipcalc 10.10.10.0/31

Address:   10.10.10.0           00001010.00001010.00001010.0000000 0
Netmask:   255.255.255.254 = 31 11111111.11111111.11111111.1111111 0
Wildcard:  0.0.0.1              00000000.00000000.00000000.0000000 1
=>
Network:   10.10.10.0/31        00001010.00001010.00001010.0000000 0
HostMin:   10.10.10.0           00001010.00001010.00001010.0000000 0
HostMax:   10.10.10.1           00001010.00001010.00001010.0000000 1
Hosts/Net: 2                     Class A, Private Internet, PtP Link RFC 3021
````

**Comment by AnotherKamila** [comment]
Hi,

Yes, for a /31 it is valid, my apologies. I didn't realise that. Closing this, sorry.
