### ISSUE TITLE
CI: Investigate packet loss

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2733]
Sometimes, packets are lost on CI.

This causes the end2end tests to fail: (see https://buildkite.com/scionproto/scionproto-nightly/builds/251#a0b26d37-3d15-422c-9ac6-39209a937efa)
The server receives the ping requests, and logs the pong. However, the client never sees the pong.

This also causes the scmp tests to fail. The message from the border router is lost, and causes the client to time out. (see https://buildkite.com/scionproto/scionproto-nightly/builds/249#3927bc96-bdf6-4859-a7d2-132a74b39a1a)

We need to investigate what the causes of this is.
For now, there are two possible explanations:
1) Bug somewhere in the dispatcher that "looses" the packet, or forwards it to the wrong port.
2) Packet is lost in the queues in the network stack. In the supervisor environment, all infra elements and clients run on the same dispatcher.

**Comment by scrye** [comment]
Investigated this issue with @Oncilla.

Some test builds with increased parallelism:
  - https://buildkite.com/scionproto/scionproto/builds/3059
  - https://buildkite.com/scionproto/scionproto/builds/3054
  - https://buildkite.com/scionproto/scionproto/builds/3052

We added packet traces to the dispatcher in https://github.com/scionproto/scion/pull/2739, logging all packets with debugging extension before they are written to the network and whenever they enter from the network.

The failing test in https://buildkite.com/scionproto/scionproto/builds/3059 shows a packet leaving the dispatcher:
```
2019-06-04 08:20:27.341829+0000 [DBUG] [TRACE] Recv'd packet with debug extension dir=egress debug_id="[68 208 28 164 251]" pkt="&{DstIA:1-ff00:0:111 SrcIA:1-ff00:0:112 DstHost:127.0.0.84 SrcHost:127.0.0.99 Path:0xc00bca8ae0 HBHExt:[] E2EExt:[E2EDebug] L4:SPort=1142 DPort=1071 TotalLen=25 Checksum=8913 Pld:70696e673a312d666630303a303a313131}" overlay_addr=127.0.0.98:31012
```
but that packet never reaches goes back into the dispatcher, so the e2e server also never sees it. This suggests that packets are not dropped by the dispatcher, but rather by the CI network.

So, we can probably discount:
> Bug somewhere in the dispatcher that "looses" the packet, or forwards it to the wrong port.

We should investigate how to determine how many packets/which packets are dropped by the network stack.

**Comment by kormat** [comment]
https://github.com/scionproto/scion/issues/2760 seems likely to be relevant.

**Comment by scrye** [comment]
Looks like increasing the dispatcher read buffer size in #2770 fixed this, so it was indeed the network that was causing the issues.
