### ISSUE TITLE
Move flag from lib/overlay/conn to applications that need it

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2773]
Main libraries should be flexible and not cause unavoidable side effects in applications.

We should move the package level `sizeIgnore` flag out of `go/lib/overlay/conn` and into the BR, and make the package functions take the **ignore size** behavior as an argument (or config field, or any other flexible solution).

**Comment by Oncilla** [comment]
Package has moved to go/lib/underlay

**Comment by matzf** [comment]
The `sizeIgnore` flag has been removed in #4020 (cc33b6ecc62448b2c3a2484bde56844a57048b58).
