### ISSUE TITLE
PS: SegSyncer does not consider TRC updates

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2794]
The PS initially fetches all core ASes to sync segments to:
https://github.com/scionproto/scion/blob/a26115989020a9d9343624b18e9b5d9e72d9752d/go/path_srv/internal/segsyncer/segsyncer.go#L55

This does not consider that the core AS set might change through TRC updates.

This should be address by the CP-PKI rewrite.

**Comment by lukedirtwalker** [comment]
Note that we want to eventually replace this with a pull model. So the change might not be needed.

**Comment by scrye** [comment]
The segment sync mechanism is going away, replaced by #3731.
