### ISSUE TITLE
buildkite ignores failures in `command` steps

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2799]
This command _always_ fails, and has done for the last 4 months, but buildkite ignores it: https://github.com/scionproto/scion/blob/master/.buildkite/steps/setup.yml#L4

@worxli is investigating if a newer version of the buildkite agent fixes this issue.

**Comment by worxli** [comment]
https://github.com/buildkite/agent/issues/1037

**Comment by lox** [comment]
Apologies folks! We'll see if we can figure out what is going on.

**Comment by worxli** [comment]
Closing because this is actually valid bash behavior. The affected command was removed because it wasn't needed anymore.
