### ISSUE TITLE
sciond API: add path policy support to path requests

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2816]
sciond path requests should have a path policy field that sciond considers.

**Comment by scrye** [comment]
We should probably close this due to age/lack of context. This will come up again eventually, but we can create a new issue then.

@lukedirtwalker: what do you think?

**Comment by lukedirtwalker** [comment]
Yeah this is old and not clearly specified. So let's close and create a new issue once we have the details specified.
