### ISSUE TITLE
BR: SCMP Revocations

### ISSUE THREAD

**Issue by sgmonroy** [scionproto/scion#2837]
Currently the BR will fork revocations depending on below conditions:
[border/rpkt/process.go#L161](https://github.com/scionproto/scion/blob/18106324cf65e01e719b30839a366e3d6e35723c/go/border/rpkt/process.go#L161)
```
// processSCMPRevocation handles SCMP revocations.
// There are 3 cases where the router does more than just forward an SCMP revocation message.
// 1. The revocation was received on a core interface, and the destination is in this ISD. In this
//    case the revocation is forked, and forwarded to the local BS and PS services. This prevents
//    the BS from propagating/registering revoked core PCBs. The destination check ensures that this
//    is only done for revocations which impact the local ISD.
// 2. The revocation was received from a parent AS, and the revoked interface is in the same ISD.
//    In this case the revocation is also forked to the local BS and PS services. This ensures that
//    ASes downstream of a revoked interface get informed quickly.
// 3. The revocation's destination is the local AS. The revocation notification is forked to the
//    local PS, to ensure that it stops providing segments with revoked interfaces to clients.
```

The purpose of revocation forking seems to be to react faster to network updates (ie. revoked interfaces) at the expense of expensive BR logic, given that the BR should implement revocation filtering to avoid trivial Denial of Service (DOS) [scionproto/scion#1867]

*** To Be Updated regarding benefits vs cost ***

**Comment by scrye** [comment]
#3743 means revocations forking is no longer a thing.

@sgmonroy: Can this be closed?

**Comment by sgmonroy** [comment]
Indeed.
