### ISSUE TITLE
py: switch to pipenv

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2843]
Currently we use plain `pip` to manage the python dependencies for scion. This comes with certain problems:
- it will install the packages 'globally' by default
- upgrading a given package is not a safe operation (it can break other packages that depend on it, because pip doesn't do real dependency resolution)
- it's not possible to separate out run-time dependencies from dev dependencies.
- we're forced to pin versions for packages we don't care about

https://realpython.com/pipenv-guide/ has a good overview of how pipenv (the recommended env management system by the python project) solves these issues fairly elegantly.

Note: 
- We currently use pip2 as well, to handle supervisor. But the good news is that supervisor supports python3 as of the 4.0 release. So we should update to that version, and drop python2 completely.

**Comment by lukedirtwalker** [comment]
The more bazelified we have everything the less this applies. Eventually we can have many requirements files for separate targets. Through bazel stuff is essentially virtualized.

We also already switched to pip3.
