### ISSUE TITLE
sciond: Add "refresh2" flag for path requests

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2871]
The current refresh flag flushes all segments which contain any local interface and then fetches fresh segments. If the lookup to the PS failed we don't have paths that go out. This is unfortunate for example for monitoring.

A Better refresh would be to do the query towards the PS with a special flag indicating that it should send local revocations that were issued since sciond last checked. This way we also see local revocations, fresh paths, and we don't have to flush anything from the pathdb. If that works for all cases we should replace the old refresh flag with this behavior.

**Comment by scrye** [comment]
We should investigate if it's possible to have this behave as a simple "fresh-segment-request-proxy" flag, where it tells SCIOND it is mandatory to wait for new segments before attempting to reply to the application's request.
