### ISSUE TITLE
deduper: Try to make debug_id aware.

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2876]
Since the deduper creates a separate context the `debug_id` of the log is not passed on. We should make sure that we can still correlate the outside context within the deduper.

Proposal:
* the first request uses the same debug_id as its outside context.
* all deduped requests log a message `Waiting on deduped reply debug_id=...., dedupe_debug_id=...`

**Comment by Oncilla** [comment]
deduper is no longer used
