### ISSUE TITLE
CI: builds on master fails if the author isn't registered on buildkite

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2877]
https://buildkite.com/scionproto/scionproto/builds/3515#0d07e8ac-0a8f-4ef0-93ba-03b3afa8db7b

> 422 Builds cannot be triggered from this pipeline as there is no Buildkite user linked to this build. Ensure that a user has added "<< redacted >>@users.noreply.github.com" as a verified email address on their account. (Attempt 1/60 Retrying in 5s)

**Comment by Hermain** [comment]
Created issue with buildkite: https://github.com/buildkite/agent/issues/1050

**Comment by kormat** [comment]
This happened again with #3164

**Comment by Hermain** [comment]
Issue solved. Buildkite turned off verification of user for all builds.
