### ISSUE TITLE
Bootstrap TLS trust from AS Certificates

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#2882]
TLS certificates are required for HTTPS and QUIC communication.

For servers/clients who are willing to trust their AS to vouch for their identity (which is the case of most control-plane speakers), a simple way to establish TLS trust is to embed trusted (root) TLS certificates in the AS certificate. Trust then flows in the following way:
  TAA -> TRC -> AS Certificate -> TLS Certificate

Embedding the TLS certificate in the AS certificate is not the most efficient solution, but it simplifies dissemination: SCION nodes that have a path to a remote node must already have the AS certificate for the remote AS, and can thus build the trust store for the TLS connection immediately.

We should look into whether the embedding is secure enough for our needs (for example, if Hidden Paths servers can use this solution to provide authentication and confidentiality), and if secure, we should implement TLS certificate embedding support (maybe as an AS certificate extension).

**Comment by maurozenoni** [comment]
Hi @scrye,

In my Master Thesis, I have explored the problem further and designed a concrete solution for it based on this idea of bootstrapping TLS trust from AS Certificates. The security of the resulting protocol has been formally verified by leveraging the Tamarin prover.

Check it out: [Thesis PDF](https://ethz.ch/content/dam/ethz/special-interest/infk/inst-infsec/information-security-group-dam/research/software/ma-20-zenoni-scion-hps.pdf).

If you have any questions, feel free to contact me.

**Comment by rsasse** [comment]
Hi @scrye and other interested parties,

It would be great for Mauro and myself to hear whether and how his thesis can possibly help you. If you are currently busy with other things, just drop us a line when you can.

**Comment by scrye** [comment]
Hi @maurozenoni, Hi @rsasse,

Thanks a lot for the help, and sorry for taking so long to respond. Between deadlines and the Corona situation, things have been pretty hectic these past few weeks. Also due to this, we haven't had the time to work on the Hidden Paths authentication system, but we expect to start tackling it again soon.

Thanks for sharing the document with us. We'll take a look and get back to you, but again, due to our packed schedule it might take some time to go through it.

Note that recently we also reworked our cryptography from JSON to X.509. You can find a lot of information about these on our new documentation site:
- [New TRC format specification](https://scion.docs.anapaya.net/en/latest/cryptography/trc.html)
- [New Certificate format specification](https://scion.docs.anapaya.net/en/latest/cryptography/certificates.html)

You can find all the information on our [new main cryptography page](https://scion.docs.anapaya.net/en/latest/cryptography/index.html), including guidelines on how to work with the crypto. Our end-goal with this change was to make it easier to reason about the security of the system, and also easier to work with existing X.509 tooling. This also means that the AS certificate _is_ the TLS certificate in this new approach.

While there are a lot of changes, nothing fundamental changed in how trust flows and most of the proof should still apply, but we'll need to take a close look.

Also, if you have time to look into the new specifications, it would be of great help for us if you could send us feedback regarding the write-up.

**Comment by matzf** [comment]
I believe this has all been implemented in the long time since this issue was written.
The control service uses the AS certificate for TLS connections, both for client and server certificates. For most RPCs, the TLS certificate is never checked (`InsecureSkipVerify`); the messages themselves (e.g. ASEntry in PCBs) are authenticated and a secure channel is not needed. At least some RPCs related to the CPPKI must remain unauthenticated, as this would otherwise introduce a cyclical dependency.
Currently only the RPCs related to DRKey rely on a secure channel and consequently do explicitly check the certificates.
