### ISSUE TITLE
Distribution mechanism for ISD hints

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2886]
In case of a multi-ISD AS, it might be useful to issue ISD hints (a list of ISDs that the AS claims to be part of)
We should evaluate the use cases for these ISD hints and decide on a distribution format.

@kormat proposed to attach this information to the CP-PKI certificates.

**Comment by kormat** [comment]
In general to support mutli-ISD ASes, we need a way to answer questions such as:
- What other ISDs is this IA in? E.g. you're looking for disjoint paths to a given destination.
- What ISDs is this AS in? E.g. you have an AS id, how do you find out anything about them? (Note this is a superset of the first question).

Including the ISD hints in the AS cert would solve the first one, but nothing else.

For the second, i think we need https://github.com/scionproto/scion/issues/1486, plus to have each core CS get the list of all ASes in every other ISD periodically. That way you can query your core for a list of ISDs for a given AS.

**Comment by scrye** [comment]
We haven't encountered a situation/use case where we needed the list of ISDs an AS is in yet.

We'll revisit this when we need it.
