### ISSUE TITLE
HP: Implement GroupId -> Registry config lookup

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2887]
For the hidden path server we need a module that looks up Registries for a list of GroupIds.
Input: List of GroupIds, List of config files, localIA
Output: map[GroupIds]->Registry (more or less addr.IA)

The lookup should return an optimal mapping of GroupIds to Registries.
Where optimal means:
* Whenever the local IA is a Registry for the GroupId it should be the local IA.
* For all other GroupIds a minimal amount of Registries should be returned.

This is HPS internal functionality and should be under `hidden_path_srv/internal`.

**Comment by chaehni** [comment]
This sounds like a variant of the `set cover` problem which is NP-complete. It is often solved with a polynomial-time greedy algorithm which approximates an optimal solution.
Another thought: Would it make sense to map from Registry to a set of GroupIds instead (i.e. map[Registry] -> []GroupIds)? Then we could directly pack the `hp_seg_request` for every Registry.

**Comment by lukedirtwalker** [comment]
I guess we can relax the `minimal amount` requirement. In the end we just need something that takes a list of GroupIDs as input and produces a set of registries where we need to send requests as output. So your proposal makes sense.
