### ISSUE TITLE
msgr: Verification policy

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#2916]
When the messenger has a verifier set, it tries to verify every payload.
However, infra currently does not sign all messages.

We should allow to set policies in the messenger what payloads must be signed.

related: #2230

**Comment by kormat** [comment]
This causes error like this:
```
2019-07-26 08:37:56.254175+0000 [EROR] Verification error debug_id=e9aa634f from="1-ff00:0:130,[10.10.0.5]:30254 (UDP)" err=
>  Sanity check failed pld="Ctrl: Union: ACK ok"
>      SignedPld is missing signature type="none"
```

**Comment by Oncilla** [comment]
The messenger can be configured with a verifier per message type.
