### ISSUE TITLE
CS: corepusher log individual errors

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2920]
Log the errors for pushing to each core. Otherwise in the log we only see a line
`2019-07-26 08:37:56.289754+0000 [EROR] [reiss.CorePusher] Failed to sync all cores debug_id=a262f5f1 err="Sync error checkErrors="[1-ff00:0:110 1-ff00:0:120 1-ff00:0:130]" remainingCores="[]""`
which is no indicative of the actual problems.

**Comment by scrye** [comment]
With the X.509 rework, I think this no longer applies.

@lukedirtwalker: What do you think, should we close it?

**Comment by lukedirtwalker** [comment]
Corepusher no longer exists, so closing this.
