### ISSUE TITLE
JSON Format: Use snake_case

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#2923]
There is no naming convention for JSON keys, but many propose using camelCase i.e. [Google](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format).

So let's use a somewhat standard format.

**Comment by Oncilla** [comment]
This needs changes to: 
- [ ] new cert/TRC format
- [ ] topology format

**Comment by kormat** [comment]
[citation needed]
This is quite a lot of work, and a big breaking change.

**Comment by worxli** [comment]
Yes. But imo it's better to be explicit on the data format and use something _more_ standard for it.

**Comment by kormat** [comment]
After a lot of discussion:
- I'm in favour of using standardised naming for json/toml/yaml etc fields.
- I propose `snake_case`, as it's widely used in unix configs (e.g. nginx, sudo, exim, postfix), and is similar to what netops are probably used to (cisco uses `linked-case`)

**Comment by worxli** [comment]
```
To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match. By default, object keys which don’t have a corresponding struct field are ignored (see Decoder.DisallowUnknownFields for an alternative).
```

^ means only changing the case doesn't break the format for JSONs. Moving to snake_case will also introduce underscores, so this is breaking nevertheless.
