### ISSUE TITLE
BS/BR: Reduce interface state to Active/Revoked

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2926]
In the BS we have 4 states: `Inactive`, `Active`, `Expired`, `Revoked`.
In the BR we have 3 statues: `Inactive`, `Active`, `Revoked`

It is not clear for what an inactive state would ever be needed so we should just drop it.
In general it is enough to have a revocation field. If there is a revocation the state is revoked otherwise we assume the state to be active.

Note that this also means that resetting interface state in the BS, will put all interfaces in the active state.

We should also drop the active field from the `if_state` message.

**Comment by lukedirtwalker** [comment]
As of https://github.com/scionproto/scion/pull/3572 the BS only has active and revoked states.

**Comment by Oncilla** [comment]
The keepalive mechanism is deprecated and will be gone with the new header design.
