### ISSUE TITLE
CI: increase buffers for BR and disp

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#2938]
By default both the border router and the go dispatcher will try to increase the buffer sizes of their kernel sockets, but will only log a warning if it fails. This means they will run with far smaller buffers than desired. To fix this:

- sysctl net.core.rmem_max=1048576
- sysctl net.core.wmem_max=1048576
- add `-overlay.conn.sizeIgnore=false` to the cmdline flags of the BR + go disp

**Comment by scrye** [comment]
This is no longer needed because CI seems to handle the network with the smaller buffers.
