### ISSUE TITLE
Allow parsing packet with invalid L4 checksum

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#2955]
The `hpkt.ParseScnPkt` function parses a scion packet, including the L4 payload. In the process, it verifies the L4 checksum and returns an error if it's not correct.

There should be a way to parse a packet without verifying the L4 checksum.

**Comment by matzf** [comment]
As the checksum validation is the very last step in the parse function, the result is already available even if the checksum failed. Therefore, we can check whether the resulting error-string contains `"Checksum failed"`, as a (rather appalling) workaround.

**Comment by kormat** [comment]
More generally, we should expose apis to apps so that they can choose exactly how much they want to parse, and whether they want to do validation themselves or not.

**Comment by oncilla** [comment]
This has been addressed with the header rework
