### ISSUE TITLE
Migrate db tests away from goconvey

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#2986]
path, trust, and beacon db should no longer use goconvey. With it the output from CI is not detailed enough to properly analyze why a test failed.

We generally want to migrate away from goconvey, to standard go tests with assert libs.

**Comment by scrye** [comment]
As I understand it, there's only `go/lib/revcache/revcachetest` and `go/lib/infra/modules/trust/trustdb/trusdbtest` left.

**Comment by matzf** [comment]
None of the _db_ tests use goconvey anymore. Keeping the more generic issue #3016 open seems sufficient to keep track of removing the remaining occurrences.
