### ISSUE TITLE
test: Get rid of goconvey

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#3016]
Goconvey is slightly painful to work with. Also, upstream seems very inactive.

The vanilla golang sub-tests provide the functionality we need already.

**Comment by matzf** [comment]
The following packages still use `goconvey`:
- `dispatcher/internal/registration` (~400 LoC)
- `pkg/sock/reliable/reconnect` (~550 LoC)
- `private/revcache` (~550 LoC)
