### ISSUE TITLE
Merge pathdb and revcache

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3024]
I think the reason revcache and pathdb is separate because it was assumed that we could use revcache in the BS. But it turned out that we didn't use it. So we could also just merge pathdb and revcache and profit from the single source of truth. This would simplify stuff, for example don't build paths with revocations -> don't load revoked segs from the DB etc.

**Comment by scrye** [comment]
Revocation cache is getting deleted for #3743, so this merge is no longer planned.
