### ISSUE TITLE
BR: Send error makes posix output hang

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3050]
When the BR fails to send packets for some reason, and the error is not tagged as `temporary` or `recoverable`, the posix output routine will drain the ring until it is closed.
see: https://github.com/scionproto/scion/blob/a178cff4a11dd4e5db70dcaff6c5afd18ca0c279/go/border/io.go#L270

However, the ring will only be closed if the socket is shutdown, and not in the error case.

The proposed solution is to fatal out in case of a non-recoverable/non-temporary error and classify errors as they pop-up.
This is reasonable, because the BR will be in a broken state when the go routine is busy emptying the ring.

**Comment by kormat** [comment]
An example of an error that should be ignored is:
```
[EROR] Error sending packet(s) src=[169.254.0.13]:30042 err="write udp 169.254.0.13:30042: sendmmsg: operation not permitted"
```
In this case it was caused by temporarily adding an iptables rule.
