### ISSUE TITLE
messenger: Revocations are not mapped back to an API call.

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3052]
If a server needs to RPC to another server and uses the messenger API it has no way to differentiate the remote not replying in time vs having used a revoked path.

Example: non-core PS requests segments from core PS via `msger.GetSegs(ctx,...)`, if the path used to reach the core PS contains a link that is down, the messenger call will just time out.

Expected behavior: The messenger stack detects the revocation and returns the messenger call immediately with an error.

**Comment by scrye** [comment]
This is mostly tricky on the server side, because the revocations come on the listening UDP socket which is common for all ongoing RPC handlers.

Clients should open dynamic ports, one per RPC, making it easy to error out the RPC when the data-plane revocation is received.

**Comment by scrye** [comment]
The SCION RPC mechanism needs to be able to tolerate traffic getting silently dropped by intermediate nodes (see #3743). A data-plane revocation (also defined in #3743) would allow a control-plane RPC speaker to quickly switch, but this is only an optimization. Infrastructure should work correctly given a total absence of revocations.

I think we should close this with a Won't Fix. @lukedirtwalker: what do you think?

**Comment by lukedirtwalker** [comment]
@scrye yeah agreed, feel free to close.
