### ISSUE TITLE
QUIC Control plane server cannot react to revocations

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3093]
Not only revocations, but SCMP in general.

The QUIC library operates on top of a `net.PacketConn`, whose implementation consists of a SCION UDP socket. SCMP packets must be either managed by the `PacketConn` or returned as an error (which the QUIC library will discard as transient).

If a server has multiple handlers running at the same time (often the case), it also becomes impossible (actually not impossible, an address trick can be used here) to trace back from revocation to handler whose traffic triggered it. This means the server will eventually time out, instead of attempting to switch path.

We should:
  - have servers react/adapt to SCMP messages quicker (e.g., change paths transparently);
  - if the server cannot adapt, have a mechanism to notify a handler that an unrecoverable error is affecting the stream;

**Comment by scrye** [comment]
A server being unable to reply to a client will cause the Client's RPC to fail. The client will just retry at that point.

The probability of this occurring is also very small, so it's not worth optimizing for it.

@lukedirtwalker: I'm thinking we can close this. What do you think?

**Comment by lukedirtwalker** [comment]
@scrye yeah agreed, feel free to close.
