### ISSUE TITLE
BR: improve metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3100]
- Revocations forked by receiving interface metric
- SCMP ~echos~/traceroutes/recordpaths
- Basically anything that can cause the router to drop a packet, to return an scmp error, or to log an error. E.g.:
  - Parse errors
  - Validation errors
  - Processing errors
  - Routing errors
- Ctrl plane metrics. E.g.:
  - Dispatcher errors/reconnections - depends on either #3183 or #3185
  - Packets in/out
  - Parse errors
  - Unsupported payloads
  - ifstateinfo payloads received
  - ifstatereq payloads sent
  - revinfo parse errors

**Comment by scrye** [comment]
Renamed similarly to other issues.

**Comment by sgmonroy** [comment]
- SCMP echos - From the BR point of view, they are just like any other packet. Only traceroute and recordpath are HBH. SCMP echo metric should be kept by the dispatcher.
- Ctrl plane metrics. E.g.:
   -  Dispatcher errors/reconnections - AFAIK there is no way to see the reconnections when they happen from the BR/app.
