### ISSUE TITLE
BS: improve metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3104]
- IFIDs sent/received by interface - done in #3151 
- Revocations issued/received - done in #3167 
- ~SCMP errors received.~ Replaced by #3107, for now. Eventually it would be nice to know what actions got an scmp error reply.
- Beacons received by update (i.e. it already exists in the path store) vs new. - done in #3186 
- ~Beacons propagated by interface~ - already existed
- ~Revocation cleaner metrics~ - these already exist, just not in a namespace i expected.
- Crypto issues:
  - cert/trc request failures: timeouts vs not available
  - Signature verification failed (e.g. possible forgery)
  - Signature validation failed (e.g. signature from expired cert)
- ~Dispatcher errors/reconnects.~ Replaced by #3107
- Implement https://github.com/scionproto/scion/issues/3121 for all periodic tasks

**Comment by Oncilla** [comment]
re: Beacons propagated by interface:
we have `beacon_propagator_beacons_total` and `beacon_originator_beacons_total`

**Comment by Oncilla** [comment]
Currently, there are multiple individual namespaces.

We should make them as follows:
namespace: `bs`
subsystem: `propagator`, `originator`, `registrar`, `keepalive` `beacon_db`

**Comment by karampok** [comment]
I have implemented `- IFIDs sent/received by interface`  on that PR  https://github.com/scionproto/scion/pull/3151

I will continue on `- Revocations issued/received`
@kormat or @Oncilla  can we clarify how the metrics will look?

On that format
```
# HELP bs_keepalive_receive_msgs_total Total number of received keepalive msgs.
# TYPE bs_keepalive_receive_msgs_total counter
bs_keepalive_receive_msgs_total{ifid="1",result="success"} 118
bs_keepalive_receive_msgs_total{ifid="2",result="success"} 118
```

**Comment by kormat** [comment]
Revocations:
```
# Gauge
bs_ifstate_state{ifid="1", state="1"}
# Counter
bs_ifstate_issued_revocations_total{ifid="1", state="new|renew"}
# Counter
bs_ifstate_revocations_duration_seconds{ifid="1"}
# Counter
bs_ifstate_send_revocations{ifid="4", dst="core|ps|br"}

# Counter
bs_revocations_receive_total{isd="64", result="success|err_expired|err_invalid", method="ctrl|scmp|carrier_pigeon"}
```

**Comment by Oncilla** [comment]
bs_revocations_receive_total{isd="64", result="err_invalid", method="scmp"}
Is just asking for a state exhaustion attack

**Comment by karampok** [comment]
@kormat can we define the exact metrics as we get them when we do `curl <>/metrics` for the next bullet? 

- Beacons received by update (i.e. it already exists in the path store) vs new.

**Comment by kormat** [comment]
```
bs_received_beacons_total{in_ifid="41",neigh_as="X", result="ok_new"} 3
```
Where `result` can be, e.g. `ok_new`, `ok_update`, `err_crypto`, etc.

**Comment by karampok** [comment]
The substem is missing
```
bs_<SUB>_received_beacons_total{in_ifid="41",neigh_as="X", result="ok_new"} 3
```
what about beaconing

**Comment by karampok** [comment]
@kormat  what about the `Revocation cleaner metrics`, how should they look like?

**Comment by karampok** [comment]
@kormat  I am closing this issue, feel free to re-open if there is something missing.
