### ISSUE TITLE
lib/snet: expose metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3107]
- Packets received/sent
- Bytes received/sent
- DialSCION/ListenSCION/Conn.Close() counters.
- Packet parsing errors
- SCMP errors
- Dispatcher errors/reconnects

Ideally this would be done such that an app doesn't have to initialize the metrics if it doesn't care about any of that.

**Comment by scrye** [comment]
Renamed similarly to other existing issues.
