### ISSUE TITLE
lib/sciond: expose metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3109]
- Number of requests by type
- Result (including "empty") by request type
- Connection/reconnection stats

**Comment by scrye** [comment]
The SCIOND client API doesn't have reconnecting logic; it establishes one connection for each RPC.

Also, the client API library never looks within the reply payloads at the moment, so it's a bit strange to look there just to add a metric for empty paths. We should definitely track these events, but it makes more sense to track them at the RPC call site; then we also know which module is failing to find paths.
