### ISSUE TITLE
CS: improve metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3110]
- Implement https://github.com/scionproto/scion/issues/3121 for all periodic tasks
- ~TRC/cert registration result: duplicate, update, new, invalid~
- ~Differentiate between CACHE_ONLY and not for requests.~
- ~Crypto issues:~
  - ~cert/trc request failures: timeouts vs not available~
  - ~Signature verification failed (e.g. possible forgery)~
  - ~Signature validation failed (e.g. signature from expired cert)~

**Comment by Oncilla** [comment]
Most metrics already addressed by #3148

**Comment by karampok** [comment]
This issue can probably close now
