### ISSUE TITLE
lib/periodic task metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3121]
Some of these can be cleanly implemented in lib/periodic, others are tasks-specific.
 
- How long is the period?
- Counters for task start/stop events
- Timestamp for last run
- How long a task took
- Per-task metrics (e.g. num revocations flushed)
- Per-task results (success, db error, ennui)
- For longer-running tasks, maybe a metric to say whether it's currently running or not.

**Comment by karampok** [comment]
Discussion about that issue:
- everything to be implemented within the `lib/periodic`
- metrics should inherit the namespace/subsystem from the task  (e.g `bs_beaconing_x_y`)
- _How long is the period_: this would be one time metrics when we start the periodic job
`<namespace>_<subsystem>_periodic_period_seconds`
- _Counters for task start/stop events_: it will look like that
`<namespace>_<subsystem>_periodic_events_<start|stop|killed>_total`
- _Timestamp for last run_: how that metric should look like?
- _How long a task took_: it will look like that
`<namespace>_<subsystem>_periodic_lastrun_duration_total`
- _Per-task metrics (e.g. num revocations flushed)_: is implemented per task story, nothing in `lib/periodic`
- _Per-task results (success, db error, ennui):_ we could potential change the interface of the `run` function to return a code and have. Nevertheless this might need more refactoring and also we already cover that so we will need to remove code to avoid duplication. Ideas?  I would suggest another issue if we want to do that.
- _For longer-running tasks,  maybe a metric to say whether it's currently running or not._: Do we have any example for that?

**Comment by karampok** [comment]
@kormat,  @lukedirtwalker thoughts?

**Comment by lukedirtwalker** [comment]
@karampok 

> Counters for task start/stop events: it will look like that
`<namespace>_<subsystem>_periodic_event_<start|stop|killed>_total`

Maybe use `start|stop/killed` as label?

> Timestamp for last run: how that metric should look like?

Brian (one of the authors of Prometheus) seems to recommend a Gauge that indicates the unix timestamp in seconds.
https://www.robustperception.io/are-increasing-timestamps-counters-or-gauges

> How long a task took: it will look like that
<namespace>_<subsystem>_periodic_lastrun_duration_total

Shouldn't that be `<namespace>_<subsystem>_periodic_run_duration_seconds_total`

> Per-task results (success, db error, ennui): we could potential change the interface of the run function to return a code and have a logic. Nevertheless this might need more refactoring and also we already cover that so we will need to remove code to avoid duplication. Ideas? I would suggest another issue if we want to do that.

No I wouldn't abstract it. It might be that depending on the task we have to use different label in the result metric.

> For longer-running tasks, maybe a metric to say whether it's currently running or not.: Do we have any example for that?

No sure if we have any. I don't have any task that comes to my mind.
