### ISSUE TITLE
sig_failover test: Reply caching on startup of test topology is problematic

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3125]
sciond and the PS cache replies they got from remote server for a certain amount of time (5min configurable). During the startup of the test topology it might be that no all paths are yet registered. If some paths are taken down, it could be that connectivity is lost.

For example in build https://buildkite.com/scionproto/acceptance/builds/365#96eaca46-463a-49df-99c0-bead1f3cd73c
The path via br2 is initially registered and cached. Then sciond doesn't receive a revocation therefore it never hands out a new path, just the broken cached one.

**Comment by Oncilla** [comment]
This also applies to the path manager.
The path manager does not receive a revocation, thus it will not bother querying sciond for new paths.

**Comment by Oncilla** [comment]
also see https://github.com/scionproto/scion/issues/1390
