### ISSUE TITLE
Use bazel to generate ANTLR files

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3130]
For ANTLR grammars we don't use bazel to generate the files. Instead we have them checked in and manually update them via Makefiles. Instead we should consider patching https://github.com/marcohu/rules_antlr to work with Go targets and use bazel to generate the files.

**Comment by sustrik** [comment]
Isn't this likely to cause the same problem as capn'proto bazel-generated files did? I.e. the stadard go toolchain would not work / be painful to work with.

**Comment by lukedirtwalker** [comment]
Yes it will. But we found workarounds for the former. I'm sure we can also find workarounds for this. Eventually bazel should be able to support working with external tools.

**Comment by lukedirtwalker** [comment]
Note adding
`options { language=Go; }` to grammar files and adding `language="Go"` to the antlr rule already works, i.e. it produces Go files that could be used AFAICT.

**Comment by lukedirtwalker** [comment]
This is now done.
