### ISSUE TITLE
Proposal: Rename "overlay" to "underlay"

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3132]
Due to some suboptimal naming choices in the past (blame that @kormat fellow), scion currently uses the word 'overlay' confusingly. In normal networking terms, scion is an overlay network, and it uses an underlay for transport (currently UDP/IP). Scion currently however refers to the transport as the "overlay".
```
SCION L4   \
--------    => Overlay
SCION L3   /
--------
UDP        \
--------    => Underlay
IP         /
```
To remove the confusion, i propose that we finally fix the naming.

**Comment by scrye** [comment]
This has been changed in quite a lot of places already, and the remaining uses of Overlay will eventually be converted too.
