### ISSUE TITLE
CPPKI: More extensive validation

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3145]
Parsing catches a lot of validation error. 
However, during validation, we should explicitly check this again to catch invalid modifications after parsing.

e.g. Version != 0

**Comment by scrye** [comment]
First we should make a list of what validations need to be implemented.

@Oncilla: What do you have in mind for such a list?

If code for this already exists, please link it here.

**Comment by scrye** [comment]
Since we plan on moving to X.509, validation will be performed by the X.509 library directly, so we don't need to add anything anymore.
