### ISSUE TITLE
SIG: improve metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3153]
- Rename metrics to follow naming conventions: E.g.:
  -  `sig_frames_recv_total` should become `sig_recv_frames_total`, as `frames` is the unit.
  - Ingress and egress metrics should be namespaced. `sig_frames_too_old` is an ingress metric. So: `sig_egress_sent_frames_total` and `sig_ingress_too_old_frames_total`
- go/sig/base/pollhdlr metrics, with remote IA as label.
- sig.json:
  - number of loads
  - timestamp of last load
  - loading errors
- go/sig/disp metrics
- number of AS remotes
- number of ip networks
- egress/dispatcher:
  - counter for failure to find session
- egress/iface:
  - SessPathPool.Get(): "result": `best`, `expiring`, `old`, `none`
  - SessPathPool.Update(): entries added/updated/deleted
- egress/reader:
  - pkts/bytes read
  - TUN errors
  - Parse errors
  - DestIA lookup failures
- egress/session:
  - PktDispatcher metrics (pkts/bytes/errors): #3071
- egress/sessmon:
  - session health
  - pollreqs sent/pollreps received (and any errors in replies), latencies for valid round-trips
  - number of paths available
  - path changes (and reasons)
  - remote sig changes (and reasons)
  - gauge for MTU
- egress/worker:
  - frame sending errors
  - non-full frames sent
  - epoch changes
- ingress
  - read errors
  - cleanups ran
  - workers spawned/shutdown
  - number of currently running workers
  - epoch changes
  - reassembly list capacity/usage.
  - reassembly errors
  - pkt sending errors
  - reassambly

**Comment by scrye** [comment]
With the gateway overhaul (#3932), metrics have been reworked. Closing this as this is no longer up to date.
