### ISSUE TITLE
SD: Bootstrap mode

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3154]
When end hosts want to bootstrap, they need to initialize sciond with the appropriate material.

The sciond needs to have topology + current TRC at the very least.

The topology can be fetched from the discovery service. sciond already allows fetching the topology on start up when configured.

The DS should be configured to serve the topology according to https://godoc.org/github.com/scionproto/scion/go/lib/discovery on port 8041 (https://github.com/scionproto/scion/wiki/Default-port-ranges#discovery-service) 

see `./bin/sciond --help-config` the section `discovery` for configuration options.

Sciond should have a bootstrap mode, where it can just be configured with an URL in the config file and will then automatically:
- fetch the topology and write it to disk
- fetch the newest local ISD TRC from the certificate server.

Because we currently do not have support for TAACs, the received TRC has to be trusted without any further verification. Thus, bootstrap mode should not be enabled by infra services.

**Comment by scrye** [comment]
The devil is in the details here, there are _many_ questions that need clarification (especially related to the trust model and the trust policy) before a bootstrap can be automatic.

Ultimately, this is more easily done manually by writing a custom small script to solve the bootstrap problem with a few `curl`/`cp` commands.

So, given that the it looks like too much work for little benefit, (and with @Oncilla's offline blessing) closing this as a Won't Fix.
