### ISSUE TITLE
metrics: Code generation

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3178]
Now that we have a standard way of instrumenting our code with metrics.
We should investigate, whether it is worth writing a code generator that takes care of writing the boiler plate code

**Comment by scrye** [comment]
With the new metric patterns (where we define metrics only once in main and then propagate them as interfaces to various modules), the amount of boilerplate is much smaller. While some stuff can still be generated, it wouldn't decrease the size of code too much. Closing this.
