### ISSUE TITLE
Investigate having su-exec handle capabilities

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3190]
We currently use https://github.com/Anapaya/su-exec as the entrypoint in docker containers so we can use matching UIDs/GIDs inside the container as outside. We also have processes that require capabilities in order to run (e.g. the SIG). As bazel doesn't support running setcap against a docker image that it's creating, currently this has to be managed by having a wrapper Dockerfile that runs setcap against the app binary.

It might be possible to have su-exec use ambient capabilities (https://lwn.net/Articles/636533/) to set the capabilities at run-time instead. That would lower the maintenance overhead for the docker containers.

**Comment by scrye** [comment]
We dropped `su-exec` altogether because we no longer need matching uids/gids. Closing.
