### ISSUE TITLE
scrypto: Clean up library

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#3230]
It is a bit awkward how algorithms are defined in the scrypto library.

We should have a clean definition of all supported signing and encryption algorithm.
The identifiers should have a distinct type.

**Comment by jiceatscion** [comment]
Obsolete. The code has been largely deleted by https://github.com/scionproto/scion/pull/3784

Please re-open an issue if you think that the replacing code has the same issue.

**Comment by matzf** [comment]
FWIW, the algorithm type definitions that @oncilla was perhaps referring to were deleted in [44eb59c25f49e86394f391](https://github.com/scionproto/scion/commit/44eb59c25f49e86394f391#diff-af81dbcc5c4107a693b5b54a3a6070dcf6845bf7a0e5b4085362a1cf3a43e3a9L29-L38).
