### ISSUE TITLE
ctags invalid option in Makefile

### ISSUE THREAD

**Issue by fin-ger** [scionproto/scion#3248]
```
# ./scion.sh topology
Shutting down: Terminating this run of the SCION infrastructure
Shut down
Compiling...
ctags: invalid option -- 'L'
	Try `ctags --help' for a complete list of options.
Makefile:44: recipe for target 'tags' failed
make: *** [tags] Error 1
```

This was run in a fresh ubuntu 16.04 installation. I proceeded by commenting out `ctags` in the Makefile, which worked for now.

Continuous Integration might help to prevent such issues.

**Comment by lukedirtwalker** [comment]
Hi @fin-ger thanks for the report. Actually the `tags` target is no longer needed, since we deleted the `c` directory. Do you want to create a PR removing it?

**Comment by fin-ger** [comment]
Sure. Give me a sec :D
