### ISSUE TITLE
SCMP tool cmn.NewSCMPPkt ignores error return values

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3276]
`Write` calls in `go/tools/scmp/cmn/common.go` should not ignore error return values. While the chance of them returning an error right now is 0, this can change when code around the `Write` calls is refactored, or if there are bugs lurking in the `Write` implementations. This can lead to very difficult to find bugs. Code should at least panic if an error occurs (propagating the error to the caller for this sort of tool probably isn't that useful).

**Comment by Oncilla** [comment]
scmp tool has been deprecated. Re-implementation in `scion` command should not have the same issues.
