### ISSUE TITLE
ci: running buildkite builds locally

### ISSUE THREAD

**Issue by karampok** [scionproto/scion#3286]
During development, it would be great to be able to run a ci pipeline locally.
What does it : 

1. given a pipeline yaml file and a documentation
2. do a local command `bk run  /path/to/pipeline.yml` as documented
3. see that the local buildkite-agent runs the build same as in CI

where the pipeline.yaml to be the default pipeline (e.g. unit-tests) and the acceptance pipeline.

**Comment by karampok** [comment]
From my research, as long as we do not try to push images somewhere but use the local registry, it should be easy.

````
#!/bin/bash

# documentation
# https://buildkite.com/docs/agent/v3/cli-pipeline

#https://github.com/buildkite/cli/
#https://github.com/buildkite/agent/releases/download/v3.16.0/buildkite-agent-linux-arm64-3.16.0.tar.gz

export BUILDKITE_BUILD_PULL_REQUEST=localPR
export BUILDKITE_BUILD_NUMBER=localXYZ
export BUILDKITE_ORGANIZATION_SLUG=localSlug
export REGISTRY=myprivate.io

temp=/tmp/pipeline.yml
.buildkite/pipeline.sh > $temp
sed -i '/docker push/d' $temp
set -x
bk run --dry-run --prompt --env LOGNAME=$(whoami) $temp
```

**Comment by lukedirtwalker** [comment]
With the new pipeline we are closer to run it locally. Steps involved:
install [bk](https://github.com/buildkite/cli)
install [buildkite-agent](https://github.com/buildkite/agent)
`.builkite/pipeline2.sh > full-pipeline.yml`
`bk local run --env LOGNAME=$USER full-pipeline.yml`
But some steps are still failing.
