### ISSUE TITLE
Do not Initialize all metric with labels

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#3298]
For every element that exposes `bs_keepalive_sent_msgs_total`, there is one with `if_id="0"`. This is also missing the `result="` label.

**Comment by karampok** [comment]
Can we clarify which exactly commit are you running?

**Comment by karampok** [comment]
From a slack conversation
```
having them with nonsense values definitely doesn't work,
we could try with empty values, and see if that works
otherwise just remove preregistration
```

As part of this story we will have only empty strings on the preregistration.

**Comment by lukedirtwalker** [comment]
If there are senseful values we can prefill we should always prefer that.

**Comment by karampok** [comment]
As discussed we will not initialize metrics.

**Comment by karampok** [comment]
@Hermain this is the commit https://github.com/scionproto/scion/pull/3333/commits/392b8a1b1efefcc6a01ac3705cd6fdc253eab549
that enables or disables the pre-init of the metrics.

I suggest that we keep the behavior as it is until we need again to pre-init the metrics for a reason.
Feel free to create an issue if you find that important, so we could plan and  think of a way (flag, build flag etc.)
