### ISSUE TITLE
BR: Interface down error

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#3301]
Bringing down an interface that the BR is running on produces: 
`[EROR] Error sending packet(s) src=[x.x.x.x]:30042 err="write udp x.x.x.x:30042: sendmmsg: invalid argument"`
Where x.x.x.x is configured on the interface that is taken down. When bringing the interface up again, the BR does send packets anymore on that interface. It seems to be stuck somewhere.

Testing this with the local interface (i.e. the network interface the BR uses to talk to the local AS), we can see the following in the metrics:
-  `br_output_bytes_total{ifid="loc"}` stops incrementing
-  `br_output_write_errors_total{ifid="loc"}` increments by 1
-  `br_output_writes_total{ifid="loc"}` stops incrementing
- `ringbuf_read_entries_count{ring_id="loc_out"}` drops to 1/sec
- `ringbuf_used_entries` stays at 0

This implies that the posixOutput goroutine is still running, and still reading from the ringbuf as normal, but somehow isn't doing any writes.

**Comment by Oncilla** [comment]
pretty sure this is related to https://github.com/scionproto/scion/issues/3050

**Comment by Oncilla** [comment]
This has been addressed by #3547
If the border router gets into this state, it can not recover. Thus, as of #3547 it fatals out.

**Comment by worxli** [comment]
It's unclear if this issue has been solved, I can still see the errors when doing `ifdown enox` on the interface. But after `ifup enox` it seems to recover, if this is the case then I'd say the issue is solved.
But this ticket says that the BR shut fatal out which doesn't happen. Can we therefore validate what the current and what the expected behaviour is?
```
2020-04-29 13:26:10.059863+0000 [EROR] Error sending packet(s) src=169.254.1.1:30042 err="write udp 169.254.1.1:30042: sendmmsg: network is unreachable"
...
2020-04-29 13:26:10.637367+0000 [INFO] IFState: intf deactivated ifid=9
2020-04-29 13:26:11.399602+0000 [EROR] Error sending packet(s) src=169.254.1.1:30042 err="write udp 169.254.1.1:30042: sendmmsg: network is unreachable"
...
2020-04-29 13:26:38.400741+0000 [EROR] Error sending packet(s) src=169.254.1.1:30042 err="write udp 169.254.1.1:30042: sendmmsg: network is unreachable"
2020-04-29 13:26:39.406407+0000 [INFO] IFState: intf activated ifid=9
```

**Comment by Oncilla** [comment]
The error shown in this log differs from the one in the initial issue: `sendmmsg: invalid argument"`
We treat network is unreachable as recoverable error.

I think the two cases are not equivalent

**Comment by worxli** [comment]
I am currently unable to reproduce `sendmmsg: invalid argument` error, thus closing this issue for real now.
