### ISSUE TITLE
BS/PS: add handler for scmp revocations

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3310]
Both the BS and PS will log a warning when they receive an SCMP revocation. At a minimum, this warning shouldn't be logged. As a slightly-less-than-minimum, they should process the revocation. While in some circumstances the BR will also fork a revocation to them, this doesn't happen in all cases, and could also be dropped.

**Comment by scrye** [comment]
(Note that the BS and PS have now been replaced by a monolithic ControlService)

#3743 changes this issue in the following ways:
- SCMP data-plane revocations may be seen by the ControlService; the ControlService packet layer may decide to act on the revocation, or discard it; the higher-level RPC layer will need to retry a different path if an RPC failed.
- The BR will not fork revocations to the ControlService

**Comment by oncilla** [comment]
We register an SCMP handler nowadays
