### ISSUE TITLE
Tracing: limit amount of data stored

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3322]
I had 105GB of data in `traces/` that i've never used, or knew about. Can we cap the amount of trace data that gets stored on disk? Or, failing that, maybe disable it by default.

**Comment by lukedirtwalker** [comment]
We could just delete `traces` whenever we setup a new topology.

**Comment by Oncilla** [comment]
partially addressed by #3709

The underlying issue is #1916

**Comment by lukedirtwalker** [comment]
@Oncilla #1916 seems unrelated? Also #3709 doesn't really improve this, since the data in `/traces` is a bind-mount and not affected by `-v`.

**Comment by Oncilla** [comment]
Uff. I meant to link to https://github.com/jaegertracing/jaeger/issues/1916

It is partially addressed because scion topology deletes the traces dir when starting the topology

**Comment by oncilla** [comment]
Not an issue anymore
