### ISSUE TITLE
Bazel caching

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#3337]
We should use bazel caching locally and on the CI to speed up things:

https://docs.bazel.build/versions/master/remote-caching.html describes some options:
- We can setup our own nginx
- We can use GCS, though from the CI (AWS) that is not idea
- We can try to use S3 on the CI (needs to be investigated, apparently performance is not great)
- Use disk cache (on CI share an NFS volume for all agents)

**Comment by worxli** [comment]
Note: Bazel should be running on the host (makes things vastly easier). Therefore this is blocked on #2791

**Comment by lukedirtwalker** [comment]
An example how to do it is here: https://github.com/scionproto/scion/pull/3439
Note that we need to change the .bazelrc file to actually use remote caching.

**Comment by scrye** [comment]
The new pipeline (see https://github.com/Anapaya/scion/issues/1671) will be using this from the start.
