### ISSUE TITLE
Remove addr.AppAddr

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3344]
Instead, use `net.UDPAddr` whenever possible. For code needing to move SVC addresses around, consider using `net.Addr` instead and have the address cast to the type at the point of use.

Probably the easiest way to implement this is to create multiple PRs that remove `AppAddr` a few packages at a time.

**Comment by karampok** [comment]
After the snet write/read refactor, there are the following references
```

15:46 $ ag addr.appaddr
go/lib/snet/svcaddr.go
40:             Host:    &addr.AppAddr{L3: a.SVC},

go/lib/snet/addr.go
37:     Host    *addr.AppAddr
184:    return &Addr{IA: ia, Host: &addr.AppAddr{L3: l3, L4: l4}}, nil

go/lib/snet/addr_test.go
30:     host4 := &addr.AppAddr{
34:     host6 := &addr.AppAddr{

go/lib/snet/udpaddr.go
43:             Host: &addr.AppAddr{

```
Which would be removed once the snet.Addr is removed (different stories)
