### ISSUE TITLE
CertRenewal: Port Trust v1 request handler to Trust v2

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3479]

**Comment by scrye** [comment]
Given the AS attributes introduced by https://github.com/Anapaya/scion/issues/1762, if the CS is in an Issuing AS, the handler should run the normal issuance logic. Otherwise, it should return an error to the client saying it is not an issuing AS.

**Comment by scrye** [comment]
Once the spec is in, we can implement server side support for it on top of capnp messages.

**Comment by Oncilla** [comment]
This is closed in favor of efforts of translating the current certificates to x509 certificates.
