### ISSUE TITLE
CertRenewal: Port Trust v1 automatic renewal requests to Trust v2

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3480]

**Comment by scrye** [comment]
The functionality should be implemented in a decoupled library, s.t. it's easier to build a binary tool on top of it later.

For the moment, the CS should just spawn a periodic task that calls the certificate renewal client library to speak to the issuing CS.

Dissemination is an open problem, but maybe there's a way where we don't need it (e.g., if we coalesce the services).

To test this, we should run the end2end integration suite with very short renewal times (how short is too short? needs some investigation).

**Comment by lukedirtwalker** [comment]
uses the messenger:
```go
	RequestChainIssue(ctx context.Context, msg *cert_mgmt.ChainIssReq, a net.Addr,
		id uint64) (*cert_mgmt.ChainIssRep, error)
```
First create the renewal.SignedRequest
Input:
- Current cert
- Current private signing key
- New keys (private keys for PoP)

Output: SignedRequest

Then put the SignedRequest into a `cert_mgmt.ChainIssReq` and send it via the messenger.

**Comment by Oncilla** [comment]
This is closed in favor of efforts of translating the current certificates to x509 certificates.
