### ISSUE TITLE
Rename name argument of bazel function scion_app_images to nameprefix

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3541]
Currently the `scion_app_images` function call suggests it creates a rule with the specified name, but it actually combines it with a suffix to construct the final name. This makes it confusing when trying to reference the rule name from the command line.

Renaming `name` to `nameprefix` would eliminate the confusion.

**Comment by matzf** [comment]
Fixed in 3e0d994ebf1cc2d2acdc78552a3f31ebafe86459
