### ISSUE TITLE
Migrate Integration - Subset E2E tests to new pipeline

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3576]
The scionproto v2 testing CI pipeline does not contain the following AS subset end to end tests:
- `e2e_integration mode=core-core`
- `e2e_integration mode=noncore-localcore`
- `e2e_integration mode=noncore-core`
- `e2e_integration mode=noncore-noncore`

These should be added again.

**Comment by oncilla** [comment]
Has not been needed so far
