### ISSUE TITLE
CI: Add pipeline/step to upload docker images to dockerhub

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3580]
For tags we should automatically upload docker images to docker hub. This can either be a separate pipeline, or a step in the existing pipeline.

**Comment by lukedirtwalker** [comment]
Probably a separate pipeline will be better since this pipeline will need to have access to docker credentials, while the "scion" pipeline could be pubic.

**Comment by scrye** [comment]
We should only push releases.
