### ISSUE TITLE
CI: Add collection of kernel packet loss to new pipeline

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3585]
https://github.com/scionproto/scion/pull/3581 Removes the old pipeline it contained functions `softnet_stat_snapshot`, `detect_packet_loss_since_snapshot` for collecting kernel metrics about lost packages. We should consider if we still need that and if so, add it to the new pipeline.

**Comment by oncilla** [comment]
So far we never needed it. Also, every time we suspected the kernel dropping packets, it turned out to not be the case
