### ISSUE TITLE
infra: Use trc.Attributes instead of infra.Attributes

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3623]
Now that v2 trust store is merged, infra.Attribute is no longer needed and can be replaced with trc.Attribtue everywhere.
[]infra.Attribute can be replaced by trc.Attribtutes

Also, trust/inspector.go:hasAttribtues can be replaced by a method call on trc.Attributes

**Comment by scrye** [comment]
Because we are planning to migrate to an X.509 trust store, is this still needed?

**Comment by lukedirtwalker** [comment]
This no longer exists in master.
