### ISSUE TITLE
Proposal: Deploy TCP for intra-AS RPCs

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3636]
Intra-AS traffic does not need to be SCION; the path is empty and BRs are not involved in forwarding (though they can be destinations for RPCs targeting their control-plane).

We can simplify the messaging stack inside an AS by using plain TCP to transport intra-AS RPCs. This also allows us to easily add TLS support.

**Comment by lukedirtwalker** [comment]
@scrye is this still valid? We have sciond talking via TCP to the CS. There are no longer different services than the CS. BR - CS communication will go away with the revocation rework.

**Comment by scrye** [comment]
This is already in, yes. Closing.
