### ISSUE TITLE
Update default port ranges in wiki page

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3655]
The port ranges on the [wiki page](https://github.com/scionproto/scion/wiki/Default-port-ranges) are no longer up to date now that BS/CS/PS have been coalesced into a single Control Service. They should be updated.

**Comment by scrye** [comment]
Also, regarding TCP usage, the SCIOND documentation should make it explicit:
- that SCIOND talks TCP in the local AS
- that its Host API is exposed over TCP on the port listed as "Control Plane" in the current documentation (and the port should be renamed to "API" or something similar)

**Comment by lukedirtwalker** [comment]
@scrye is that still the case?

**Comment by matzf** [comment]
This information has been updated in the meantime, and somewhat more detailed information is available in the "port table" section of the operational manuals pages of the individual components.

- [router](https://docs.scion.org/en/latest/manuals/router.html#port-table)
- [dispatcher](https://docs.scion.org/en/latest/manuals/dispatcher.html#port-table)
- [daemon](https://docs.scion.org/en/latest/manuals/daemon.html#port-table)
- [cs](https://docs.scion.org/en/latest/manuals/control.html#port-table)
- [sig](https://docs.scion.org/en/latest/manuals/gateway.html#port-table)

This looks sufficient to close this issue for now. The wiki page should perhaps be removed at some point.
