### ISSUE TITLE
rename: common.IFIDType to addr.IfID

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#3676]

**Comment by matzf** [comment]
Also, change the type from currently `uint64` to `uin16`, as the actual interface IDs on the wire are only 12 bits.

**Comment by scrye** [comment]
`common.IFIDType` is deprecated:

https://github.com/scionproto/scion/blob/7f5de5ba4d91d505e0774aa875f44d45852db8d1/go/lib/common/defs.go#L37-L41

Won't fix this.

**Comment by matzf** [comment]
@scrye, @juagargi, sorry I had not previously seen this deprecation note. This `common.IFIDType` is currently also used for higher level descriptions of paths, like for example `snet.PathInterface`, that (presumably) should be usable to describe paths of all or at least most types. I don't think specializing this for the different path types would be required or desirable. What type should be used there? What about e.g. `addr.IfID`? ;)
