### ISSUE TITLE
wiki: describe why no quic default port is needed

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#3681]

**Comment by matzf** [comment]
The default port used for inter-AS control plane traffic, which is the thing using QUIC these days, is documented:

> 
> Control Service
> 
> Purpose | Protocol | Control Plane
> -- | -- | --
> Control plane (inter-AS) | SCION/UDP | 30252
> Control plane (intra-AS) | TCP | 30252
> ... | ... | ...
>
