### ISSUE TITLE
config: print minimal config

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#3683]
When calling `{cs,border,sciond,godispatcher} -help-config` the full configuration file, including all configurable fields, is dispalyed.

We should have a `-help-minimal-config` that displays the minimal required configuration

**Comment by worxli** [comment]
Instead of having a minimal-config we should just make sure the config produced by help-config works in a docker container. For an operator it is ok to have all config options (with their default configured) in the config file.

**Comment by worxli** [comment]
Also make sure the container is able to run without bind-mounts configured.

**Comment by scrye** [comment]
This probably needs to be split into 4 different issues (one for each of `cs`, `border`, `sciond`, `dispatcher`), with each one also explaining _what_ a minimal config would mean.

**Comment by scrye** [comment]
> Also make sure the container is able to run without bind-mounts configured.

Isn't this difficult to do because the Dispatchers exposes its API on a UNIX domain socket? How would the default configuration for a dockerized `cs` look like, given no binds?

**Comment by worxli** [comment]
Ok, for the dispatcher it's not possible. But in general there are many bind-mounts that would not be necessary (e.g. for caching).

**Comment by scrye** [comment]
Do those bind mounts affect how the minimal config might look like? The docker container has its own root, so every file touched in there is local to the container unless the user explicitly bind-mounted something, so any default file paths would work as long as they are valid paths.

**Comment by worxli** [comment]
Exactly, the default paths need to exist inside the image and not rely on being bind-mounted.
