### ISSUE TITLE
cs: register down paths from beacons

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#3700]
Currently, the beacon registrar registers the up-path to the core in the local path database.

In addition, it could register a down-path for every AS-hop on the path. This will get rid of some odd error scenarios, where the AS cannot reach ASes that are on its direct up path.

**Comment by Oncilla** [comment]
Alternatively, the segment fetcher https://github.com/scionproto/scion/blob/master/go/lib/infra/modules/segfetcher/fetcher.go#L118
could be enhaced, such that it discovers that the destination is actually already on the path.
