### ISSUE TITLE
Override dispatcher socket path

### ISSUE THREAD

**Issue by ekuiter** [scionproto/scion#3703]
There does not seem to be a simple way to override the dispatcher socket path defined here:
https://github.com/scionproto/scion/blob/efc9deddc6b4b3f23944ad98f99134beca0e5ae5/go/lib/sock/reliable/reliable.go#L85

For example, with an environment variable, flag or TOML configuration option. Our problem is that the given path is not accessible on Android, and right now we use a [script](https://github.com/ekuiter/scion-android-binary/blob/master/build.sh) to rewrite reliable.go to read the path from an environment variable.

**Comment by Oncilla** [comment]
I don't think rewriting the default value is the right approach here.

Instead, we should modify all calls `reliable.NewDispatcher("")` to take a configurable argument.

**Comment by scrye** [comment]
Closing this. The plan is to deprecate the Dispatcher soon-ish (see scionproto/scion#3961), so no new features will be going in. The removal of the dispatcher should also fix the root issue with the path on Android (because the unix domain socket is no longer needed).
