### ISSUE TITLE
Update Go, Bazel, rules-go, and gazelle to the latest versions

### ISSUE THREAD

**Issue by ekuiter** [scionproto/scion#3704]
All of the packages mentioned in the title are outdated. Especially Bazel, which is now available in version 3.0.0 instead of 1.2.0. Updating these packages fixes a number of issues, especially regarding compilation of SCION for [Android smartphones](https://github.com/ekuiter/scion-android-binary).

**Comment by lukedirtwalker** [comment]
What exactly is Bazel 3.0 vs 1.2 fixing for you?

**Comment by ekuiter** [comment]
I had several issues with Android compilation which were due to the use of Bazel 0.26.1 in SCION's previous versions, where upgrading to 3.0 helped a lot (but caused other issues in turn, e.g. nogo crashing, which had to be addressed separately). So, upgrading 1.2 to 3.0 does not benefit me as such, but maybe others in the future.

Here are some of my issues, which are partly due to old versions:
bazelbuild/rules_go#195, bazelbuild/rules_go#2089, bazelbuild/rules_go#2172,
bazelbuild/rules_go#2371, scionproto/scion#3325, Catfriend1/syncthing-android#370, golang/go#29674. For example, one problem was a misaligned TLS segment in Go's compilation output, preventing Android to start the executable. This is due to Go 1.11 and fixed in SCION v0.5.0 by upgrading to Go 1.13. Keeping all versions up-to-date helps prevent such issues in the first place.

**Comment by lukedirtwalker** [comment]
With https://github.com/scionproto/scion/pull/3782 merged, we are at least on Bazel on a very recent version, other stuff you mentioned is also quite recent. We constantly monitor updates in libs around, sometimes they go a bit out of date but we try to keep up to date with them. Just blindly updating has bitten us in the past, so if there is no (strong) reason to update we will keep current versions for a while even if there are newer version available.
