### ISSUE TITLE
make topo description file names lower case

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3711]
The only place where we have file names starting with a capital letter is in the `topology` directory.
(plus the all-caps files like README etc.)

We should make them lower cased to be consistent.

**Comment by scrye** [comment]
To add to this, the g4 grammar files also use upper case:

```
go/lib/pathpol/Sequence.g4
go/lib/pktcls/TrafficClass.g4
```

Might as well fix those too as part of this.
