### ISSUE TITLE
SCION Header version 2

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#3714]
Over the past months, the SCION team has been working on a new version of the SCION header, with the goal of addressing most of the current issues we identified over the past year. The current design document together with the motivation behind it can be found below.

[SCION_Header_Redesign v2019-11-05.pdf](https://github.com/scionproto/scion/files/4483100/SCION_Header_Redesign.v2019-11-05.pdf)

This issue adds some more details to the design document where it was not completely specific. Additionally, we are proposing a new addition of flags in the hop field (more details belows), a new path type and the introduction of a path meta header for the SCION Path Type and the OneHopPath type.

# SCION Header Formats
This is a brief reference about the new SCION header formats. For the exact meaning of each field consult the design document.

#### Header alignment
In order to reduce the amount of padding, it is proposed to align headers to multiples of 4 bytes instead of 8 bytes.

## Common Header
The Common Header has the following format:
```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|Version|      QoS      |                FlowID                 |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|    NextHdr    |    HdrLen     |          PayloadLen           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|    PathType   |Dt |Dl |St |Sl |              RSV              |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

#### Address Type and Length
DT/ST and DL/SL encode host-address type and host-address length, respectively, for destination/
source. The possible host address length values are 4 bytes (0), 8 bytes (1), 12 bytes (2) and
16 bytes (4). ST and DT additionally specify the type of the address. Currently, we only define the IP address family as type 0. Thus, an IPv4 address is encoded as `len=0, type=0` and an IPv6 address is encoded as `len=3, type=0`.
If some address has a length different from the supported values, the next larger size can be used and the address can be padded with zeros.

#### Flow ID
A flowlabel of 20 bits is added to the common header in order to effectively support RSS on
routers and middleboxes. It follows the flow-label specification for IPv6, but is **mandatory** to be set by applications.

#### QoS Flags
The QoS flags are similar to those in the IP header and also include the ECN (Explicit
Congestion Notification) bits.

#### Path Type
The `PathType` specifies the SCION path type with up to 256 different types. The
format of each path type is independent of each other. The initially proposed SCION path
types are SCION (0), OneHopPath (1), EPIC (2) and COLIBRI (3). Here, we only specify the SCION and OneHopPath path types.

**Note**, the OneHopPath path type is an addition to what's described in the design document.

**Note**, the PathOffset field in the common header is gone. Instead we introduce a PathMeta header for SCION and OneHopPath types. This ensures that each path type is self contained.

**Note**, the `QoS` and `FlowID` fields where moved to the first line of the common header. This is to be in line with the IPv6 header from which we borrow the specifications of these two fields.

## Address Header
The Address Header has the following format:
```
0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|            DstISD           |                                 |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                                 +
|                             DstAS                             |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|            SrcISD           |                                 |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                                 +
|                             SrcAS                             |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                    DstHostAddr (variable Len)                 |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                    SrcHostAddr (variable Len)                 |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
## SCION Path Type
The path layout is modified. Instead of the current layout with interleaved info fields and hop fields, in the future layout all info fields are at the beginning, followed by all hop fields. Additionally, there is now a PathMeta header contain meta information about the SCION path.
```
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                          PathMetaHdr                          |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           InfoField                           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                              ...                              |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           InfoField                           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           HopField                            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           HopField                            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                              ...                              |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

### PathMeta Header
The PathMeta field is a 4 byte header containing meta information about the SCION path contained in the path header. It has the following format:
```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|CI |  CurrHF   |    RSV    |  Seg0Len  |  Seg1Len  |  Seg2Len  |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
**(C)urr(I)NF:** 2-bits index (0-based) pointing to the current info field (see offset calculations below).
**CurrHF:** 6-bits index (0-based) pointing to the current hop field (see offset calculations below).
**Seg{0,1,2}Len:** The number of hop fields in a given segment. `SegNLen > 0` implies the existence of info field `N`.

**Note**, the PathMeta header is in addition to what's described in the design doc.

#### Path Offset Calculations

The number of info fields is implied by `Seg{0,1,2}Len > 0`, thus `NumINF = N + 1 if SegNLen >0 for N in (2, 1, 0)`. It is an error to have `SegXLen > 0 && SegYLen = 0, X > Y`. If all `Seg{0,1,2}Len == 0` then this denotes an empty path, which is only valid for intra-AS communication.

The offsets of the current info field and current hop field (relative to the end of the address header) are now calculated as
* `InfoFieldOffset = 4 bytes + 8 bytes * CurrINF`
* `HopFieldOffset = 4 bytes + 8 bytes * NumINF  + 12 bytes * CurrHF`
To check that the current hop field is in the segment of the current info field, the `CurrHF` needs to be compared to the `SegLen` fields of the current and preceding info fields.

This construction allows for up to three info fields, which is the maximum for a SCION path. Should there ever be a path type with more than three segments, this would require a new path type to be introduced (which would also allow for a backwards-compatible upgrade). The advantage of this construction is that all the offsets can be calculated and validated purely from the path meta header, which greatly simplifies processing logic.

### Info Field

InfoField has the following format:
```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|r r r r r P S C|      RSV      |             SegID             |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           Timestamp                           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
`P`eering, `S`hortcut, and `C`onstruction Direction remain unchanged in semantics.

The new segment identifier `SegID` is a updatable field that is required for the new
MAC-chaining mechanism (see the design doc for details)

**Note**, `CurrHF` and `SegLen` has been moved out of the info field into the PathMeta header.

### Hop Field
Hop fields are now fixed at 12 bytes, instead of previously being multiples of 8 bytes (variable length). Compared to the current standard of 8 bytes, this allows us to increase
the size of interface IDs from 12 bit to 16 bit and significantly strengthen the security. The increased size of the hop-field MAC now makes brute-force attacks practically infeasible
as 2^48 ~= 2.8 * 10^14 packets have to be sent to guarantee a successful attack. On
the other hand, having a fixed size for hop fields enables more efficient processing and
avoids excessive overhead.

The Hop Field has the following format:
```
  0                   1                   2                   3
  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |r r r r r r A A|    ExpTime    |           ConsIngress         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |        ConsEgress             |                               |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                               +
 |                              MAC                              |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
#### Addition
With the new SCION header format, the existing hop field flags `Xover` and `VerifyOnly` are not needed anymore. `Xover` is implicit now that changing segments always happens at the last hop field. Furthermore, `VerifyOnly` is not needed anymore, since the new authentication mechanisms does not require hop fields that are only there for verification (but not for routing).

Instead we are adding two new flags, the _ConsIngress Router Alert_ and the _ConsEgress Router Alert_. The semantics of these flags are the following:
* If the _ConsIngress Router Alert_ is set, the ingress router (in construction direction) will process the L4 payload in the packet.
* If the _ConsEgress Router Alert_ is set, the egress router (in construction direction) will process the L4 payload in the packet.

These flags were added to have a zero-overhead mechanism to notify routers on a path to look at the payload for a given packet. A sender can use this to address a specific router on the path without knowing its address. 

A use case for this is the `SCMP traceroute`. So far, a `SCMP Hop-by-hop extension` was included in the packet header notifying routers on the path to parse the SCMP payload. However, this required _every_ router on the path to parse the payload even if, e.g., in the case of `traceroute`, only a single one of them needed to actually process and reply to the traceroute request. While `SCMP traceroute` is currently the only use case we have for these flags, we imagine that this mechanism can be used for future use cases as well.

**Note,** a sender cannot rely on multiple routers retrieving and processing the payload even if it sets multiple router alert flags. This is entirely use case dependent and in the case of `SCMP traceroute` for example the router for which the traceroute request is intended will process it (if the corresponding router alert flag is set) and reply to the request without further forwarding the request along the path. Use cases that require multiple routers/hops on the path to process a packet should instead rely on a _hop-by-hop extension_.

## OneHopPath Path Type
The OneHopPath path type is a special case of the SCION path type. It is used to handle communication between two entities from neighboring ASes that do not have a forwarding path. Currently, it's only used for bootstrapping beaconing between neighboring ASes.

A OneHopPath has exactly the path meta field, one info field and two hop fields with the speciality that the second hop field is not known apriori, but is instead created by the corresponding BR upon processing of the OneHopPath. 

```
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                          PathMetaHdr                          |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           InfoField                           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           HopField                            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           HopField                            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by mlegner** [comment]
Great work, I have no objections to most of the modifications. A few questions that arose:
- What was the reason to use introduce the Active flags instead of an index of the current Info field?
- The computation of `NumINF` and thus `HopFieldOffset` seems a little tedious to me (also, I understand the idea of but cannot properly parse the definition `NumINF = N + 1 if SegNLen >0 for N in (2, 1, 0)`). As there are two 0 bits, we could use them to encode the number of segments.

**Comment by shitz** [comment]
> 
> 
> Great work, I have no objections to most of the modifications. Two questions that arose:
> 
>     * What was the reason to introduce the Active flags instead of an index of the current Info field?
> 
That's a good question. It felt in a way more natural and pleasing on the eyes. With that being said, I agree that we could also simply use a 2 bit index, like the following:
```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|CI |  CurrHF   |    RSV    |  Seg0Len  |  Seg1Len  |  Seg2Len  |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
>     * The computation of `NumINF` and thus `HopFieldOffset` seems a little tedious to me (also, I understand the idea of but cannot properly parse the definition `NumINF = N + 1 if SegNLen >0 for N in (2, 1, 0)`). As there are two 0 bits, we could use them to encode the number of segments.
Yeah, maybe it's not written in an intuitive way, but basically it says 
```
if Seg2Len > 0 then NumINF = 3
else if Seg1Len > 0 then NumINF = 2
else NumINF = 1
```
You have to parse all `SegLen` fields anyway, thus I think it's not worth it to include 2 bits of redundant information.

**Comment by mlegner** [comment]
> > What was the reason to introduce the Active flags instead of an index of the current Info field?
> 
> That's a good question. It felt in a way more natural and pleasing on the eyes. With that being said, I agree that we could also simply use a 2 bit index, like the following:
> 
> ```
>  0                   1                   2                   3
>  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
> +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> |CI |  CurrHF   |    RSV    |  Seg0Len  |  Seg1Len  |  Seg2Len  |
> +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> ```

That was what I meant. I personally would have a slight preference for this option, but as I'm not much affected, I think your opinion is more relevant.

> Yeah, maybe it's not written in an intuitive way, but basically it says
> 
> ```
> if Seg2Len > 0 then NumINF = 3
> else if Seg1Len > 0 then NumINF = 2
> else NumINF = 1
> ```

Yes, that's how I understood it.

> You have to parse all `SegLen` fields anyway, thus I think it's not worth it to include 2 bits of redundant information.

I understand. I was worried that this computation would slow down the processing but it probably doesn't matter. In particular if you would anyway need to check the consistency.

**Comment by shitz** [comment]
> 
> 
> > > What was the reason to introduce the Active flags instead of an index of the current Info field?
> > 
> > 
> > That's a good question. It felt in a way more natural and pleasing on the eyes. With that being said, I agree that we could also simply use a 2 bit index, like the following:
> > ```
> >  0                   1                   2                   3
> >  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
> > +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> > |CI |  CurrHF   |    RSV    |  Seg0Len  |  Seg1Len  |  Seg2Len  |
> > +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> > ```
> 
> That was what I meant. I personally would have a slight preference for this option, but as I'm not much affected, I think your opinion is more relevant.
> 
I adopted your proposal and updated the issue. 👍 
> > Yeah, maybe it's not written in an intuitive way, but basically it says
> > ```
> > if Seg2Len > 0 then NumINF = 3
> > else if Seg1Len > 0 then NumINF = 2
> > else NumINF = 1
> > ```
> 
> Yes, that's how I understood it.
> 
> > You have to parse all `SegLen` fields anyway, thus I think it's not worth it to include 2 bits of redundant information.
> 
> I understand. I was worried that this computation would slow down the processing but it probably doesn't matter. In particular if you would anyway need to check the consistency.

Exactly. The consistency check makes this essentially equivalent in terms of processing overhead.

**Comment by matzf** [comment]
The address type fields `St` (`SourceType`) and `Dt` (`DestType`) in the common header were previously 6-bit fields, now they're only 2-bits.
It's not quite clear to me how this will be used. The description of the related length-fields hint at possibly many different address types, but only 2-bits for the type field seem too tight to encode this.

The "best" interpretation I could think of is that the address type ids can be chosen by each AS, so that each AS can have up to 4 address types of its choice. This seems like a neat idea, but I don't fully see yet how this would work; when initiating communication with a host in a remote AS, how do you know which type id should be used?

Could you clarify how these address type fields will be used?

**Comment by shitz** [comment]
Besides the `{Src/Dst}Type` there are also the `{Src/Dst}Len` fields. The len fields give you 4 different lengths: 4B (0), 8B (1), 12B (2), 16B (3). The type fields give you 4 different address types _per length_, e.g., an IPv4 address has `len=0, type=0` or an IPv6 address has `len=3, type=0`. We believe these 4 length types together with 4 types per length will give enough flexilibility to also account for different host addressing schemes in the future (besides IP4/6).
