### ISSUE TITLE
Data-plane only revocations and keepalives between BRs

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3743]
(Discussing revocations and keepalive changes together in this issue because the two are  related)

### Revocation change

We should remove revocations from the control-plane, and replace them with data-plane only revocations. The removal part consists of:
- CSes would no longer create revocations;
- SDs would no longer cache revocations;
- applications would no longer inform SDs about revocations;
- transit BRs would no longer fork revocations;

The reasoning for this change can be found at the bottom of this post.

However, there are optimizations where it's desirable to quickly know that an interface is down; an application might want to reroute traffic to a different path at that point. We will be using Authenticated SCMP for this. SCMP messages will be created by the BR whose link has failed, and will be sent back to the host originating the traffic.

### Keepalive change

We should move keepalives from the CS to the BR. Keepalives are used to maintain the health of the data-plane, and the move would avoid a crash of the control-plane taking down the data-plane.

### Reasoning for the revocation change

Revocations **are an optimization**. Therefore, SCION networks should work correctly under the assumption they don't exist.

Revocations **are best effort**. Applications should not rely on data-plane revocations being delivered to operate correctly. Specifically, applications _should_ have state machines that switch from a broken path even if no revocation was received on that path.

Applications that depend on RPC timeouts should expect the timeouts to happen because a revocation might not be delivered, and MUST have the distributed algorithms operate correctly in a network which does not generate data-plane revocations.

To summarize, the design principle this issue advocates for is: a SCION network should work correctly without revocations. A SCION network with revocations should work _strictly_ better. If a revocation feature does _not_ bring a strict improvement, it should not be implemented.

#### Current state

We currently implement the following interactions related to revocations:
1. BS creates and sends a revocation to the local BR when it hasn't heard from a remote BS for a time;
2. If a BR sees a data-plane revocation on a core interface, and the destination is in this ISD, it forks the revocation, and forwards it to the local BS and PS services. This prevents the BS from propagating/registering revoked core PCBs. The destination check ensures that this is only done for revocations which impact the local ISD.
3. If a BR sees a data-plane revocation when receiving traffic from a parent AS, and the revoked interface is in the same ISD, the BR forks the revocation to the local BS and PS services. This ensures that ASes downstream of a revoked interface get informed quickly.
4. If a BR sees a data-plane revocation with a destination is the local AS, it forks the revocation to the local PS, to ensure that it stops providing segments with revoked interfaces to clients.
5. The PS forwards revocations to SD when replying to segment requests.
6. If an application receives a data-plane revocation, it informs SD. SD implements two aspects: (1) it verifies the revocation and informs the application if it was valid; (2) it caches the revocation to provide _unrevoked_ paths to clients.
7. If SD has a revocation that is valid for an amount of time, it will not serve paths containing the revoked interface, even though the interface might be up.

#### Discussion

Most of the optimizations in the previous sections do not provide strict improvements to a SCION network without revocations. Thus, they create subtle bugs and lead to awkward state machines in applications. The proposal is to remove most of them and ensure our applications work correctly in a SCION . Afterwards, we can slowly add optimizations that we are sure are strict improvements.

##### Issue A - SD not serving revoked path segments leads to loss of connectivity

Interactions (2), (3), (4), (5) from the previous section all serve the intent of having SD serve "better paths", that is, paths without revocations on them. However, this introduces some subtly faulty logic in applications.

Suppose there are two paths towards a destination: P1 and P2. P1 is much better than P2. P1 has a revocation on it, but only the PS knows it.

An application requests paths for the destination. It asks SD, SD asks the CS, the CS provides P1 and P2 and the revocation on P1, SD filters P1 because it is revoked, application receives P2. Application now thinks only P2 exists, and will happily use only P2 even after P1 comes back up, because it won't know of its existence.

Patching the application is the solution. "The application should poll SD for new paths to each destination".

##### Issue B - Revocations do not perfectly mirror interface state

Revocations have a life time that is decided _at the time the CS notices the network fault_. The most awkward aspect here is that the CSes on both sides of a link decide the lifetime. So if an admin takes an interface down for two seconds, the CS in the neighboring AS has no knowledge of the admin operation and just creates a revocation with a default lifetime, taking down traffic through the interface for much longer than needed. This has created network issues multiple times.

Patching applications is needed again. "The application should poll the path ahead of revocation expiry just in case it is usable".

##### Issue C - Revocations are amplification attack vectors

Revocations traveling through the data-plane can be replayed by design (the delivery itself is a statement of _revocation still applies due to its lifetime_, and it's done by CSes/BRs). This means that if a BR has a burst of data-plane revocations going through it, due to interactions (2), (3), (4) from the previous section it needs to do a lot of work just to fork the revocations. Depending on the number of CSes, the work can be 3x, 5x or even more.

The nastiest part here is that this "attack" can happen during legitimate traffic. If a 10G stream hits a revocation, the BR would reply to all the packets with an SCMP revocation. This means that BRs on the path back will do a lot of forking for legitimate traffic. This can also become an DoS vector for attackers: search for which interfaces in the SCION world are revoked, and blast them with traffic.

As a mitigation, remembering which revocations were forked might work, but this requires very complex logic in the BR. The whole complexity could be avoided by just not forking.

##### Issue D - Verifying a revocation stalls the data-plane

Sending a revocation with garbage data into an application's socket will make the application send it to SD. If it's garbage, SD will take a long time to verify and reply to the application. The application has the choice of using the same path, switching to a different one, or waiting for SD to reply. It takes all of these actions  _without_ having evaluated the revocation yet, so the revocation itself at this point brings no benefit.

For a high-speed data-plane application, a stall of even a few milliseconds is unacceptable.

**Comment by matzf** [comment]
Just an additional point on the keepalives: in the current implementation keepalives may be dropped by the routers due to congestion and as a consequence, the BS might accidentally revoke a healthy (and busy!) link.
If the keepalives are handled by the BR directly, it should be possible to avoid sending explicit keepalive messages most of the time as each received data plane packet signals that the interface is up. Explicit keepalives only have to be sent if the link is underused.

**Comment by scrye** [comment]
Closing this proposal as *Accepted* because this is now part of the roadmap and is currently being implemented.
