### ISSUE TITLE
Add scmp tool subcommands as scion tool subcommands

### ISSUE THREAD

**Issue by scrye** [scionproto/scion#3756]
#3708 introduced the `scion` command to aggregate the functionality of various tools.

The `scmp` tool has the following subcommands:
- `echo`: `ping`-like behavior
- `tr`: `traceroute`-like behavior
- `rp`: SCION-specific path recording tool

These subcommands should also be usable from the `scion` tool, as:
- `scmp echo` -> `scion echo`
- `scmp tr` -> `scion traceroute`
- `scmp rp` -> `scion recordpath`

The command-line arguments of the subcommands should be kept the same.

**Comment by Oncilla** [comment]
`scmp echo` should be translated to `scion ping`

**Comment by Oncilla** [comment]
`ping` command was added in #3796

**Comment by lukedirtwalker** [comment]
This is now implemented in master
