### ISSUE TITLE
 ParsePacket should return erros instead of panicking

### ISSUE THREAD

**Issue by dende** [scionproto/scion#3772]
When trying to fuzz test some of the parsers used all over the project, I stumbled upon the go package `github.com/scionproto/scion/go/border/braccept/parser`. It defines the function `ParsePacket`, which seems to be used only by the go struct `DevTaggedLayers`. 

In case of formating erros (wrong intendation etc) the whole thing panics instead of returning errors, see https://github.com/scionproto/scion/blob/master/go/border/braccept/parser/parser.go#L211. This makes it unnecessarily hard to write tests for that code.

**Comment by sgmonroy** [comment]
It is intentional to panic if there is an issue.
That parser is for testing only and not meant as a general application. 
It is definitely not meant to be fuzzed.

**Comment by dende** [comment]
Ah I see, thanks for the clarification. Even if it is test code only, I feel like returning errors would be more "go-ish".
