### ISSUE TITLE
staticinfo: port extension to protobuf

### ISSUE THREAD

**Issue by Oncilla** [scionproto/scion#3875]
PR #3874 translates the path segment from capnp to protobuf.
To keep the footprint of the PR smaller, the static info was not ported.

Additionally, some files were modified to disable static info. The changes need to be reverted:
(locations should be tagged with a FIXME comment.)

- [go/cs/beaconing/extender.go ](https://github.com/scionproto/scion/pull/3874/files#diff-1f9877490df6a71da51cc6cd371a748e)
- [go/lib/infra/modules/combinator/staticinfo_accumulator.go](https://github.com/scionproto/scion/pull/3874/files#diff-529361492c0bb42fb9af4868089f18ea)

**Comment by matzf** [comment]
Done, #3899.

**Comment by lukedirtwalker** [comment]
Fixed by #3899
