### ISSUE TITLE
bfd: dispatch intra-AS BFD messages with full underlay address

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#3891]
From `docs/protocols/bfd.rst`:
> Furthermore, SCION router creates one “internal” BFD session for every other SCION router instance within the same AS. The associated BFD packets must use SCION Empty path type.
> These BFD sessions are uniquely **identified by the source address, as it appears in the SCION address header**.
> [...]
> 
> Caveats
>
> Note that there is no UDP header, and therefore no ports in BFD/SCION protocol.
> The consequence is that there can’t be two SCION/BFD-enabled applications (e.g. two SCION router instances) sharing the same IP address.

The caveats section says it all -- this choice of BFD session identification disallows running more than one border router instance on the same (internal) IP address. This is suboptimal:
- running multiple router instances serving different external interfaces on the same (internal) IP can be useful for various purposes, e.g. isolating interfaces that have to be re-configured frequently from the more stable interfaces, failure isolation and working around implementation limits of number of interfaces per border router instances (if this still applies).
- consistency: the underlay used is IP/UDP, the configuration of the border router requires to specify the internal address as IP + port. The routers are identified with this internal IP+port everywhere, except here.
- nasty failure mode: accidentally configuring two router instances to use the same IP+port will result in a failure on startup, address already in use -- nice. However, running two border routers with the same IP will appear to work fine, but BFD will just silently not work properly. Note that 
- the argument in favour appears to be mostly about internal aesthetics, the BFD code does not need to be aware of the underlay used.

Looking at the code that implements this in `go/pgk/router/dataplane.go`, identifying the session based on the full underlay address instead of only the source IP could easily done.

**Comment by matzf** [comment]
Proposal for a patch:
```
diff --git a/go/pkg/router/dataplane.go b/go/pkg/router/dataplane.go
index 4cf7d852..b4d5ca5d 100644
--- a/go/pkg/router/dataplane.go
+++ b/go/pkg/router/dataplane.go
@@ -409,12 +409,12 @@ func (d *DataPlane) Run() error {
 			if pkts == 0 {
 				continue
 			}
-			for _, p := range msgs[:pkts] {
+			for i, p := range msgs[:pkts] {
 				origPacket = origPacket[:p.N]
 				// TODO(karampok). Use meta for sanity checks.
 				p.Buffers[0] = p.Buffers[0][:p.N]
 				copy(origPacket[:p.N], p.Buffers[0])
-				wr, err := d.processPkt(ingressID, &p, spkt, origPacket, buffer)
+				wr, err := d.processPkt(ingressID, &p, metas[i], spkt, origPacket, buffer)
 				switch {
 				case err == nil:
 				case errors.As(err, &scmpErr):
@@ -474,7 +474,7 @@ func (d *DataPlane) Run() error {
 	return nil
 }
 
-func (d *DataPlane) processPkt(ingressID uint16, m *ipv4.Message, s slayers.SCION,
+func (d *DataPlane) processPkt(ingressID uint16, m *ipv4.Message, meta conn.ReadMeta, s slayers.SCION,
 	origPacket []byte, buffer gopacket.SerializeBuffer) (BatchConn, error) {
 
 	defer func() {
@@ -495,11 +495,7 @@ func (d *DataPlane) processPkt(ingressID uint16, m *ipv4.Message, s slayers.SCIO
 	switch s.PathType {
 	case slayers.PathTypeEmpty:
 		if s.NextHdr == common.L4BFD {
-			src, err := s.SrcAddr()
-			if err != nil {
-				return nil, serrors.WrapStr("Failed to parse addr", err)
-			}
-			return nil, d.processIntraBFD(src, s.Payload)
+			return nil, d.processIntraBFD(meta.Src, s.Payload)
 		}
 		return nil, serrors.WithCtx(unsupportedPathTypeNextHeader,
 			"type", s.PathType, "header", s.NextHdr)
@@ -547,7 +543,7 @@ func (d *DataPlane) processIntraBFD(src net.Addr, data []byte) error {
 	}
 
 	ifID := uint16(0)
-	srcIPAddr, ok := src.(*net.IPAddr)
+	srcUDPAddr, ok := src.(*net.UDPAddr)
 	if !ok {
 		return serrors.New("type assertion failure", "from", fmt.Sprintf("%v(%T)", src, src),
 			"expected", "*net.IPAddr")
@@ -559,7 +555,7 @@ func (d *DataPlane) processIntraBFD(src net.Addr, data []byte) error {
 			return serrors.New("type assertion failure", "from",
 				fmt.Sprintf("%v(%T)", remoteUDPAddr, remoteUDPAddr), "expected", "*net.UDPAddr")
 		}
-		if bytes.Equal(remoteUDPAddr.IP, srcIPAddr.IP) {
+		if bytes.Equal(remoteUDPAddr.IP, srcUDPAddr.IP) && remoteUDPAddr.Port == srcUDPAddr.Port {
 			ifID = k
 			continue
 		}

```

**Comment by shitz** [comment]
Hi @matzf 

Thanks for bringing up this issue. We have discussed it internally and came to the conclusion that we'll add support for dispatching BFD messages based on the underlay as a _temporary workaround_, since apparently you are relying on having multiple routers per host and the overhead to support this is very little (as your patch shows).

The reason why we consider this a workaround is that the underlay should not be tied to the SCION protocol neither conceptually nor in the implementation. Unfortunately, there are a few areas where this is not the case in the implementation, e.g., using the destination address from the SCION header as the underlay destination address in the destination AS is such a coupling of SCION and underlay that shouldn't exist, but is currently there as a shortcut. We want to avoid adding more such couplings.

In the future, we are planning to move more towards a "BFD daemon" model, where BFD would be run on top of UDP/SCION. In such a setup, there can be one or multiple dedicated BFD endpoints (either as standalone processes or part of some bigger application) per host address.
