### ISSUE TITLE
Linter for reStructuredText (rst)

### ISSUE THREAD

**Issue by mlegner** [scionproto/scion#3894]
As documentation is now moving towards reStructuredText and Sphinx, it would be great to have a corresponding linter included in the `scion.sh lint` command. Ideally, this would both check style conventions (empty lines, trailing whitespaces, ...) and actual syntax. A brief search yielded a few tools [1-2] but I didn't have time to have a close look yet.

[1] https://github.com/myint/rstcheck
[2] https://github.com/twolfson/restructuredtext-lint

**Comment by matzf** [comment]
Done in #4503, albeit with sphinx-lint not the tools proposed here.
