### ISSUE TITLE
Scion border service config loc error in Ubuntu package

### ISSUE THREAD

**Issue by ahmetozer** [scionproto/scion#4064]
Hi everyone,
In scion package install on Ubuntu 18.04, scion-border-router@br-1.service  service looks /etc/scion/br-1.service.toml for configuration but scionlab-config is generates  /etc/scion/br-1.toml so service is not work by default install.

I currently use it with linking the files.

```bash
ln -s /etc/scion/br-1.toml /etc/scion/br-1.service.toml
```

**Comment by matzf** [comment]
Note: this issue refers to the packages and configuration provided by the SCIONLab project. 

Hi @ahmetozer, thank you for investigating and reporting your issue!
I'm genuinely puzzled; we're running Ubuntu 18.04 throughout the SCIONLab infrastructure, in automatic test setups and on various personal machines and have not encountered this behavior.

What I assume is the relevant configuration in the systemd unit file for the router (`/lib/systemd/system/scion-border-router@.service`) is the following line:
```
ExecStart=/usr/bin/scion-border-router --config /etc/scion/%i.toml
```
According to the documentation (`man systemd.unit`) this `%i` should expand to the instance name _not including_ the `.service` suffix:
>       │"%i"      │ Instance name            │ For instantiated units: this │
>       │          │                          │ is the string between the    │
>       │          │                          │ "@" character and the suffix │
>       │          │                          │ of the unit name.            │

This seems to work as expected for our service file on all our systems and it also matches my general experience with running other systemd services.

In order to help us find out what could be wrong, please provide us with some more information:
How did you install the packages and configuration on your host? Did you use the `scionlab-config` script, or did you install the configuration manually?
When your border router service did not start, how did you find out that this was the cause of it? Can you maybe share what steps you took and the logs?
Could you please also check which version of systemd is installed on your system, reported by `systemctl --version`. Although I've not found any reference to changes to the interpretation of this `%i` in the systemd changelog, it seems worth checking this.

**Comment by ahmetozer** [comment]
Thanks for returning.

I follow the document which is on [https://docs.scionlab.org/content/install/pkg.html#unpack-configuration-manually](https://docs.scionlab.org/content/install/pkg.html#unpack-configuration-manually) for the service enabling.

I use `scionlab-config` command that is created on scionlab.org/user/as/XXXX install type as **"SCION installation from packages"** 

```bash
# scionlab-config --host-id=xxxxxxxxxxxxxxxx --host-secret=xxxxxxxxxxxxxxxx
Created symlink /etc/systemd/system/scionlab.target.wants/scion-border-router@br-1.service → /lib/systemd/system/scion-border-router@.service.
Created symlink /etc/systemd/system/scionlab.target.wants/scion-control-service@cs-1.service → /lib/systemd/system/scion-control-service@.service.
Created symlink /etc/systemd/system/scionlab.target.wants/scion-daemon.service → /lib/systemd/system/scion-daemon.service.
Created symlink /etc/systemd/system/scionlab.target.wants/scion-dispatcher.service → /lib/systemd/system/scion-dispatcher.service.
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
.................................................................+..............+...............+............................................................+.......................................................................................................................................................+........................................................................................................................+.......................................................+................................................................................................+....................................................................................................................................................................................................................................................................................+...............................+................+..........................................+.......................................................................................................++*++*++*++*

# systemctl enable scion-border-router@br-1.service
# service  scion-border-router@br-1.service start
# service  scion-border-router@br-1.service status
● scion-border-router@br-1.service.service - SCION Border Router
   Loaded: loaded (/lib/systemd/system/scion-border-router@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-06-18 10:59:28 UTC; 7s ago
     Docs: https://www.scionlab.org
  Process: 335 ExecStart=/usr/bin/scion-border-router --config /etc/scion/br-1.service.toml (code=exited, status=1/FAILURE)
 Main PID: 335 (code=exited, status=1/FAILURE)

Jun 18 10:59:28 0235ce5b55c7 systemd[1]: scion-border-router@br-1.service.service: Service hold-off time over, scheduling restart.
Jun 18 10:59:28 0235ce5b55c7 systemd[1]: scion-border-router@br-1.service.service: Scheduled restart job, restart counter is at 5.
Jun 18 10:59:28 0235ce5b55c7 systemd[1]: Stopped SCION Border Router.
Jun 18 10:59:28 0235ce5b55c7 systemd[1]: scion-border-router@br-1.service.service: Start request repeated too quickl
y.
Jun 18 10:59:28 0235ce5b55c7 systemd[1]: scion-border-router@br-1.service.service: Failed with result 'exit-code'.

Jun 18 10:59:28 0235ce5b55c7 systemd[1]: Failed to start SCION Border Router
```

When the service is not started, I look `/etc/scion/` folder and br-1.toml is available. So I try to use with `ln -s /etc/scion/br-1.toml /etc/scion/br-1.service.toml` and it works.

```bash
# ln -s /etc/scion/br-1.toml /etc/scion/br-1.service.toml
# service  scion-border-router@br-1.service restart
#  service  scion-border-router@br-1.service status
● scion-border-router@br-1.service.service - SCION Border Router
   Loaded: loaded (/lib/systemd/system/scion-border-router@.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-06-18 11:04:46 UTC; 4s ago
     Docs: https://www.scionlab.org
 Main PID: 1134 (scion-border-ro)
```

Here is inside the service file.

```bash
# cat /lib/systemd/system/scion-border-router\@.service | grep toml
ExecStart=/usr/bin/scion-border-router --config /etc/scion/%i.toml
```

My systemd version.

```bash
# systemctl --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

I created a container for demonstration, `ahmetozer/scion:issue4064`
I hope it is helpful.

Best regards.

**Comment by matzf** [comment]
Alright, gotcha:
```
# service  scion-border-router@br-1.service start
# service  scion-border-router@br-1.service status
```

Unlike `systemctl` where the unit name may be given with or without the `.service` suffix, the `service` script appears to unconditionally append a `.service` to the given unit name. So the script invocation as above will internally invoke `systemctl start scion-border-router@br-1.service.service`; note the duplicate suffix, so the template instance name is parsed as `br-1.service`.
So, either use the `systemctl` commands directly or leave away the `.service` suffix when using the `service` script.

And just to clarify, by running the `scionlab-config` script, all the scion services have already been enabled and started -- that is, you don't manually handle the services at all. The documentation section on "manually unpacking the configuration" is meant as an _alternative_ to running this script.
