### ISSUE TITLE
addr: missing bounds check

### ISSUE THREAD

**Issue by jcp19** [scionproto/scion#4080]
I am currently verifying the correctness of the scion router and I found that, in the following function, there are bound checks in all "successful" cases except for the case of `HostTypeSVC`. Is there any undocumented assumption that ensures that this cannot fail or is this a memory safety problem, where you can possibly try to read an index of the slice out of bounds?

https://github.com/scionproto/scion/blob/cb2509fb65d7212b984bf8adee6db7168bfb05e2/go/lib/addr/host.go#L298-L317

**Comment by oncilla** [comment]
Hi @jcp19 

Thank you for reporting this. This looks to be a problem in the library, yes.

I don't think this could be triggered in the router, because we do proper bounds checks when decoding the packet here: https://github.com/scionproto/scion/blob/cb2509fb65d7212b984bf8adee6db7168bfb05e2/go/lib/slayers/scion.go#L427

Still, `addr.HostFromRaw` should do an explicit bounds check. Would you mind creating a PR to fix this?

Out of curiosity, how did you find this? Manual inspection or some type of fuzzing or statical analysis?

**Comment by jcp19** [comment]
I hope that PR #4081 addresses the issue :)

I found this problem with [Gobra](https://github.com/viperproject/gobra), a program verifier for Go.  Basically, the specification of `binary.BigEndian.Uint16` contains a **precondition** that disallows any call with an argument `s` whose length is less that 2. While trying to prove memory safety, Gobra complained that the call to `binary.BigEndian.Uint16(b)` is not safe because it is not guaranteed that the precondition is satisfied.

**Comment by oncilla** [comment]
@jcp19 ha, that is very neat.

How fast is Gobra at finding these kinds of problems? If it is reasonable fast enough, we could think of integrating it in our CI.

In any case, keep us posted if you find any other problems.

**Comment by jcp19** [comment]
Currently, it is hard to predict how Gobra would perform in the CI of SCION because we have been working mostly on verifying the implementation of the DataPlane in the border router, and it is hard to extrapolate how this would scale to the rest of the codebase. Nonetheless, we have concrete plans to look into integrating Gobra in CI workflows (e.g. [link](https://www.pm.inf.ethz.ch/education/student-projects/program-verification-in-continuous-integration-workflows.html)).

I should note however that integrating a tool like Gobra in the CI of SCION will require more effort from the developers to annotate their code with specifications.

**Comment by shitz** [comment]
Just to add to the discussion here. I spoke with Prof. Müller and we will organize a tech talk after the holiday season (sometime in August) where Gobra will be presented and where we can also discuss if and how we could integrate it in our QA efforts.
