### ISSUE TITLE
slayers: possible panic in the `SerializeTo` with receiver of type `Raw`

### ISSUE THREAD

**Issue by jcp19** [scionproto/scion#4094]
Hi :)
In the following excerpt, it seems to me that there is the implicit assumption that `len(s.Raw)` is at least `MetaLen`. Is this always true? if not, then it is possible that a panic occurs in the slicing operation (`s.Raw[:MetaLen]`).
https://github.com/scionproto/scion/blob/e4b728b87a7860d8901502efc77978fd97347d50/go/lib/slayers/path/scion/raw.go#L52-L56

If this is indeed a problem, then the simplest solution seems to be to remove the slicing operation because `s.PathMeta.SerializeTo` already performs a bounds check before writing to the buffer passed as argument.

**Comment by oncilla** [comment]
Hi @jcp19 

There is an implicit assumption here. The only place that raw is set, here:

https://github.com/scionproto/scion/blob/e4b728b87a7860d8901502efc77978fd97347d50/go/lib/slayers/path/scion/raw.go#L39

This means that `s.Raw` is non-nil, it is guaranteed to be of at least MetaLen length.
However, to protect against future changes, I think we should just drop the slicing as you suggested.

Care to create a PR?

**Comment by jcp19** [comment]
Yes, I will take care of this issue and the other occurrences of `s.Raw[:MetaLen]`.

**Comment by jiceatscion** [comment]
Since we haven't heard from jcp19, attempting to refactor as suggested.
