### ISSUE TITLE
Possibly missing synchronization in the `DataPlane.Run` method

### ISSUE THREAD

**Issue by jcp19** [scionproto/scion#4116]
Hi all,
in the `Run` method of the file [`dataplane.go`](https://github.com/scionproto/scion/blob/master/go/pkg/router/dataplane.go), it looks like every goroutine running the `read` closure consults the value of `d.running` (Line 455) to decide when to stop processing and forwarding messages. However, it seems to me that this is done without any kind of synchronization. According to the [Go memory model](https://golang.org/ref/mem) (section **Incorrect synchronization**), it can happen that a goroutine running `read` might not ever observe any changes to `d.running` made by other threads, and thus, it might not stop when it should.
https://github.com/scionproto/scion/blob/764d6e2afe4765acf24492746c197c32417a57c9/go/pkg/router/dataplane.go#L444-L456

Is this a bug or am I missing something here?

**Comment by oncilla** [comment]
Hi @jcp19 

Thanks for bringing this up. It is correct that this is not a valid way of synchronization.

Note that the only place that running is written is in the `Run` method itself, thus, there is no way to stop the go routines in the first place. The observation is correct, however. We should not read `d.running` in the for loop.

**Comment by jiceatscion** [comment]
@oncilla Besides the sloppy access to the flag, was there ever any intent that the router could be shutdown cleanly? It looks like the only real use of the flag is to detect attempts at hot reconfiguration. It migh even work in that case (although I'd have to check if it's all done from the same go-routine). Either way, it's easy to fix, but if there's no intention of requesting a router termination I might as well turn all the "for d.running" into "for".

**Comment by oncilla** [comment]
@jiceatscion a long time a go, the open-source and Anapaya internal implementation shared the control plane logic of the router.
Hot reloading was a feature that was supported by our internal implementation, but has never been translated into the open source. Since then we have moved away from sharing the control plane logic. 

IMO, yes, just change the for loop condition to solve the issue.

**Comment by jiceatscion** [comment]
Unfortunately, I found quite a few test cases that were relying on changing the flag to cause the dataplane to terminate (so, we know it works :-) ). So, I'd have to find some other way for these tests to effect a shutdown. On the other hand making the flag properly synchronized is easy enough. Even if the shutdown feature is only used by tests. Remains to be seen how much the bus-locking atomic access adds to the packet processing time :-(.
Stay tuned!

**Comment by oncilla** [comment]
easy, drop the tests :wink:

**Comment by jiceatscion** [comment]
So, the cost of the atomic flag is not measurable. I'm really not sure how to make do in tests without a way to shut down the go routines. So, here is a proper shutdown mechanism instead. It's really not complicated, so might as well.
