### ISSUE TITLE
possibly missing error check in resolveInbound in dataplane.go

### ISSUE THREAD

**Issue by LinoTelschow** [scionproto/scion#4126]
Hi all,
I might have found a problem.

The method `resolveInbound` calls the function `resolveLocalDst`. `resolveLocalDst` may return a nil and an error. These errors may not be catched by `resolveInbound`. This means `resolveInbound` will instead return a nil value for `*net.UDPAddr` and a nil value for the error.

This might be problematic, since the client code below might receive a nil for *net.UDPAddr` without realizing that an error occurred.

```
func (p *scionPacketProcessor) resolveInbound() (*net.UDPAddr, processResult, error) {
	a, err := p.d.resolveLocalDst(p.scionLayer)
	switch {
	case errors.Is(err, noSVCBackend):
		r, err := p.packSCMP(
			&slayers.SCMP{
				TypeCode: slayers.CreateSCMPTypeCode(slayers.SCMPTypeDestinationUnreachable,
					slayers.SCMPCodeNoRoute),
			},
			&slayers.SCMPDestinationUnreachable{}, err)
		return nil, r, err
	default:
		return a, processResult{}, nil
	}
}
```

```
func (d *DataPlane) resolveLocalDst(s slayers.SCION) (*net.UDPAddr, error) {
	dst, err := s.DstAddr()
	if err != nil {
		// TODO parameter problem.
		return nil, err
	}
	switch v := dst.(type) {
	case addr.HostSVC:
		// For map lookup use the Base address, i.e. strip the multi cast
		// information, because we only register base addresses in the map.
		a, ok := d.svc.Any(v.Base())
		if !ok {
			return nil, noSVCBackend
		}
		return a, nil
	case *net.IPAddr:
		return addEndhostPort(v), nil
	default:
		panic("unexpected address type returned from DstAddr")
	}
}
```

client code calling `resolveInbound`

```
// Inbound: pkts destined to the local IA.
	if p.scionLayer.DstIA.Equal(p.d.localIA) && int(p.path.PathMeta.CurrHF)+1 == p.path.NumHops {
		a, r, err := p.resolveInbound()
		if err != nil {
			return r, err
		}
		return processResult{OutConn: p.d.internal, OutAddr: a, OutPkt: p.rawPkt}, nil
	}
```

**Comment by oncilla** [comment]
Indeed, it looks like this could happen if we go into this branch:

https://github.com/scionproto/scion/blob/b5954eafc987875b1cdea6a85f66fae15a54178e/go/pkg/router/dataplane.go#L1304-L1307

I think currently the packet would just be dropped by the kernel. It would be nice however, if the appropriate SCMP message would be generated. Would you like to work on a fix for this?

**Comment by LinoTelschow** [comment]
Yes, I can fix it. I just need to know which SCMP message should be returned if we reach this branch:

```
if err != nil { 
 	// TODO parameter problem. 
 	return nil, err 
 } 
```

**Comment by oncilla** [comment]
This should be a parameter problem: https://scion.docs.anapaya.net/en/latest/protocols/scmp.html#parameter-problem

SMCP Type: 4
SCMP Code: 34 - Invalid destination address

To test your implementation you can add an acceptance test case for the router here:

https://github.com/scionproto/scion/blob/b5954eafc987875b1cdea6a85f66fae15a54178e/go/integration/braccept/main.go#L82

To run them locally, use the following command:
```
bazel test //acceptance/router_multi:test_nobfd
```

If you need more guidance, let me know :+1:

**Comment by LinoTelschow** [comment]
I would suggest to use the following fix:

```
func (p *scionPacketProcessor) resolveInbound() (*net.UDPAddr, processResult, error) {
	a, err := p.d.resolveLocalDst(p.scionLayer)
	switch {
	case errors.Is(err, invalidDstAddr):
		r, err := p.packSCMP(
			&slayers.SCMP{
				TypeCode: slayers.CreateSCMPTypeCode(slayers.SCMPTypeParameterProblem,
					slayers.SCMPCodeInvalidDestinationAddress),
			},
			&slayers.SCMPParameterProblem{Pointer: 0}, err)
		return nil, r, err
	case errors.Is(err, noSVCBackend):
		r, err := p.packSCMP(
			&slayers.SCMP{
				TypeCode: slayers.CreateSCMPTypeCode(slayers.SCMPTypeDestinationUnreachable,
					slayers.SCMPCodeNoRoute),
			},
			&slayers.SCMPDestinationUnreachable{}, err)
		return nil, r, err
	default:
		return a, processResult{}, nil
	}
}
```

I cannot specify a pointer address in the SCMPParameterProblem struct, since the Dst address has already been parsed when the resolveInbound is invoked.
