### ISSUE TITLE
Possibly missing check in SCION path DecodeFromBytes

### ISSUE THREAD

**Issue by LinoTelschow** [scionproto/scion#4133]
Hi all,

There might be some checks missing in this function:
This decoder first decodes the MetaHdr, then it counts the number of Info fields and hops. The MetaHdr decoder first decodes the current info field and hop number. The *Base decoder never checks if CurrINF and CurrHF are valid indices.
Is this behavior intended?
https://github.com/scionproto/scion/blob/362c4622084037cd1d3ac593d2d78128a86638fd/go/lib/slayers/path/scion/base.go#L51-L70
https://github.com/scionproto/scion/blob/362c4622084037cd1d3ac593d2d78128a86638fd/go/lib/slayers/path/scion/base.go#L125-L137

**Comment by shitz** [comment]
Hi @LinoTelschow 

Thanks for reporting this. Indeed the decoder could be enhanced by also verifying that the `CurrINF` and `CurrHF` indices indeed point to an existing info- and hop-field. We will take this up and add it.
