### ISSUE TITLE
Unnecessary computations performed in method `processIntraBFD`

### ISSUE THREAD

**Issue by jcp19** [scionproto/scion#4139]
Hi :)

The `continue` statement in the following loop seems to be irrelevant - the behavior of the loop is the same with or without it. I believe this was meant to be a `break`, with the goal of finishing the loop earlier when the interface ID is found.

https://github.com/scionproto/scion/blob/7d06a3efe494f96b9a9f0ac7787fa0f2dabfbde0/go/pkg/router/dataplane.go#L676-L681

**Comment by oncilla** [comment]
Hi @jcp19

Good catch. Indeed, this should be a `break` instead.
Do you want to create a PR to fix this, or should I take care of it?

**Comment by jcp19** [comment]
Sure, here it is :)

**Comment by lukedirtwalker** [comment]
Fixed by #4140, thanks
