### ISSUE TITLE
Adding checks to intra-segment forwarding to achieve stronger security

### ISSUE THREAD

**Issue by tklenze** [scionproto/scion#4148]
Hi all, and happy SCION Day. Sofia Giampietro and I (Tobias Klenze) from the Information Security group at ETH are formally proving the security of the SCION forwarding protocol. We believe that we have found a way for SCION to achieve stronger guarantees than it currently does given a powerful adversary.

### Already implemented check for segment switching
If a router needs to switch between segments (IsXover), then it checks that the ingress and egress interfaces are combined in a valid way (core-to-child, child-to-core, or child-to-child). In particular, L900-L907:
https://github.com/scionproto/scion/blob/bddecd65d2723ac60727300d47cedb1c3ec17562/go/pkg/router/dataplane.go#L877-L920

### Proposed new check for intra-segment forwarding
We propose a similar check for the case in which the router forwards a packet along a single segment. This check would only allow **child-to-parent**, **parent-to-child**, and **core-to-core** combinations, as well as packets coming from an **internal** interface. Such an explicit check would entail valley freedom. At the end of this post is a draft of how it could look like.

### Security analysis
What is this check useful for? If we assume a benign setting in which all paths being used are authorized, then the check is not necessary, since authorized paths are valley-free by construction.
In an adversarial setting, there are some attacker model in which this check can lead to stronger properties. We will focus here on an attacker model in which there is a malicious end host, who has compromised the AS keys of some ASes. The ASes themselves are assumed to act in an honest way, in particular the routers. The attacker can obtain authorized paths from the path server, and, using the keys of compromised ASes, the attacker can modify them, yielding forwarding paths with valid MACs that are not authorized in the control plane.

Given such a powerful attacker, it is clear that we cannot achieve much: for instance, path authorization goes down the drain if the attacker knows all relevant AS keys. However, we believe that the proposed additional check is sufficient to guarantee two stronger properties than the ones we can currently guarantee:

(i) We currently prove valley-free forwarding, assuming that an attacker does not know any keys of on-path ASes. (We could prove that the AS key of the "valley AS" has to be known, which is slightly stronger, but so far we have not). With the additional check, we think we can show valley-free forwarding even if **all AS keys** are known to the attacker.

(ii) We currently formally prove "loop freedom, unless there exists an on-loop AS whose key is known to the attacker". We think that the additional check would allow us to show that loops can only exist if **all on-loop AS keys** are known to the attacker. (NB: We define a loop as "the same link is traversed twice in the same direction by a packet". Infinite loops are ruled out in SCION due to the limitation to three segments and the maximum header size)

While the attacker model may sound unreasonably quite strong, I don't think it is. Imagine there is a bug in a widely used implementation of the router that would allow an attacker to obtain the AS keys. This attacker could instantly use the obtained keys to create arbitrary, unauthorized forwarding paths. By adding the proposed check, we ensure a baseline of forwarding security (e.g., ruling out valleys) is always achieved, even if keys are compromised.

### Proposed implementation
Rough sketch of how the check could be implemented in the "validateEgressID" function. Disclaimer: IANAGD -- I am not a Go developer
```go
        ingress, egress := p.d.linkTypes[p.ingressID], p.d.linkTypes[pktEgressID]
        if !p.segmentChange {
                // Check that the interface pair is valid within a single segment.
                // No check required if the packet is received from an internal interface.
                switch {
                case ingress == topology.Unset: // Tobias: Is this the correct check to see if an interface is internal?
                        return processResult{}, nil
                case ingress == topology.Core && egress == topology.Core:
                        return processResult{}, nil
                case ingress == topology.Child && egress == topology.Parent:
                        return processResult{}, nil
                case ingress == topology.Parent && egress == topology.Child:
                        return processResult{}, nil
                default: // error handling...
                }
        } else {
                // Check that the interface pair is valid on a segment switch.
                // Having a segment change received from the internal interface is never valid.
                switch {
                case ingress == topology.Core && egress == topology.Child:
                        return processResult{}, nil
                case ingress == topology.Child && egress == topology.Core:
                        return processResult{}, nil
                case ingress == topology.Child && egress == topology.Child:
                        return processResult{}, nil
                default: // error handling...
                }
        }
```

**Comment by tklenze** [comment]
Any comments on this proposal? I think this is a rather low hanging fruit in terms of adding safeguards to the SCION data plane.

**Comment by matzf** [comment]
In the dev chat, @oncilla has signalled approval and I'm also in favor of accepting this proposal. No objections have been raised so far.

This [proposal process](https://docs.scion.org/en/latest/contribute.html#formal-process) is new, so I'm still figuring out how to best do this; we don't need a more detailed design document for this, so the final comment period of 10 days can start immediately. If no objections are raised during this period, this proposal will be **accepted**.

**Comment by tklenze** [comment]
Great! Now that the proposal is accepted, what is the next step? I suppose someone has to create a pull request. Could someone take care of that? I am not a Go developer and I am a bit afraid of breaking things.
By the way, we have a paper about our verification effort coming up in December. It would be amazing if we could implement this proposal until then, as we could then write about it in the paper.

**Comment by matzf** [comment]
I've assigned this to me, I'll implement this. I'll try to get this done soonish.
