### ISSUE TITLE
Refactor addr.HostAddr types

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4149]
The `addr.HostAddr` type hierarchy is currently organized around this base interface:
```go
type HostAddr interface {
	Size() int
	Type() HostAddrType
	Pack() []byte
	IP() net.IP
	Copy() HostAddr
	Equal(HostAddr) bool
	fmt.Stringer
}
```
This interface is implemented by the types `HostNone`, `HostIPv4`, `HostIPv6` and `HostSVC`. 
The `Pack` and `Size` methods are not really used, as `slayers` uses separate serialization logic, based on separate types. The same is true for the `HostFromRaw` parsing function.

The `slayers` library does not generally use these `HostAddr` types. Instead, it relies on `net.Addr` with explicit type assertions to `net.IPAddr` and `addr.HostSVC`. The `net.Addr` interface here is merely a convention, none of the interface methods are actually used.

This situation is not ideal:
- creating `HostAddr` always allocates -- this cannot be fixed with the interface type.
- the `HostIPv4`/`HostIPv6` split is unnecessary as the `IP` is already aware of the type
- `HostAddr` is not a value type, cannot be used as map key etc.
- different "world" of address types in `slayers` and everywhere else
- arbitrarily pretends that `HostSVC` is a `net.Addr`

---

#### Proposal
Replace the `HostAddr` type hierarchy with a single value type `Host`.
This type is opaque, allowing to internally change or extend the representation.

```go
type Host struct {
	ip  netaddr.IP
	svc SVC         // could squeeze this into ip, is it worth it?
	t   HostAddrType
}

func (h Host) Type() HostAddrType {
	return h.t
}

func (h Host) IP() netaddr.IP {
	if h.t != HostTypeIP {
		panic("IP called on non-IP address")
	}
	return h.ip
}

func (h Host) SVC() SVC {
	if h.t != HostTypeSVC {
		panic("SVC called on non-SVC address")
	}
	return h.svc
}

func (h Host) String() string { ... }

// HostIP creates a Host address of type IP
func HostIP(ip netaddr.IP) Host {
	return Host{t: HostTypeIP, ip: ip}
}

// HostIPFromStd is a hopefully temporary conversion function to create a Host of type IP from net.IP.
// Panics if ip does not have length 4 or 16.
// Unmaps IPv6-mapped IPv4 addresses.
func HostIPFromStd(ip net.IP) Host {
	a, ok := netaddr.FromStdIP(ip)
	if !ok {
		panic("invalid ip")
	}
	return HostIP(a)
}

func HostSVC(svc SVC) Host {
	return Host{t: HostTypeSVC, svc: svc}
}


type HostAddrType uint8
const (
	HostTypeNone HostAddrType = iota
	HostTypeIP   // merged IPv4/IPv6
	HostTypeSVC
)

// SVC -- renamed from HostSVC, without the HostAddr methods
type SVC uint16
const (
	SvcDS       SVC = 0x0001
	SvcCS       SVC = 0x0002
	SvcWildcard SVC = 0x0010
	SvcNone     SVC = 0xffff

	SVCMcast SVC = 0x8000
)
```

This `Host` type is adopted in
- `snet.SCIONAddress` and so `snet.Packet`
- `slayers.SCION` in `{Get,Set}{Src,Dst}Addr`, getting rid of internal type assertions

The `HostAddressType` enum is used in the dispatcher's "reliable" protocol. To allow combining
`HostTypeIPv4` and `HostTypeIPv6` without breaking compatibility, the enum is re-defined with the
old values in the dispatcher package.

This allows the router dataplane to use `slayers.SCION.GetDstAddr` without allocations.
We do need to introduce a number of conversion from `net.IP` to `netaddr.IP` -- as we gradually adopt
`netaddr.IP` et al (or in the future `net/netip.Addr`), these conversions should disappear.

**Comment by lukedirtwalker** [comment]
I agree that the current situation is not ideal and I also think we should improve it.

I just checked where the HostAddr is actually used currently and there are not a lot of places.
I wonder if we shouldn't go a step further:
- Complete drop the `HostAddr` type without replacement.
- Rename `HostSVC` to `SVC` as you suggested.
- Move what you suggested with the `Host` type into the `snet.SCIONAddress`
- Drop the `DstAddr()` and `SrcAddr()` helper methods from slayers, I think almost all use cases would be better off by directly using the `s.SrcAddrType, s.SrcAddrLen, s.RawSrcAddr` fields.
- The dispatcher thing we can do as you suggest.

Hope that makes sense.

**Comment by matzf** [comment]
Interesting, I had not considered that. This does seem like a good idea :+1: 

> Move what you suggested with the Host type into the snet.SCIONAddress

Just to clarify, you'd "flatten" the `SCIONAddress` type by moving the fields and methods of the `Host` member to `SCIONAddress`, is that right? The type would become, roughly:
```go
type SCIONAddress struct {
	ia   addr.IA
	ip  netaddr.IP
	svc SVC
	t   HostAddrType
}
```

If we touch this, we could also rename it, I've always found `SCIONAddress` doesn't really fit with any of the other type names in `snet`. Maybe `Host` or `HostAddr` then, given these have just become available?

---

> Drop the DstAddr() and SrcAddr() helper methods from slayers, I think almost all use cases would be better off by directly using the s.SrcAddrType, s.SrcAddrLen, s.RawSrcAddr fields.

The `Set{Src,Dst}Addr` functions are used in a large number of tests. If we drop these convenience methods, I think we'd have to introduce some helpers in a different place -- setting all three members everywhere seems cumbersome and error prone otherwise.
By the way, separating out the `{Src,Dst}AddrType` from the respective `Len` field seems somewhat complicated here, anyway. We don't lose anything if we treat the `Len/Type` as an opaque, combined identifier. The length is represented by the slice length of the addr field. If we go down this route without convenience getter/setters, perhaps we can simplify this too.

**Comment by lukedirtwalker** [comment]
Yeah `snet.HostAddr` sounds good to me as you suggested. I do like types with public members though because it's easier to construct. Maybe we could consider something like this for the snet package:
```go
type Addr interface {
	addr() // just a random private method so that no other package can implement this interface.
}

type SVCAddr struct {
	IA addr.IA
	SVC SVC
}

type HostAddr struct {
	IA addr.IA
	IP netaddr.IP
}
```
This way we can still leverage the type system of Go, the construction of an address is really convenient and for the extraction of IP or SVC we need a type switch instead of a switch over the type.

---

Re the `Set{Src,Dst}Addr` I would keep those, I was only thinking to remove the getter versions of it. I agree with the combination of Len/Type though.

**Comment by matzf** [comment]
If we keep the `Set{Src,Dst}Addr` functions, what type should these have? If we add new address types only to `snet` (vs `addr`), these are not available for this interface in `slayers`. Part of the motivation of this proposal was that the current function interface, taking a `net.Addr` with internal type assertions, is clunky and requires allocations.

Having separate types and an interface does indeed seem more convenient, but as far as I understand it also unavoidably leads to heap allocations.

**Comment by matzf** [comment]
#4346 implements the proposed API and additionally adds `addr.Addr` as a replacement for `snet.SCIONAddress`.

Any further comments on this?

**Comment by matzf** [comment]
#4346 has been reviewed and it looks like this PR, implementing this here proposal, will likely be accepted.

Unless any objections are raised in the 10 day final comment period, this proposal and the PR will be accepted.

**Comment by matzf** [comment]
No objections have been raised, so this proposal is now **accepted**.
