### ISSUE TITLE
Verify TRC ISD identifier

### ISSUE THREAD

**Issue by FR4NK-W** [scionproto/scion#4170]
The `scion-pki` tool does not have a way to verify that the ISD ID  of a TRC matches a specific ISD ID during TRC verification.

Parsing the output of the `trc human` command to verify the ISD identity of a TRC file is not really a solution for CLI usage.

**Comment by oncilla** [comment]
Closed in https://github.com/scionproto/scion/commit/03034e35b1fcb404d41ae891187f3c6014f48416
