### ISSUE TITLE
router: `AddLinkType` does not acquire the `DataPlane` mutex

### ISSUE THREAD

**Issue by jcp19** [scionproto/scion#4282]
Unlike all other `AddX` methods such as `AddInternalInterface`, `AddExternalInterface`, and `AddNeighborIA`, the method `AddLinkType` does not acquire the `DataPlane` mutex and does not return `modifyExisting` if it is already running. Is this something that was overlooked?

https://github.com/scionproto/scion/blob/780bf4cb9863838b3c901d4a015cd3c7f09664ec/router/dataplane.go#L241-L250

**Comment by jcp19** [comment]
Should I open a PR for this? The comment says `This can only be called on a not yet running dataplane.`, but the setter does not check that the router is not running

**Comment by jiceatscion** [comment]
Thanks for the careful scrutiny. I'll go have a second look but, if memory serves, this is part of the initialization path (hence the comment). It is not meant to be called once the interfaces are being used. Someone can always modify the code and call it the wrong context, of course, but then one can also modify the code to divide by zero. Not sure such mistakes can be prevented in the general case (esp since go has pretty limited scoping features). Did you see that function actually being called in a racy way?

**Comment by jcp19** [comment]
I am not aware of any racy call to this function, but at the same time, it is a public function and a client may choose to call it in any way they want. I understand what you mean by "Someone can always modify the code and call it the wrong context", but why then do we have the check that the router is not running in `SetIA`, `SetKey`, `AddInternalInterface`, `AddExternalInterface`, `AddNeighborIA`, `AddExternalInterfaceBFD`, `AddNextHop`, and `AddNextHopBFD`? From the user's perspective, it may be confusing that some of these setters will return with an error, where for others it may cause a race condition.

The reason I reported this is that I thought that someone overlooked this, as I did not see any reason for this setter to differ from the others in this regard. Being consistent here also leads to a more consistent specification of the methods in the router in the context of the VerifiedSCION project, although I would say that this is a minor point.

**Comment by jiceatscion** [comment]
After seeing where it is called from, I have to agree. There does not seem to be anything confining the execution of this to an initialization context. Actually, I have trouble finding how Connector.AddExternalInterface is used. Deferring to Dominik here. He appears to have authored these parts.

**Comment by jiceatscion** [comment]
#4614 is the fix
