### ISSUE TITLE
ci: AT hidden_paths is flaky

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4301]
The hidden_paths integration test is flaky on the CI infrastructure. As far as I remember, this had not been flaky on the old buildkite AWS stack, only on the new infrastructure. Possibly it's just a small thing like adjusting a timeout value.

**Comment by jiceatscion** [comment]
https://github.com/scionproto/scion/pull/4398 includes an attempt at deflaking the hidden_path test. It was flaky on my own machine too; as soon as I switched to docker compose v2. My guess is that the slow starting of containers actually did provide some helpful delays in the right places. While tuning the delays I also noticed that switching my laptop to high performance made failure more likely.
