### ISSUE TITLE
path server doesn't verify paths

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#436]
As path server doesn't seem to do any verification of the validity of paths, doing the following means that it will hand out invalid paths for a long time:

```
./scion.sh topology
./scion.sh run # wait a bit
./scion.sh stop
./scion.sh topology # to invalidate all the certs/keys/etc
./scion.sh run
```

The routers will logs will then have `"Dropping packet due to incorrect MAC."` continuously being added.

**Comment by kormat** [comment]
This is still broken. https://gist.github.com/kormat/bd5c4c90093bf20c6ed9332ebabb8439 is how it looks today on master.

@pszalach - is there a timeline for fixing this?

**Comment by shitz** [comment]
Path Servers properly verify PCBs now (modulo cross-signatures on TRCs that have not been implemented yet)
