### ISSUE TITLE
proposal: do not exit process in log.HandlePanic

### ISSUE THREAD

**Issue by oncilla** [scionproto/scion#4360]
Currently, `log.HandlePanic` immediately aborts the process.

https://github.com/scionproto/scion/blob/595839f08d2a9570d767845da4c08e11755e2aaa/pkg/log/log.go#L125-L137

This behavior does not allow applications to catch panics and recover from them, or do clean up work before exiting the process.
The behavior was introduced in https://github.com/scionproto/scion/commit/c69ca6c42de517551237df03e539f030fa18bbca to avoid swallowing panics.

Instead of aborting the process, we should just re-panic.
The effects are the same, the process will notice that a go routine has panicked, because it is bubbled up.
However, it would allow us to handle panics (when possible) and do clean up work in parent go routines if necessary.

**Comment by matzf** [comment]
I don't have strong opinion on changing this from `os.Exit(255)` to `panic(msg)`. Note that this will change the exit code (exits with 2) and it seems to dirty the log a little bit (as the runtime reprints the panic), but that's no big problem in my opinion. 

Can you explain how you want to use this to do clean up work in the parent go routine? As I understand it, panics don't bubble up to the parent go routine. The [language specification says](https://go.dev/ref/spec#Handling_panics):

> While executing a function F, an explicit call to panic or a [run-time panic](https://go.dev/ref/spec#Run_time_panics) terminates the execution of F. Any functions [deferred](https://go.dev/ref/spec#Defer_statements) by F are then executed as usual. Next, any deferred functions run by F's caller are run, and so on **up to any deferred by the top-level function in the executing goroutine. At that point, the program is terminated** and the error condition is reported, including the value of the argument to panic. This termination sequence is called panicking.

Some playground experiments confirm this, the panic does not bubble up to the parent goroutine to be recovered. Are you thinking of adding some custom machinery to pass panics up the chain somehow?

**Comment by oncilla** [comment]
> Can you explain how you want to use this to do clean up work in the parent go routine? As I understand it, panics don't bubble up to the parent go routine.

Indeed, there was an misunderstanding on how panics are propagated on my side.

Thanks for the quote!
