### ISSUE TITLE
Wireshark crashing with unquoted scion.dst_host in filter

### ISSUE THREAD

**Issue by sarcasticadmin** [scionproto/scion#4395]
## Description

Utilizing the latest version of the wireshark plugin: https://github.com/scionproto/scion/blob/468618633db29e36835923b24fcb7dcdf93c261d/tools/wireshark/scion.lua

The following filter causes wireshark to crash:

```
scion.dst_host == 127.0.0.1
```

The following filter works against a scion packet capture:

```
scion.dst_host == "127.0.0.1"
```

## Expected behavior

Error raised if filter input needs to be of type string

## System Info

Wireshark: `Version 4.0.8 (v4.0.8-0-g81696bb74857)`
Windows 11: `Version 22H2 (OS Build 22621.2283)`

**Comment by jiceatscion** [comment]
Apparently that is no-longer possible:

![image](https://github.com/user-attachments/assets/d434b533-1130-4d67-806e-bc1507eb19c9)

My Wireshark: Version 4.2.4 (Git commit c966d79150b6).
