### ISSUE TITLE
## Specify router performance goal in context of target platform

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4407]

**Comment by jiceatscion** [comment]
We have two well-tested sample platforms, all tested with 3 non-performance cores. Both with a shared 2 MB L2 cache.

1 - 10 cores 3.5 GHz 13th Gen Intel(R) Core(TM) i7
2 - 4 cores 1GHz AMD Puma model 48 S-o-C

For the router as it is today, we have a provisional performance index of about 30 (varies, unfortunately from 27 to 32 depending on platform).

On our two platforms we have the following measurement results:

AMD:

* "coremark": 2889,
* "mmbm": 246.25,
* "packet_size":172, 
* "rate": 44253, [60 Mbit/s]

Intel:

* "coremark": 29826,
* "mmbm": 3751,
* "packet_size": 172,
* "rate": 651073, [895 Mbit/s]

We have established the following extrapolation formula:

* rate = performance_index / (1.0 / coremark + 400 * PACKET_LEN / (mmbm * 1024 * 1024))
  Where mmbm is one of the measurements of the mmbm benchmark selected for its relevance to the router's workload.

One of the mmbm measurements is "mmbm_large_allmiss", it measures the copy rate of large blocks (4K) assuming a large arena (such as that used by the router) which causes 100% TLB misses and 100% cache misses. We can use this and our extrapolation formula to predict the router's performance under an assumption of ordinary 1024 byte packets.

AMD:

* "coremark": 2889
* "mmbm_large_allmiss": 719.51,
* "size":1024,
* "rate": 30369, [250 Mbit/s]

Intel:

* "coremark": 29826,
* "mmbm_large_allmiss": 4104.84,
* "size":1024,
* "rate": 209775 (1.7 Gbit/s)

This is not a stretch goal. This is what we should expect based on the data we already have.

It is likely possible to significantly reduce the number of TLB misses in the router. However, for medium to large packets, eliminating cache misses is not realistic.

Assuming TLB misses can be mostly avoided. We should expect the following numbers:

AMD:

* "coremark": 2889,
* "size":1024,
* "mmbm_large_cachemiss": 725.7,
* "rate": 30528, [249 Mbit/s]

Intel:

* "coremark": 29826,
* "size":1024,
* "mmbm_large_cachemiss": 13865.37,
* "rate": 518628 (4.2 Gbit/s)

The projected performance number of the AMD device are quite low, but then it is a very low-end device. Also, analyzing its memory behavior has proven quite difficult, so this prediction is uncertain.

Regarding the Intel platform, we seem to be able to get close to 5 GBit/s. So, for the sake of setting a stretch goal, we shall endeavor to reach that number by finding further optimizations in the router.

**Comment by jiceatscion** [comment]
The object of this issue was to establish a target. This is hereby done.
