### ISSUE TITLE
## Design and implement translation of local router performance metrics to target platform predicted performance

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4408]
The outcome of this task is a router performance model and a set of tools:
The model defines a router performance index as a function of:
* the observed router throughput on a given platform
* the performance characteristics of that platform
That is such that the router's performance index value depends only on the router's implementation.

The tools facilitate the process of:
* Collecting the characteristics of a platform
* Measuring the router's throughput on said platform
* Calculating the router's performance index based on the model
* Reporting and recording the above.
* Predicting the throughput of a router on an hypothetical platform, given the router's performance index and that platform's characteristics.

**Comment by jiceatscion** [comment]
Uh, this wasn't meant to be closed until both PRs where in.

**Comment by jiceatscion** [comment]
This effort is now concluded. PR 4496 has all the necessary tooling:
* microbenchmarks for memory and arithmetic performance
* independent script to run the router benchmark against an external router
* router benchmark library that automatically collects benchmark results and calculates the performance index
* a document explaining the performance index formula.

The performance model itself, which results in the performance index formula, isn't nearly as good as we'd want it to be. However there is only that much we can invest in it. The document describes the difficulties encountered and the resulting limitations in the model.

This will close once the PR is merged.
