### ISSUE TITLE
Docker compose - unknown flag: --compatibility

### ISSUE THREAD

**Issue by edoardottt** [scionproto/scion#4433]
### Env info
- Linux Ubuntu 23.04 6.2.0-36-generic
- Bazel 6.4.0
- Docker 24.0.5
- Docker compose v2.12.2

### Issue description
I've just downloaded locally the master branch of scion with
```console
git clone https://github.com/scionproto/scion
```
and I'm following this guide https://docs.scion.org/en/latest/dev/setup.html.

Done with Prerequisites, I'm stuck at point 4 of Bazel section.

When I run 
```console
./scion.sh bazel-remote
```

I get the error: 
```
unknown flag: --compatibility
See 'docker --help'.
```

I guess this is an error of docker compose V2.

References:
- https://github.com/docker/compose/issues/8618
- https://github.com/docker/compose/pull/8637
- https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2

**Comment by matzf** [comment]
Thanks for reporting this @edoardottt.

I don't quite understand which versions of docker compose have this flag, and which ones don't, but either way it doesn't do anything useful.
As it happens, I've already had a branch where I've been cleaning this up, #4396.

**Comment by edoardottt** [comment]
Thanks @matzf. If this can help, using [`this command`](https://github.com/scionproto/scion/pull/4396/files#diff-0b2711294c05591582ed85e4c57f86246ec19867ad9b1659b3ee7f94c58b2f4eR9)

gives me this error:
```
unknown shorthand flag: 'f' in -f
See 'docker --help'.
```

**Comment by matzf** [comment]
That's what I'd get if I invoke `docker -f bazel-remote.yml up -d`, instead of `docker compose -f ...` . Is it at all possible that you mis-copy-pasted/mistyped?  Otherwise, this seems quite bizarre.

**Comment by matzf** [comment]
That's so weird, it looks like in some way the `compose` in the commandline is lost or ignored. Are there some aliases, wrapper functions or scripts involved somewhere?
What happens with `docker compose version`?

**Comment by edoardottt** [comment]
```console
$> docker compose version
Docker Compose version v2.12.2
```

**Comment by edoardottt** [comment]
Hi @matzf, idk why but just tried again with latest changes and it looks like 
```console
USER_ID="$uid" GROUP_ID="$gid" docker compose -f bazel-remote.yml up -d
```

works fine.

**Comment by matzf** [comment]
Excellent. Sorry to not have been any help, but glad it works now :+1:
