### ISSUE TITLE
Building fails on cab6ce389b5ba96c5e7cdbaf0591ffca99aafd42

### ISSUE THREAD

**Issue by nixinator** [scionproto/scion#4436]
[build.log](https://github.com/scionproto/scion/files/13258213/build.log)

I've also tried to build other revisions, and they also fail.

So it's quite possible that it's 'my machine'.

I' ve tried build off some tags too, and they all complain about 'nogo' 

I'll see if can turn that off.

Thanks for your help.

**Comment by nixinator** [comment]
This is quite clearly a bug

**Comment by jiceatscion** [comment]
Could not reproduce at the given commit ID. Obviously cannot reproduce at head.
