### ISSUE TITLE
[acceptance tests] docker logs fetching is wrong with the new container names

### ISSUE THREAD

**Issue by JordiSubira** [scionproto/scion#4473]
After https://github.com/scionproto/scion/pull/4396 the handling of `scion` prefixes and containers name is different. Scion service containers get started with the following name pattern: scion-<svc_id>-1, where <svc_id> is the service identifier, e.g. br1-ff00_0_1-1. However, when fetching the logs for the acceptance tests (https://github.com/scionproto/scion/blob/master/acceptance/common/docker.py#L61) the issued command is of the following form: docker logs svc_id, rendering the following error in the output dir for logs: `Error response from daemon: No such container br1-ff00_0_1-1`.

**Comment by jiceatscion** [comment]
Jordi fixed it as part of #4344
