### ISSUE TITLE
make test-integration & make docker-image fails because of wrong hash.

### ISSUE THREAD

**Issue by Andraax** [scionproto/scion#4480]
Hello, I want to setup the scion dev environment but I am running into an issue when making the test integration for it. Here's the error:
![error-scion-hash](https://github.com/scionproto/scion/assets/32449863/5ac63c10-c0e6-4525-b1f8-1a9324beb18b)
I checked the file and get this hash instead of the intended one:
![tmp-hash](https://github.com/scionproto/scion/assets/32449863/8eaf18e3-3231-41c9-998d-f9a917d6e535)
How can I solve this issue and proceed to build the environment correctly?
I need to precise that make and make test are working but this error occurs for make test-integration and make docker-images. 
I am on a virtualized Ubuntu 22.04.3 LTS.

**Comment by oncilla** [comment]
Hi @Andraax 

We have observed this issue in combination with a recent docker release. It appears that the [rules_docker](https://github.com/bazelbuild/rules_docker) that we are using is incompatible with the latest docker version.

The long term fix is to adopt [rules_oci](https://github.com/bazel-contrib/rules_oci).

As a temporary workaround, you can downgrade your docker version as described in this slack thread:
https://scionproto.slack.com/archives/C8ADA9CEP/p1708592627637149?thread_ts=1708537828.158799&cid=C8ADA9CEP

```
sudo apt-get autoremove docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
VERSION_STRING=5:24.0.7-1~ubuntu.22.04~jammy
sudo apt-get install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-buildx-plugin docker-compose-plugin
```

Just to confirm, what is your currently installed docker version?

For me, the following works without any issues:
```
$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Andraax** [comment]
Thanks, downgrading to docker 24.0.7 resolved my issue and now I am able to run SCION.
