### ISSUE TITLE
topology: allow peering links between core-ASes

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4484]
Currently, the topology loader forbids core ASes from having peering links (i.e. links with `"link_to": "peer"`). The validation check is here: https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/private/topology/topology.go#L544-L550.
As far as I'm aware, there is no technical reason why core ASes cannot have peering links. 
Core ASes should be able to have peering links to any other AS, i.e. to both core or non-core ASes in both the same or different ISDs.

**Comment by jiceatscion** [comment]
Both Anapaya and Adrian confirm that there's no reason to prohibit peering between core ASes. So my update to the draft should stand. As for fiing the code, that's a pretty minor issue comparatively. Just change the snippet that Matthias copied here and the associated tests if any.
