### ISSUE TITLE
[lint] protobufer types should(n't) be named after RPC name

### ISSUE THREAD

**Issue by JordiSubira** [scionproto/scion#4485]
Currently the linting complains if we want to use the well-known types `google.protobuf.Empty` https://protobuf.dev/reference/protobuf/google.protobuf/#empty. 

> proto/daemon/v1/daemon.proto:40:19:RPC request type "Empty" should be named "PortRangeRequest" or "DaemonServicePortRangeRequest".

In the same document, they encourage to use it to avoid duplicity and having a myriad of protobuf types which are empty. Is there a good reason why we would like to have one empty type for request?

**Comment by matzf** [comment]
Done, in  #4344 we've set `rpc_allow_google_protobuf_empty_requests`/`rpc_allow_google_protobuf_empty_responses` to `true` in `buf.yaml`.

FWIW, the rationale for disallowing the Empty type is _source code_ compatibility (which is what the tooling that "buf" sells wants to achieve); if Empty needs to be changed to something non-empty, the generated wrapper code will have different types. In the wire format, this is perfectly compatible. I don't see that we're striving for this level of automatic and complete API compatibility, so allowing to use Empty is fine.
