### ISSUE TITLE
doc: clarify SCMP reality vs. ambition

### ISSUE THREAD

**Issue by matzf** [scionproto/scion#4528]
The SCMP "specification" document (in doc/protocols/scmp.rst) currently describes support for SCMP as mandatory. Furthermore, it mandates the use of SPAO+DRKey authentication for SCMPs.
This does not correspond to what is currently implemented. SCMP support has been treated as at least semi-optional e.g. in discussions around the dispatcher-less end host stack. Regarding the authentication, there is no full implementation of this neither in router (support in "our" router is experimental/demo-level, no other router implementation supports it at all) nor in end hosts (currently, nothing at all). There is not sufficiently clear consensus around this to pretend that we'll realize this ambition shortly. The documentation specs should be updated to reflect this reality, the authentication part can be moved into a design document.

**Comment by nicorusti** [comment]
Thanks a lot for opening this!  JFYI, this issue relates to: 
- Authentication https://github.com/scionproto/scion/issues/3969 
- SCMP in the current IETF data plane draft  https://github.com/scionassociation/scion-dp_I-D/issues/8
