### ISSUE TITLE
private/app/path: IA ignored in Sort function

### ISSUE THREAD

**Issue by olibeck** [scionproto/scion#4596]
I came accross the `Sort` function in `path.go` and as I understand it, it should sort paths (in decreasing priority) by length,  IA, ID and expiry time. Currently the `IA` step is skipped due to a minor bug in the following line: https://github.com/scionproto/scion/blob/ad503c1fb89ba583093e2ea8004c7acd5027e010/private/app/path/path.go#L49

I assume the second `intfA[i].IA` should be `intfB[i].IA`.

The more I think about it, I think the whole IA check might be unnecessary. As a given interface always leads to the same IA, sorting the interface IDs also sorts the next IAs. I think there are only two scenarios in which not doing the IA check would change the order and I'm not sure if they are even possible:
- Paths with different starting IAs,
- The same interface leading to two different IAs.

**Comment by oncilla** [comment]
Hi @olibeck 

Thanks for reporting this.

You are correct. It mostly doesn't matter. However there are some fringe edge cases if we start out on different ASes, or if there are invalid segments in the mix. Let's err on the safe side and just fix the typo, as this should give us a deterministic ordering.

I have opened up #4600 to address this.
