### ISSUE TITLE
scion cannot propagate IP-level errors

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#470]
Assuming SCION is using IP-overlay, if an ip error happens within an AS, the icmp message generated will be sent to the ingress router, but does not [contain enough information](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Data) for the router to create an SCMP message to send back to the client:

> ICMP error messages contain a data section that includes the entire IPv4 header, plus the first eight bytes of data from the IPv4 packet that caused the error message. The ICMP packet is then encapsulated in a new IPv4 packet.

This implies if all devices on the entire path do not support scion, we cannot detect/propagate errors.

**Comment by scrye** [comment]
This is a problem that is difficult to solve, and we'll need to work around the lack of ICMP. Luckily, SCMP is informational and does not need reliable delivery (so all SCION speakers can tolerate the lack of SCMP signaling).

If an AS wants to reply with SCMP in the event of ICMP errors, they can deploy internal mechanisms to do so, but this is outside the scope of SCION. Closing as Won't fix.
