### ISSUE TITLE
Refactor code to be closer to 1 class per module.

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#488]
The current code base has a small number of large modules, containing many classes each. This causes major headaches when circular imports occur. E.g.: http://dpaste.com/3PJ2AR3

By refactoring into separate smaller modules, this can greatly reduce the complexity of imports. Here's an example solution to the above problem: https://gist.github.com/kormat/91bff3868718d65a8068

This would also make it much easier to find the relevant code.

**Comment by shitz** [comment]
This has been addressed in newer code and definitely in everything written in Go. Since we are transitioning much of the codebase to Go anyway we will have to see what happens to the existing Python code at which point a new issue might be needed.
