### ISSUE TITLE
Beacon server doesn't know enough about available bandwidth

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#538]
In SIBRA, beacons must contain the available steady and ephemeral bandwidth for each hop. The problem is that the routers are the source of this information, and they can't usefully insert it into beacons. So, all routers need to be informing all local BSes about their available bandwidths. @pszalach suggests adding this to the KeepAlive messages, which probably makes sense.

**Comment by scrye** [comment]
This is quite outdated by now, and will be revisited as part of the [Colibri service](https://anapaya-scion.readthedocs-hosted.com/en/latest/ColibriService.html). Closing this, we will open a new issue if this problem pops up again.
