### ISSUE TITLE
IF state update messages need to be authenticated

### ISSUE THREAD

**Issue by shitz** [scionproto/scion#584]
Currently, IF state messages, sent from the master BS to the ERs within an AS, are not authenticated. This would allow an attacker to fake an IF state update message, e.g., an attacker could make an ER believe that another interface is down for which then this ER would incorrectly drop packets and issue revocations.

Possible solutions:
1) Add a MAC to each IF state update. Since ERs and BSes within the same AS already have preshared keys this can be a symmetric MAC.

2) Since revocation tokens form a hash-chain, only the initial IF state update has to be authenticated. From then on an ER can authenticate incoming IF state updates by checking that H(new_token) == current_token.

**Comment by kormat** [comment]
Option 1 sounds good. We can wrap IFID & IFStateUpdate in a `SignedBlob` (and have the ingress BR sign it for IFID packets) with a MAC derived from the AS master key.

It might not be a bad idea to do this for _all_ infra intra-AS traffic.

**Comment by Oncilla** [comment]
IF state does no longer exist.
Border router track link health themselves now
