### ISSUE TITLE
Certificate and TRC distribution.

### ISSUE THREAD

**Issue by pszal** [scionproto/scion#603]
Previously, BSes, PSes, and end hosts requested certificate servers for a
missing TRC/certificate (when they could not verify a path segment). However, it
introduces unnecessary complexity and dependency on certificate servers (and
their consistency).  

I think that easier and cleaner way to certificate/TRC distribution is to use
path infrastructure. We need only guarantee that: BS/PS which caches a path
segment must have all information needed (i.e., TRCs & certificates) to verify
this path segment. This seems to be quite easy to guarantee. For instance, if a
BS tries to register a path at a PS, and this PS does not have a corresponding
certificate, then he queries the BS for this certificate (the BS must have this
certificate, otherwise he should not register the path).  Similar for PCB
propagation, and end-host requests. In this setting certificate server would be
just a store of TRCs and certificates, and would initiate TRC/certificate update
among local infrastructure.

Alternatively we could attach certificate/TRC to path segments, to eliminate
circular dependencies completely, but the overhead would be significant.

What do you think?

**Comment by shitz** [comment]
Certs and TRCs can either be requested directly from a CS or from the upstream/previous beacon server in case of beacon propagation. This has been implemented.
