### ISSUE TITLE
cPS fails resolving remote non-core ASes if relevant core seg is missing

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#643]
Steps required for this to happen:
1. cPS queries remote ISD for down-seg to a target AS.
2. the down-segs returned all start at a core AS the cPS doesn't have a core-seg to.
3. the cPS then fails to resolve the path.

Step 2 can happen if either the relevant core-seg has expired, or if the cPS is non-master and happens to not have the core-seg cached.

**Comment by shitz** [comment]
This has been fixed by adding support to ask SCIOND for paths in the CS.
