### ISSUE TITLE
PathTransportExt cannot carry long paths

### ISSUE THREAD

**Issue by pszal** [scionproto/scion#704]
`PathTransportExt` can carry paths in data- and control-plane formats. As extension's payload is capped to 2KB, every longer path cannot be sent in a single extension.
We could split longer paths into multiple extension headers, ... or just reconsider whether it is a good idea to transport long messages via packet extensions.

**Comment by kormat** [comment]
We can consider keeping this extension, but _only_ for data-plane paths. Path Segments are just too large.

**Comment by scrye** [comment]
The new extension format also allows payloads up to 2KB (see #3715).

Headers this large will run into many other issues, and we never needed to carry this much data in the extension itself. Closing this until we hit a wall with extension sizes.
