### ISSUE TITLE
core path servers give up on propagation if they don't have a path to another core as

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#741]
E.g.: https://circleci.com/gh/netsec-ethz/scion/2829

Here's the sequence of events:
- infrastructure startup took from 08:45:06 to 08:45:45
- sb2-23-1 registered a steady path with ps2-21-1 at 08:45:45
- ps2-21-1 did not yet have a path to 2-22, so it didn't propagate the registered path
- ps2-21-1 receives a path to 2-22 at 08:45:48, as the bs in 2-22 is finally up and running
- ps2-21-1 doesn't try propagate the sibra segment again until it is renewed, at 08:47:16
  by this time the sibra extension test has timed out.

The problem is that the path server couldn't propagate at registration time, and doesn't try again when it does get the path it needed, so the propagation doesn't happen until the sibra segment is renewed ~90s later.

**Comment by scrye** [comment]
The Go Control Service will periodically try to propagate on all relevant interfaces, so this should be fixed now.
