### ISSUE TITLE
Don't build full paths when src/dst are on-path

### ISSUE THREAD

**Issue by aznair** [scionproto/scion#753]
PathCombinator has plenty of problems but here I'd like to focus on a particularly dumb one.
Consider getting paths from AS 17 to AS 14, where the relevant ASes are:
11 (core)
  |
14 (intermediate)
  |
17 (leaf)
A host in AS 17 first builds the obvious shortcut path: 17 -> 14
It then proceeds to build full paths, including: 17 -> 14 -> 11 -> 14
When this full path is taken, er1_14-er1_17 goes ahead and delivers the packet to the destination instead of the next hop router because it sees that it is in the destination AS.
This is fine for the one packet, but the receiver in AS 14 will save the reversed full path with an incorrect first hop (should be er1_14er1_11).
So when the receiver later tries to send its own packets on this path, the packet will be dropped due to having incorrect IOF/HOF indexes.

Apparently we've been considering marking OFs as "deliverable" which will help here (@pszalach you're probably on TCP full-time for a while but any timeline for this?), and also PathCombinator should not build this full path to begin with.

This hasn't really been a problem so far because all our tests use only the first path given by sciond and receivers never create packets from scratch, only reverse incoming packets. Both of these assumptions fail for SSP which is where the problem was discovered.

**Comment by shitz** [comment]
This is fixed in the new path combinator.

**Comment by kormat** [comment]
@shitz : are you sure? i thought that was "future work"

**Comment by shitz** [comment]
@kormat you are right. Reopened.

**Comment by scrye** [comment]
Fixed by #1696.
