### ISSUE TITLE
Inconsistent naming of cert vs cert chain

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#754]
- beacon server's `_get_my_cert` actually returns a cert chain.
- trust store's `add_cert`/`get_cert` etc talk only about certs, but actually only deal with cert chains.

This makes things much more confusing than it needs to be.

**Comment by scrye** [comment]
This issue refers to the now-deprecated Python code. The Go code makes a clear distinction between a Certificate and a Certificate Chain:

https://github.com/scionproto/scion/blob/a85aede1c1521d2709d29d779091312a0ae50919/go/lib/scrypto/cert/chain.go#L27
