### ISSUE TITLE
(Python) PathCombinator badly needs a rewrite

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#761]
Pathcombinator has long been the worst code in the tree. It's gotten to the point where it's effectively untestable (e.g. `_join_shortcuts` is ~50 lines of highly complex code). This really needs a refactoring, and to be moved into a separate module.

**Comment by shitz** [comment]
The Python sciond implementation gets soon superseded by the new Go sciond. In any case, specifically the path combinator part has already been rewritten in Go.
