### ISSUE TITLE
Major renaming

### ISSUE THREAD

**Issue by pszal** [scionproto/scion#803]
- PCB -> PSB (path segment beacon)
- ASMarking -> ASEntry
- PCBMarking -> HopEntry
- edge router -> border router
- end2end path -> forwarding path
- InfoOpaqueField -> InfoField
- _beaconing_ instead of _dissemination/propagation_
- _registration_ instead of _propagation_ (among PSes)

ref: https://github.com/netsec-ethz/scion-doc/issues/53

**Comment by shitz** [comment]
`PathSegment`: The control-plane data-structure that holds a path segment
`PCB`: A packet that contains a `PathSegment` under construction.

**Comment by kormat** [comment]
This renaming is happening in the go codebase, but we are not going to rename the python codebase, and will just use the new names as services/libraries are implemented in Go.

**Comment by scrye** [comment]
Python servers are no longer under development and will soon be deprecated, so closing this.
