### ISSUE TITLE
More comprehensive topology

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#830]
The existing topology isn't comprehensive enough
- all core ASes only have a single child
- only single links between any pair of ASes
- no peer links between leaf ASes

We need to make a list of all scenarios we want to test, and make a minimal topology to cover those.

**Comment by kormat** [comment]
This should be done after #1466 is merged, as it removes the (old) 1-12 zookeepers, meaning we'll have more room to breathe inside the 4G ram limit of circleci.

**Comment by shitz** [comment]
Relatedly: Now that the BR supports multiple external interfaces we should also consolidate some BRs to properly test various cross-over cases.

**Comment by shitz** [comment]
Also a childless core needs to be added

**Comment by sgmonroy** [comment]
For each of the use cases, we want to test the BR for:
- internal to external
- external to internal
- external to external

Use cases:
* no segment change
* up -> core
* core -> down
* up -> down
* up -> down (in core)
* up -> down (peer)
* up -> down (shortcut)
