### ISSUE TITLE
Sync with the book

### ISSUE THREAD

**Issue by pszal** [scionproto/scion#933]
Please post here minor (?) TODOs:
1. ~~Move `HdrLen` just before `TotalLen`  (see \label{fig:packet-format-com-header}).~~
2. ~~Compute lengths/offsets (`CurrINF, CurrHF, HdrLen, ExtHdrLen`) as in the book (i.e., `len`*8).~~
3. Remove path-segment support from the path carrying extension.
4. ~~Do not remove signatures while converting PCBs to path segments.~~
5. Implement the path policy extension.
6. ~~Check PBKDF~~ #978 
7. ~~Check listings in the host structure chapter with the current API~~
8. ~~CBC-MAC -> CMAC~~

**Comment by kormat** [comment]
9. Change address order (in both common and address headers)
10. topology format.

**Comment by Oncilla** [comment]
11. sync TRC file:
 - add "ExpirationTime"
 - rename "ISDID" -> "ISD"
 - rename "QuorumEEPKI" -> "ThresholdEEPKI"
 - change CertLog entry from public key to cert
 - add dict to RootCAs entries with ("Certificate", "OnlineKeyAlg", "OnlineKey", "TRCSrv", "ARPKISrv", 
"ARPKIKey")
 - delete "RootRainsKey" to "RAINS"
 - add dict to "RAINS" with ("RootRAINSKey", "OnlineKeyAlg", "OnlineKey", "TRCSrv")
12. sync Cert file:
 - rename "SubjectSigKey" -> "SubjectSignKey"
