### ISSUE TITLE
Use powers of ten for network bandwidth everywhere.

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#942]
The standard for network bandwidth is powers of ten (https://en.wikipedia.org/wiki/Data_rate_units). I know the SIBRA code currently uses powers of 2, and needs to be fixed. This may also apply elsewhere.

**Comment by scrye** [comment]
This is probably no longer relevant, as SIBRA has been replaced by the [Colibri service](https://anapaya-scion.readthedocs-hosted.com/en/latest/ColibriService.html). In any case, arbitrary bandwidths should be supported, so closing this.
