### ISSUE TITLE
BS fails with ZkNoNodeError

### ISSUE THREAD

**Issue by pszal** [scionproto/scion#951]
From an overnight test. BS reconnects to ZK, and `pcb_cache.expire()` raises unhandled `ZkNoNodeError` (isn't `pcb_cache` synchronized at that point?):
https://gist.github.com/pszalach/b1ef5385299dfe8eed68bf67977b3bbb

**Comment by kormat** [comment]
This is a locking failure. Both BSes in 1-13 believed they held the lock.

bs1-13-2: `2016-12-13 17:17:03.667715+00:00 [INFO] (BS.worker) Successfully acquired ZK lock (epoch 3)`
bs1-13-1: `2016-12-13 17:17:04.443968+00:00 [INFO] (BS.worker) Successfully acquired ZK lock (epoch 3)`

**Comment by worxli** [comment]
This was an issue in the python BS, both the python BS and zookeeper have been removed.
