### ISSUE TITLE
Instrumentation and monitoring of infrastructure

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#984]
We need to add prometheus metrics to our infrastructure code, and automate generation of prometheus scrape configs to monitor the infrastructure. The go router already has some metrics, but probably needs some more.

**Comment by kormat** [comment]
We also need prometheus' alertmanager service, and have some paging in place.

**Comment by kormat** [comment]
As part of instrumentation, we also need to do a huge cleanup on the logging in the python code. It's a huge amount of noise, and rarely useful as-is.

**Comment by shitz** [comment]
Processes export prometheus metrics and also the logging in python has been cleaned up to the extent where further big improvements probably won't be made for the Python implementation.
